// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"

	"github.com/99designs/gqlgen/graphql"
)

type AddInventoryItemInput struct {
	ShopID          string          `json:"shopId"`
	ItemName        string          `json:"itemName"`
	Description     *string         `json:"description,omitempty"`
	Barcode         *string         `json:"barcode,omitempty"`
	Category        *string         `json:"category,omitempty"`
	UnitOfMeasure   *string         `json:"unitOfMeasure,omitempty"`
	CostPrice       *float64        `json:"costPrice,omitempty"`
	SellingPrice    *float64        `json:"sellingPrice,omitempty"`
	StockQuantity   *int            `json:"stockQuantity,omitempty"`
	ReorderLevel    *int            `json:"reorderLevel,omitempty"`
	Photo           *graphql.Upload `json:"photo,omitempty"`
	VisualClassKeys []string        `json:"visualClassKeys,omitempty"`
}

type AuthResponse struct {
	User        *User  `json:"user"`
	AccessToken string `json:"accessToken"`
}

type AvailableSlot struct {
	Table     *RestaurantTable `json:"table"`
	StartTime string           `json:"startTime"`
	EndTime   string           `json:"endTime"`
}

type Booking struct {
	ID              string        `json:"id"`
	RestaurantID    string        `json:"restaurantId"`
	CustomerID      string        `json:"customerId"`
	TableID         *string       `json:"tableId,omitempty"`
	PartySize       int           `json:"partySize"`
	BookingTime     string        `json:"bookingTime"`
	DurationMinutes int           `json:"durationMinutes"`
	Status          BookingStatus `json:"status"`
	SpecialRequests *string       `json:"specialRequests,omitempty"`
	PaymentStatus   PaymentStatus `json:"paymentStatus"`
	Source          BookingSource `json:"source"`
	CreatedAt       string        `json:"createdAt"`
	UpdatedAt       string        `json:"updatedAt"`
}

type BusinessHours struct {
	OpenTime  string   `json:"openTime"`
	CloseTime string   `json:"closeTime"`
	Days      []string `json:"days"`
}

type BusinessHoursInput struct {
	OpenTime  string   `json:"openTime"`
	CloseTime string   `json:"closeTime"`
	Days      []string `json:"days"`
}

type CallLog struct {
	ID            string       `json:"id"`
	RestaurantID  *string      `json:"restaurantId,omitempty"`
	VapiCallID    string       `json:"vapiCallId"`
	CustomerPhone *string      `json:"customerPhone,omitempty"`
	BookingID     *string      `json:"bookingId,omitempty"`
	Transcript    *string      `json:"transcript,omitempty"`
	Outcome       *CallOutcome `json:"outcome,omitempty"`
	CreatedAt     string       `json:"createdAt"`
}

type CheckAvailabilityInput struct {
	RestaurantID  string `json:"restaurantId"`
	PartySize     int    `json:"partySize"`
	RequestedTime string `json:"requestedTime"`
}

type CheckoutBatch struct {
	ID          string               `json:"id"`
	ShopID      string               `json:"shopId"`
	SoldAt      string               `json:"soldAt"`
	TotalItems  int                  `json:"totalItems"`
	TotalCost   float64              `json:"totalCost"`
	GrossSale   float64              `json:"grossSale"`
	GrossProfit float64              `json:"grossProfit"`
	Items       []*CheckoutBatchItem `json:"items"`
}

type CheckoutBatchItem struct {
	ID              string  `json:"id"`
	InventoryItemID string  `json:"inventoryItemId"`
	ItemName        string  `json:"itemName"`
	Quantity        int     `json:"quantity"`
	CostPrice       float64 `json:"costPrice"`
	SellingPrice    float64 `json:"sellingPrice"`
	LineCostTotal   float64 `json:"lineCostTotal"`
	LineSaleTotal   float64 `json:"lineSaleTotal"`
}

type CheckoutBatchItemInput struct {
	ItemID   string `json:"itemId"`
	Quantity int    `json:"quantity"`
}

type CheckoutBatchSyncInput struct {
	LocalID         string                    `json:"localId"`
	ShopID          string                    `json:"shopId"`
	ClientCreatedAt *string                   `json:"clientCreatedAt,omitempty"`
	Items           []*CheckoutBatchItemInput `json:"items"`
}

type CheckoutCartInput struct {
	ShopID string                    `json:"shopId"`
	Items  []*CheckoutBatchItemInput `json:"items"`
}

type Closure struct {
	ID          string  `json:"id"`
	ClosureDate string  `json:"closureDate"`
	Reason      *string `json:"reason,omitempty"`
}

type ContactDetails struct {
	Phone   *string `json:"phone,omitempty"`
	Email   *string `json:"email,omitempty"`
	Address *string `json:"address,omitempty"`
}

type ContactDetailsInput struct {
	Phone   *string `json:"phone,omitempty"`
	Email   *string `json:"email,omitempty"`
	Address *string `json:"address,omitempty"`
}

type Coordinates struct {
	Lat float64 `json:"lat"`
	Lng float64 `json:"lng"`
}

type CoordinatesInput struct {
	Lat float64 `json:"lat"`
	Lng float64 `json:"lng"`
}

type CreateBookingInput struct {
	RestaurantID    string         `json:"restaurantId"`
	CustomerID      string         `json:"customerId"`
	TableID         *string        `json:"tableId,omitempty"`
	PartySize       int            `json:"partySize"`
	BookingTime     string         `json:"bookingTime"`
	SpecialRequests *string        `json:"specialRequests,omitempty"`
	Source          *BookingSource `json:"source,omitempty"`
	IdempotencyKey  string         `json:"idempotencyKey"`
}

type CreateClosureInput struct {
	RestaurantID string  `json:"restaurantId"`
	ClosureDate  string  `json:"closureDate"`
	Reason       *string `json:"reason,omitempty"`
}

type CreateMenuItemInput struct {
	RestaurantID string   `json:"restaurantId"`
	Name         string   `json:"name"`
	Description  *string  `json:"description,omitempty"`
	PriceCents   int      `json:"priceCents"`
	Category     *string  `json:"category,omitempty"`
	Allergens    []string `json:"allergens,omitempty"`
}

type CreatePostInput struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type CreateRestaurantInput struct {
	Name                   string       `json:"name"`
	Phone                  string       `json:"phone"`
	Email                  *string      `json:"email,omitempty"`
	AddressLine1           string       `json:"addressLine1"`
	Suburb                 string       `json:"suburb"`
	State                  string       `json:"state"`
	Postcode               string       `json:"postcode"`
	Timezone               *string      `json:"timezone,omitempty"`
	CuisineType            *string      `json:"cuisineType,omitempty"`
	SeatingType            *SeatingType `json:"seatingType,omitempty"`
	DefaultTurnDurationMin *int         `json:"defaultTurnDurationMin,omitempty"`
	BookingBufferMin       *int         `json:"bookingBufferMin,omitempty"`
	MaxPartySize           *int         `json:"maxPartySize,omitempty"`
}

type CreateShopInput struct {
	ShopName       string                `json:"shopName"`
	Address        string                `json:"address"`
	Description    *string               `json:"description,omitempty"`
	BusinessHours  *BusinessHoursInput   `json:"businessHours"`
	PaymentMethods *PaymentMethodsInput  `json:"paymentMethods"`
	Delivery       *DeliveryOptionsInput `json:"delivery"`
	SocialMedia    *SocialMediaInput     `json:"socialMedia"`
	ContactDetails *ContactDetailsInput  `json:"contactDetails"`
	Coordinates    *CoordinatesInput     `json:"coordinates"`
	Photo          *graphql.Upload       `json:"photo,omitempty"`
	Photos         []*graphql.Upload     `json:"photos,omitempty"`
}

type CreateTableInput struct {
	RestaurantID string  `json:"restaurantId"`
	TableNumber  string  `json:"tableNumber"`
	CapacityMin  int     `json:"capacityMin"`
	CapacityMax  int     `json:"capacityMax"`
	Section      *string `json:"section,omitempty"`
}

type CreateWaitlistEntryInput struct {
	RestaurantID  string `json:"restaurantId"`
	CustomerID    string `json:"customerId"`
	PartySize     int    `json:"partySize"`
	RequestedTime string `json:"requestedTime"`
}

type Customer struct {
	ID        string  `json:"id"`
	Phone     string  `json:"phone"`
	Name      *string `json:"name,omitempty"`
	Email     *string `json:"email,omitempty"`
	CreatedAt string  `json:"createdAt"`
}

type DailySalesMetric struct {
	DayName       string  `json:"dayName"`
	FormattedDate string  `json:"formattedDate"`
	GrossSale     float64 `json:"grossSale"`
	GrossProfit   float64 `json:"grossProfit"`
}

type DecrementStockInput struct {
	ItemID           string `json:"itemId"`
	QuantityToRemove int    `json:"quantityToRemove"`
}

type DeliveryOptions struct {
	Available bool     `json:"available"`
	Radius    *float64 `json:"radius,omitempty"`
	Fee       *float64 `json:"fee,omitempty"`
	MinOrder  *float64 `json:"minOrder,omitempty"`
}

type DeliveryOptionsInput struct {
	Available bool     `json:"available"`
	Radius    *float64 `json:"radius,omitempty"`
	Fee       *float64 `json:"fee,omitempty"`
	MinOrder  *float64 `json:"minOrder,omitempty"`
}

type DeltaResponse struct {
	Upserted   []map[string]any `json:"upserted"`
	DeletedIds []string         `json:"deletedIds"`
	Rejected   []*SyncRejection `json:"rejected"`
}

type FindOrCreateCustomerInput struct {
	Phone string  `json:"phone"`
	Name  *string `json:"name,omitempty"`
	Email *string `json:"email,omitempty"`
}

type GoogleLoginInput struct {
	Code string `json:"code"`
}

type HourlySalesMetric struct {
	Hour         int `json:"hour"`
	Transactions int `json:"transactions"`
	ItemsSold    int `json:"itemsSold"`
}

type IncrementStockInput struct {
	ItemID        string `json:"itemId"`
	QuantityToAdd int    `json:"quantityToAdd"`
}

type InventorySyncInput struct {
	LocalID         string          `json:"localId"`
	ShopID          string          `json:"shopId"`
	IsDeleted       bool            `json:"isDeleted"`
	IsServerSynced  bool            `json:"isServerSynced"`
	ClientCreatedAt *string         `json:"clientCreatedAt,omitempty"`
	ItemName        string          `json:"itemName"`
	Description     *string         `json:"description,omitempty"`
	Barcode         *string         `json:"barcode,omitempty"`
	Category        *string         `json:"category,omitempty"`
	UnitOfMeasure   *string         `json:"unitOfMeasure,omitempty"`
	CostPrice       *float64        `json:"costPrice,omitempty"`
	SellingPrice    *float64        `json:"sellingPrice,omitempty"`
	StockQuantity   *int            `json:"stockQuantity,omitempty"`
	ReorderLevel    *int            `json:"reorderLevel,omitempty"`
	Photo           *string         `json:"photo,omitempty"`
	NewPhoto        *graphql.Upload `json:"newPhoto,omitempty"`
	VisualClassKeys []string        `json:"visualClassKeys,omitempty"`
}

type InviteRestaurantStaffInput struct {
	RestaurantID string             `json:"restaurantId"`
	Email        string             `json:"email"`
	Role         RestaurantUserRole `json:"role"`
}

type ItemActionHistory struct {
	ID              string  `json:"id"`
	ShopID          string  `json:"shopId"`
	InventoryItemID *string `json:"inventoryItemId,omitempty"`
	ItemName        string  `json:"itemName"`
	Action          string  `json:"action"`
	Quantity        *int    `json:"quantity,omitempty"`
	Date            string  `json:"date"`
}

type ItemActionHistorySyncInput struct {
	LocalID         string  `json:"localId"`
	ShopID          string  `json:"shopId"`
	InventoryItemID *string `json:"inventoryItemId,omitempty"`
	ItemName        string  `json:"itemName"`
	Action          string  `json:"action"`
	Quantity        *int    `json:"quantity,omitempty"`
	ClientCreatedAt string  `json:"clientCreatedAt"`
}

type MenuItem struct {
	ID           string   `json:"id"`
	RestaurantID string   `json:"restaurantId"`
	Name         string   `json:"name"`
	Description  *string  `json:"description,omitempty"`
	PriceCents   int      `json:"priceCents"`
	Category     *string  `json:"category,omitempty"`
	IsAvailable  bool     `json:"isAvailable"`
	Allergens    []string `json:"allergens"`
	SortOrder    int      `json:"sortOrder"`
}

type Mutation struct {
}

type OperatingHours struct {
	ID        string  `json:"id"`
	DayOfWeek int     `json:"dayOfWeek"`
	OpenTime  *string `json:"openTime,omitempty"`
	CloseTime *string `json:"closeTime,omitempty"`
	IsClosed  bool    `json:"isClosed"`
}

type OwnerInventoryItem struct {
	ID              string   `json:"id"`
	ShopID          string   `json:"shopId"`
	ItemName        string   `json:"itemName"`
	Description     *string  `json:"description,omitempty"`
	Barcode         *string  `json:"barcode,omitempty"`
	Category        *string  `json:"category,omitempty"`
	UnitOfMeasure   *string  `json:"unitOfMeasure,omitempty"`
	Photo           *string  `json:"photo,omitempty"`
	SellingPrice    *float64 `json:"sellingPrice,omitempty"`
	StockQuantity   *int     `json:"stockQuantity,omitempty"`
	CostPrice       *float64 `json:"costPrice,omitempty"`
	ReorderLevel    *int     `json:"reorderLevel,omitempty"`
	VisualClassKeys []string `json:"visualClassKeys"`
	UpdatedAt       string   `json:"updatedAt"`
	DeletedAt       *string  `json:"deletedAt,omitempty"`
	ServerUpdatedAt *string  `json:"serverUpdatedAt,omitempty"`
}

type OwnerShop struct {
	ID              string           `json:"id"`
	OwnerID         string           `json:"ownerId"`
	Owner           *User            `json:"owner"`
	ShopName        string           `json:"shopName"`
	Coordinates     *Coordinates     `json:"coordinates"`
	Description     *string          `json:"description,omitempty"`
	BusinessHours   *BusinessHours   `json:"businessHours"`
	PaymentMethods  *PaymentMethods  `json:"paymentMethods"`
	Delivery        *DeliveryOptions `json:"delivery"`
	SocialMedia     *SocialMedia     `json:"socialMedia"`
	Verification    *Verification    `json:"verification"`
	ContactDetails  *ContactDetails  `json:"contactDetails"`
	Status          *ShopStatus      `json:"status"`
	Address         string           `json:"address"`
	Photo           *string          `json:"photo,omitempty"`
	Photos          []string         `json:"photos"`
	CreatedAt       string           `json:"createdAt"`
	DeletedAt       *string          `json:"deletedAt,omitempty"`
	ServerUpdatedAt *string          `json:"serverUpdatedAt,omitempty"`
}

type PaginatedCheckoutBatches struct {
	Batches     []*CheckoutBatch `json:"batches"`
	TotalCount  int              `json:"totalCount"`
	HasNextPage bool             `json:"hasNextPage"`
}

type PaginatedItemActionHistory struct {
	Records     []*ItemActionHistory `json:"records"`
	TotalCount  int                  `json:"totalCount"`
	HasNextPage bool                 `json:"hasNextPage"`
}

type PaginatedOwnerInventory struct {
	Items       []*OwnerInventoryItem `json:"items"`
	TotalCount  int                   `json:"totalCount"`
	HasNextPage bool                  `json:"hasNextPage"`
}

type PaginatedOwnerShops struct {
	Shops       []*OwnerShop `json:"shops"`
	TotalCount  int          `json:"totalCount"`
	HasNextPage bool         `json:"hasNextPage"`
}

type PaginatedPosts struct {
	Posts       []*Post `json:"posts"`
	TotalCount  int     `json:"totalCount"`
	HasNextPage bool    `json:"hasNextPage"`
}

type PaginatedPublicProducts struct {
	Products    []*PublicProduct `json:"products"`
	TotalCount  int              `json:"totalCount"`
	HasNextPage bool             `json:"hasNextPage"`
}

type PaginatedShops struct {
	Shops       []*Shop `json:"shops"`
	TotalCount  int     `json:"totalCount"`
	HasNextPage bool    `json:"hasNextPage"`
}

type PaymentMethods struct {
	Cash    bool `json:"cash"`
	Gcash   bool `json:"gcash"`
	Paymaya bool `json:"paymaya"`
	Card    bool `json:"card"`
}

type PaymentMethodsInput struct {
	Cash    bool `json:"cash"`
	Gcash   bool `json:"gcash"`
	Paymaya bool `json:"paymaya"`
	Card    bool `json:"card"`
}

type Post struct {
	ID        string `json:"id"`
	Title     string `json:"title"`
	Content   string `json:"content"`
	UserID    string `json:"userId"`
	CreatedAt string `json:"createdAt"`
}

type PublicProduct struct {
	ID            string   `json:"id"`
	ShopID        string   `json:"shopId"`
	ItemName      string   `json:"itemName"`
	Description   *string  `json:"description,omitempty"`
	Category      *string  `json:"category,omitempty"`
	UnitOfMeasure *string  `json:"unitOfMeasure,omitempty"`
	Photo         *string  `json:"photo,omitempty"`
	SellingPrice  *float64 `json:"sellingPrice,omitempty"`
	StockQuantity *int     `json:"stockQuantity,omitempty"`
	MatchScore    *float64 `json:"matchScore,omitempty"`
	MatchType     *string  `json:"matchType,omitempty"`
	Barcode       *string  `json:"barcode,omitempty"`
}

type Query struct {
}

type RecordScanEventInput struct {
	ShopID             string   `json:"shopId"`
	InventoryItemID    *string  `json:"inventoryItemId,omitempty"`
	TopVisualCandidate *string  `json:"topVisualCandidate,omitempty"`
	VisualDistance     *float64 `json:"visualDistance,omitempty"`
	OcrText            *string  `json:"ocrText,omitempty"`
	ResolvedName       *string  `json:"resolvedName,omitempty"`
	MatchType          string   `json:"matchType"`
}

type RefreshResponse struct {
	AccessToken string `json:"accessToken"`
	User        *User  `json:"user"`
}

type Restaurant struct {
	ID                     string             `json:"id"`
	Name                   string             `json:"name"`
	Phone                  string             `json:"phone"`
	Email                  *string            `json:"email,omitempty"`
	AddressLine1           string             `json:"addressLine1"`
	Suburb                 string             `json:"suburb"`
	State                  string             `json:"state"`
	Postcode               string             `json:"postcode"`
	Timezone               string             `json:"timezone"`
	CuisineType            *string            `json:"cuisineType,omitempty"`
	SeatingType            SeatingType        `json:"seatingType"`
	DefaultTurnDurationMin int                `json:"defaultTurnDurationMin"`
	BookingBufferMin       int                `json:"bookingBufferMin"`
	MaxPartySize           int                `json:"maxPartySize"`
	Description            *string            `json:"description,omitempty"`
	ParkingInfo            *string            `json:"parkingInfo,omitempty"`
	IsActive               bool               `json:"isActive"`
	Tables                 []*RestaurantTable `json:"tables"`
	OperatingHours         []*OperatingHours  `json:"operatingHours"`
	Closures               []*Closure         `json:"closures"`
	CreatedAt              string             `json:"createdAt"`
	UpdatedAt              string             `json:"updatedAt"`
}

type RestaurantAuthResponse struct {
	Owner       *RestaurantOwner `json:"owner"`
	AccessToken string           `json:"accessToken"`
}

type RestaurantLoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type RestaurantOwner struct {
	ID          string                 `json:"id"`
	FirstName   string                 `json:"firstName"`
	LastName    string                 `json:"lastName"`
	Email       string                 `json:"email"`
	Restaurants []*RestaurantStaffRole `json:"restaurants"`
	CreatedAt   string                 `json:"createdAt"`
	UpdatedAt   string                 `json:"updatedAt"`
}

type RestaurantRefreshResponse struct {
	AccessToken string           `json:"accessToken"`
	Owner       *RestaurantOwner `json:"owner"`
}

type RestaurantRegisterInput struct {
	FirstName string `json:"firstName"`
	LastName  string `json:"lastName"`
	Email     string `json:"email"`
	Password  string `json:"password"`
}

type RestaurantStaffRole struct {
	Restaurant *Restaurant        `json:"restaurant"`
	Role       RestaurantUserRole `json:"role"`
}

type RestaurantTable struct {
	ID           string  `json:"id"`
	RestaurantID string  `json:"restaurantId"`
	TableNumber  string  `json:"tableNumber"`
	CapacityMin  int     `json:"capacityMin"`
	CapacityMax  int     `json:"capacityMax"`
	Section      *string `json:"section,omitempty"`
	IsActive     bool    `json:"isActive"`
}

type RestaurantUser struct {
	ID           string             `json:"id"`
	RestaurantID string             `json:"restaurantId"`
	Name         string             `json:"name"`
	Email        string             `json:"email"`
	Phone        *string            `json:"phone,omitempty"`
	Role         RestaurantUserRole `json:"role"`
	CreatedAt    string             `json:"createdAt"`
}

type SetOperatingHoursInput struct {
	DayOfWeek int     `json:"dayOfWeek"`
	OpenTime  *string `json:"openTime,omitempty"`
	CloseTime *string `json:"closeTime,omitempty"`
	IsClosed  *bool   `json:"isClosed,omitempty"`
}

type Shop struct {
	ID             string           `json:"id"`
	ShopName       string           `json:"shopName"`
	Address        string           `json:"address"`
	Coordinates    *Coordinates     `json:"coordinates"`
	Description    *string          `json:"description,omitempty"`
	BusinessHours  *BusinessHours   `json:"businessHours"`
	PaymentMethods *PaymentMethods  `json:"paymentMethods"`
	Delivery       *DeliveryOptions `json:"delivery"`
	SocialMedia    *SocialMedia     `json:"socialMedia"`
	Verification   *Verification    `json:"verification"`
	ContactDetails *ContactDetails  `json:"contactDetails"`
	Status         *ShopStatus      `json:"status"`
	Photo          *string          `json:"photo,omitempty"`
	Photos         []string         `json:"photos"`
	Reviews        []*ShopReview    `json:"reviews"`
	CreatedAt      string           `json:"createdAt"`
}

type ShopDashboardMetrics struct {
	TodaysGrossSales         float64             `json:"todaysGrossSales"`
	TodaysSalesGrowthPct     float64             `json:"todaysSalesGrowthPct"`
	WeeklyRevenueGrowthIndex float64             `json:"weeklyRevenueGrowthIndex"`
	AverageTicketSize        float64             `json:"averageTicketSize"`
	InventoryCapitalRatio    float64             `json:"inventoryCapitalRatio"`
	WeeklySalesTrend         []*DailySalesMetric `json:"weeklySalesTrend"`
}

type ShopReview struct {
	ID        string   `json:"id"`
	UserID    string   `json:"userId"`
	Rating    int      `json:"rating"`
	Comment   *string  `json:"comment,omitempty"`
	Photos    []string `json:"photos"`
	CreatedAt string   `json:"createdAt"`
}

type ShopStatus struct {
	IsActive bool `json:"isActive"`
}

type ShopSyncInput struct {
	LocalID         string                `json:"localId"`
	IsDeleted       bool                  `json:"isDeleted"`
	IsServerSynced  bool                  `json:"isServerSynced"`
	ClientCreatedAt *string               `json:"clientCreatedAt,omitempty"`
	ShopName        string                `json:"shopName"`
	Address         string                `json:"address"`
	Description     *string               `json:"description,omitempty"`
	Coordinates     *CoordinatesInput     `json:"coordinates"`
	BusinessHours   *BusinessHoursInput   `json:"businessHours"`
	PaymentMethods  *PaymentMethodsInput  `json:"paymentMethods"`
	Delivery        *DeliveryOptionsInput `json:"delivery"`
	SocialMedia     *SocialMediaInput     `json:"socialMedia"`
	ContactDetails  *ContactDetailsInput  `json:"contactDetails"`
	Photo           *string               `json:"photo,omitempty"`
	NewPhoto        *graphql.Upload       `json:"newPhoto,omitempty"`
	Photos          []string              `json:"photos,omitempty"`
	NewPhotos       []*graphql.Upload     `json:"newPhotos,omitempty"`
}

type SocialMedia struct {
	Facebook  *string `json:"facebook,omitempty"`
	Instagram *string `json:"instagram,omitempty"`
}

type SocialMediaInput struct {
	Facebook  *string `json:"facebook,omitempty"`
	Instagram *string `json:"instagram,omitempty"`
}

type SyncRejection struct {
	LocalID string `json:"localId"`
	Code    string `json:"code"`
	Reason  string `json:"reason"`
}

type UnifiedBatchSyncInput struct {
	LastSyncedAt    string                        `json:"lastSyncedAt"`
	Shops           []*ShopSyncInput              `json:"shops"`
	Inventory       []*InventorySyncInput         `json:"inventory"`
	Checkouts       []*CheckoutBatchSyncInput     `json:"checkouts"`
	ActionHistories []*ItemActionHistorySyncInput `json:"actionHistories"`
}

type UnifiedBatchSyncPayload struct {
	ShopsDelta           *DeltaResponse `json:"shopsDelta"`
	InventoryDelta       *DeltaResponse `json:"inventoryDelta"`
	CheckoutsDelta       *DeltaResponse `json:"checkoutsDelta"`
	ActionHistoriesDelta *DeltaResponse `json:"actionHistoriesDelta"`
	ServerTime           string         `json:"serverTime"`
}

type UpdateBookingInput struct {
	TableID         *string        `json:"tableId,omitempty"`
	PartySize       *int           `json:"partySize,omitempty"`
	BookingTime     *string        `json:"bookingTime,omitempty"`
	Status          *BookingStatus `json:"status,omitempty"`
	SpecialRequests *string        `json:"specialRequests,omitempty"`
	PaymentStatus   *PaymentStatus `json:"paymentStatus,omitempty"`
}

type UpdateInventoryItemInput struct {
	ItemID          string          `json:"itemId"`
	ItemName        string          `json:"itemName"`
	Description     *string         `json:"description,omitempty"`
	Barcode         *string         `json:"barcode,omitempty"`
	Category        *string         `json:"category,omitempty"`
	UnitOfMeasure   *string         `json:"unitOfMeasure,omitempty"`
	CostPrice       *float64        `json:"costPrice,omitempty"`
	SellingPrice    *float64        `json:"sellingPrice,omitempty"`
	StockQuantity   *int            `json:"stockQuantity,omitempty"`
	ReorderLevel    *int            `json:"reorderLevel,omitempty"`
	Photo           *string         `json:"photo,omitempty"`
	NewPhoto        *graphql.Upload `json:"newPhoto,omitempty"`
	VisualClassKeys []string        `json:"visualClassKeys,omitempty"`
}

type UpdateMenuItemInput struct {
	Name        *string  `json:"name,omitempty"`
	Description *string  `json:"description,omitempty"`
	PriceCents  *int     `json:"priceCents,omitempty"`
	Category    *string  `json:"category,omitempty"`
	IsAvailable *bool    `json:"isAvailable,omitempty"`
	Allergens   []string `json:"allergens,omitempty"`
	SortOrder   *int     `json:"sortOrder,omitempty"`
}

type UpdatePostInput struct {
	ID      string `json:"id"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

type UpdateRestaurantInput struct {
	Name                   *string      `json:"name,omitempty"`
	Phone                  *string      `json:"phone,omitempty"`
	Email                  *string      `json:"email,omitempty"`
	AddressLine1           *string      `json:"addressLine1,omitempty"`
	Suburb                 *string      `json:"suburb,omitempty"`
	State                  *string      `json:"state,omitempty"`
	Postcode               *string      `json:"postcode,omitempty"`
	CuisineType            *string      `json:"cuisineType,omitempty"`
	SeatingType            *SeatingType `json:"seatingType,omitempty"`
	DefaultTurnDurationMin *int         `json:"defaultTurnDurationMin,omitempty"`
	BookingBufferMin       *int         `json:"bookingBufferMin,omitempty"`
	MaxPartySize           *int         `json:"maxPartySize,omitempty"`
	Description            *string      `json:"description,omitempty"`
	ParkingInfo            *string      `json:"parkingInfo,omitempty"`
	IsActive               *bool        `json:"isActive,omitempty"`
}

type UpdateShopInput struct {
	ShopID         string                `json:"shopId"`
	ShopName       string                `json:"shopName"`
	Description    *string               `json:"description,omitempty"`
	BusinessHours  *BusinessHoursInput   `json:"businessHours"`
	PaymentMethods *PaymentMethodsInput  `json:"paymentMethods"`
	Delivery       *DeliveryOptionsInput `json:"delivery"`
	SocialMedia    *SocialMediaInput     `json:"socialMedia"`
	ContactDetails *ContactDetailsInput  `json:"contactDetails"`
	Address        string                `json:"address"`
	Coordinates    *CoordinatesInput     `json:"coordinates"`
	Photo          *string               `json:"photo,omitempty"`
	NewPhoto       *graphql.Upload       `json:"newPhoto,omitempty"`
	Photos         []string              `json:"photos,omitempty"`
	NewPhotos      []*graphql.Upload     `json:"newPhotos,omitempty"`
}

type UpdateTableInput struct {
	TableNumber *string `json:"tableNumber,omitempty"`
	CapacityMin *int    `json:"capacityMin,omitempty"`
	CapacityMax *int    `json:"capacityMax,omitempty"`
	Section     *string `json:"section,omitempty"`
	IsActive    *bool   `json:"isActive,omitempty"`
}

type User struct {
	ID           string               `json:"id"`
	FirstName    string               `json:"firstName"`
	LastName     string               `json:"lastName"`
	Email        string               `json:"email"`
	ProfilePhoto string               `json:"profilePhoto"`
	Shops        *PaginatedOwnerShops `json:"shops"`
}

type Verification struct {
	IsVerified     bool    `json:"isVerified"`
	VerifiedDate   *string `json:"verifiedDate,omitempty"`
	VerificationID *string `json:"verificationId,omitempty"`
}

type WaitlistEntry struct {
	ID            string         `json:"id"`
	RestaurantID  string         `json:"restaurantId"`
	CustomerID    string         `json:"customerId"`
	PartySize     int            `json:"partySize"`
	RequestedTime string         `json:"requestedTime"`
	Status        WaitlistStatus `json:"status"`
	CreatedAt     string         `json:"createdAt"`
}

type BookingSource string

const (
	BookingSourcePhone      BookingSource = "PHONE"
	BookingSourceWeb        BookingSource = "WEB"
	BookingSourceWalkIn     BookingSource = "WALK_IN"
	BookingSourceThirdParty BookingSource = "THIRD_PARTY"
)

var AllBookingSource = []BookingSource{
	BookingSourcePhone,
	BookingSourceWeb,
	BookingSourceWalkIn,
	BookingSourceThirdParty,
}

func (e BookingSource) IsValid() bool {
	switch e {
	case BookingSourcePhone, BookingSourceWeb, BookingSourceWalkIn, BookingSourceThirdParty:
		return true
	}
	return false
}

func (e BookingSource) String() string {
	return string(e)
}

func (e *BookingSource) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BookingSource(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BookingSource", str)
	}
	return nil
}

func (e BookingSource) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *BookingSource) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e BookingSource) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type BookingStatus string

const (
	BookingStatusPending   BookingStatus = "PENDING"
	BookingStatusConfirmed BookingStatus = "CONFIRMED"
	BookingStatusSeated    BookingStatus = "SEATED"
	BookingStatusCompleted BookingStatus = "COMPLETED"
	BookingStatusCancelled BookingStatus = "CANCELLED"
	BookingStatusNoShow    BookingStatus = "NO_SHOW"
)

var AllBookingStatus = []BookingStatus{
	BookingStatusPending,
	BookingStatusConfirmed,
	BookingStatusSeated,
	BookingStatusCompleted,
	BookingStatusCancelled,
	BookingStatusNoShow,
}

func (e BookingStatus) IsValid() bool {
	switch e {
	case BookingStatusPending, BookingStatusConfirmed, BookingStatusSeated, BookingStatusCompleted, BookingStatusCancelled, BookingStatusNoShow:
		return true
	}
	return false
}

func (e BookingStatus) String() string {
	return string(e)
}

func (e *BookingStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = BookingStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid BookingStatus", str)
	}
	return nil
}

func (e BookingStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *BookingStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e BookingStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type CallOutcome string

const (
	CallOutcomeBooked         CallOutcome = "BOOKED"
	CallOutcomeNoAvailability CallOutcome = "NO_AVAILABILITY"
	CallOutcomeTransferred    CallOutcome = "TRANSFERRED"
	CallOutcomeAbandoned      CallOutcome = "ABANDONED"
)

var AllCallOutcome = []CallOutcome{
	CallOutcomeBooked,
	CallOutcomeNoAvailability,
	CallOutcomeTransferred,
	CallOutcomeAbandoned,
}

func (e CallOutcome) IsValid() bool {
	switch e {
	case CallOutcomeBooked, CallOutcomeNoAvailability, CallOutcomeTransferred, CallOutcomeAbandoned:
		return true
	}
	return false
}

func (e CallOutcome) String() string {
	return string(e)
}

func (e *CallOutcome) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CallOutcome(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CallOutcome", str)
	}
	return nil
}

func (e CallOutcome) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CallOutcome) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CallOutcome) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PaymentStatus string

const (
	PaymentStatusNone     PaymentStatus = "NONE"
	PaymentStatusPending  PaymentStatus = "PENDING"
	PaymentStatusPaid     PaymentStatus = "PAID"
	PaymentStatusRefunded PaymentStatus = "REFUNDED"
)

var AllPaymentStatus = []PaymentStatus{
	PaymentStatusNone,
	PaymentStatusPending,
	PaymentStatusPaid,
	PaymentStatusRefunded,
}

func (e PaymentStatus) IsValid() bool {
	switch e {
	case PaymentStatusNone, PaymentStatusPending, PaymentStatusPaid, PaymentStatusRefunded:
		return true
	}
	return false
}

func (e PaymentStatus) String() string {
	return string(e)
}

func (e *PaymentStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PaymentStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PaymentStatus", str)
	}
	return nil
}

func (e PaymentStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PaymentStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PaymentStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RestaurantUserRole string

const (
	RestaurantUserRoleOwner   RestaurantUserRole = "OWNER"
	RestaurantUserRoleManager RestaurantUserRole = "MANAGER"
	RestaurantUserRoleStaff   RestaurantUserRole = "STAFF"
)

var AllRestaurantUserRole = []RestaurantUserRole{
	RestaurantUserRoleOwner,
	RestaurantUserRoleManager,
	RestaurantUserRoleStaff,
}

func (e RestaurantUserRole) IsValid() bool {
	switch e {
	case RestaurantUserRoleOwner, RestaurantUserRoleManager, RestaurantUserRoleStaff:
		return true
	}
	return false
}

func (e RestaurantUserRole) String() string {
	return string(e)
}

func (e *RestaurantUserRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RestaurantUserRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RestaurantUserRole", str)
	}
	return nil
}

func (e RestaurantUserRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RestaurantUserRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RestaurantUserRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SeatingType string

const (
	SeatingTypeStandard     SeatingType = "STANDARD"
	SeatingTypeFixedSitting SeatingType = "FIXED_SITTING"
)

var AllSeatingType = []SeatingType{
	SeatingTypeStandard,
	SeatingTypeFixedSitting,
}

func (e SeatingType) IsValid() bool {
	switch e {
	case SeatingTypeStandard, SeatingTypeFixedSitting:
		return true
	}
	return false
}

func (e SeatingType) String() string {
	return string(e)
}

func (e *SeatingType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SeatingType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SeatingType", str)
	}
	return nil
}

func (e SeatingType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SeatingType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SeatingType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type WaitlistStatus string

const (
	WaitlistStatusWaiting   WaitlistStatus = "WAITING"
	WaitlistStatusNotified  WaitlistStatus = "NOTIFIED"
	WaitlistStatusConverted WaitlistStatus = "CONVERTED"
	WaitlistStatusExpired   WaitlistStatus = "EXPIRED"
)

var AllWaitlistStatus = []WaitlistStatus{
	WaitlistStatusWaiting,
	WaitlistStatusNotified,
	WaitlistStatusConverted,
	WaitlistStatusExpired,
}

func (e WaitlistStatus) IsValid() bool {
	switch e {
	case WaitlistStatusWaiting, WaitlistStatusNotified, WaitlistStatusConverted, WaitlistStatusExpired:
		return true
	}
	return false
}

func (e WaitlistStatus) String() string {
	return string(e)
}

func (e *WaitlistStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = WaitlistStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid WaitlistStatus", str)
	}
	return nil
}

func (e WaitlistStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *WaitlistStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e WaitlistStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
