// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"github.com/99designs/gqlgen/graphql"
)

type AddInventoryItemInput struct {
	ShopID        string          `json:"shopId"`
	ItemName      string          `json:"itemName"`
	Description   *string         `json:"description,omitempty"`
	Barcode       *string         `json:"barcode,omitempty"`
	Category      *string         `json:"category,omitempty"`
	UnitOfMeasure *string         `json:"unitOfMeasure,omitempty"`
	CostPrice     *float64        `json:"costPrice,omitempty"`
	SellingPrice  *float64        `json:"sellingPrice,omitempty"`
	StockQuantity *int            `json:"stockQuantity,omitempty"`
	ReorderLevel  *int            `json:"reorderLevel,omitempty"`
	Photo         *graphql.Upload `json:"photo,omitempty"`
}

type AuthResponse struct {
	User        *User  `json:"user"`
	AccessToken string `json:"accessToken"`
}

type BusinessHours struct {
	OpenTime  string   `json:"openTime"`
	CloseTime string   `json:"closeTime"`
	Days      []string `json:"days"`
}

type BusinessHoursInput struct {
	OpenTime  string   `json:"openTime"`
	CloseTime string   `json:"closeTime"`
	Days      []string `json:"days"`
}

type ContactDetails struct {
	Phone   *string `json:"phone,omitempty"`
	Email   *string `json:"email,omitempty"`
	Address *string `json:"address,omitempty"`
}

type ContactDetailsInput struct {
	Phone   *string `json:"phone,omitempty"`
	Email   *string `json:"email,omitempty"`
	Address *string `json:"address,omitempty"`
}

type Coordinates struct {
	Lat float64 `json:"lat"`
	Lng float64 `json:"lng"`
}

type CoordinatesInput struct {
	Lat float64 `json:"lat"`
	Lng float64 `json:"lng"`
}

type CreatePostInput struct {
	Title   string `json:"title"`
	Content string `json:"content"`
}

type CreateShopInput struct {
	ShopName       string                `json:"shopName"`
	Address        string                `json:"address"`
	Description    *string               `json:"description,omitempty"`
	BusinessHours  *BusinessHoursInput   `json:"businessHours"`
	PaymentMethods *PaymentMethodsInput  `json:"paymentMethods"`
	Delivery       *DeliveryOptionsInput `json:"delivery"`
	SocialMedia    *SocialMediaInput     `json:"socialMedia"`
	ContactDetails *ContactDetailsInput  `json:"contactDetails"`
	Coordinates    *CoordinatesInput     `json:"coordinates"`
	Photo          *graphql.Upload       `json:"photo,omitempty"`
	Photos         []*graphql.Upload     `json:"photos,omitempty"`
}

type DecrementStockInput struct {
	ItemID           string `json:"itemId"`
	QuantityToRemove int    `json:"quantityToRemove"`
}

type DeliveryOptions struct {
	Available bool     `json:"available"`
	Radius    *float64 `json:"radius,omitempty"`
	Fee       *float64 `json:"fee,omitempty"`
	MinOrder  *float64 `json:"minOrder,omitempty"`
}

type DeliveryOptionsInput struct {
	Available bool     `json:"available"`
	Radius    *float64 `json:"radius,omitempty"`
	Fee       *float64 `json:"fee,omitempty"`
	MinOrder  *float64 `json:"minOrder,omitempty"`
}

type GoogleLoginInput struct {
	Code string `json:"code"`
}

type IncrementStockInput struct {
	ItemID        string `json:"itemId"`
	QuantityToAdd int    `json:"quantityToAdd"`
}

type Mutation struct {
}

type OwnerInventoryItem struct {
	ID            string   `json:"id"`
	ShopID        string   `json:"shopId"`
	ItemName      string   `json:"itemName"`
	Description   *string  `json:"description,omitempty"`
	Barcode       *string  `json:"barcode,omitempty"`
	Category      *string  `json:"category,omitempty"`
	UnitOfMeasure *string  `json:"unitOfMeasure,omitempty"`
	Photo         *string  `json:"photo,omitempty"`
	SellingPrice  *float64 `json:"sellingPrice,omitempty"`
	StockQuantity *int     `json:"stockQuantity,omitempty"`
	CostPrice     *float64 `json:"costPrice,omitempty"`
	ReorderLevel  *int     `json:"reorderLevel,omitempty"`
	UpdatedAt     string   `json:"updatedAt"`
}

type OwnerShop struct {
	ID             string           `json:"id"`
	OwnerID        string           `json:"ownerId"`
	Owner          *User            `json:"owner"`
	ShopName       string           `json:"shopName"`
	Coordinates    *Coordinates     `json:"coordinates"`
	Description    *string          `json:"description,omitempty"`
	BusinessHours  *BusinessHours   `json:"businessHours"`
	PaymentMethods *PaymentMethods  `json:"paymentMethods"`
	Delivery       *DeliveryOptions `json:"delivery"`
	SocialMedia    *SocialMedia     `json:"socialMedia"`
	Verification   *Verification    `json:"verification"`
	ContactDetails *ContactDetails  `json:"contactDetails"`
	Status         *ShopStatus      `json:"status"`
	Address        string           `json:"address"`
	Photo          *string          `json:"photo,omitempty"`
	Photos         []string         `json:"photos"`
	CreatedAt      string           `json:"createdAt"`
}

type PaginatedOwnerInventory struct {
	Items       []*OwnerInventoryItem `json:"items"`
	TotalCount  int                   `json:"totalCount"`
	HasNextPage bool                  `json:"hasNextPage"`
}

type PaginatedOwnerShops struct {
	Shops       []*OwnerShop `json:"shops"`
	TotalCount  int          `json:"totalCount"`
	HasNextPage bool         `json:"hasNextPage"`
}

type PaginatedPosts struct {
	Posts       []*Post `json:"posts"`
	TotalCount  int     `json:"totalCount"`
	HasNextPage bool    `json:"hasNextPage"`
}

type PaginatedPublicProducts struct {
	Products    []*PublicProduct `json:"products"`
	TotalCount  int              `json:"totalCount"`
	HasNextPage bool             `json:"hasNextPage"`
}

type PaginatedShops struct {
	Shops       []*Shop `json:"shops"`
	TotalCount  int     `json:"totalCount"`
	HasNextPage bool    `json:"hasNextPage"`
}

type PaymentMethods struct {
	Cash    bool `json:"cash"`
	Gcash   bool `json:"gcash"`
	Paymaya bool `json:"paymaya"`
	Card    bool `json:"card"`
}

type PaymentMethodsInput struct {
	Cash    bool `json:"cash"`
	Gcash   bool `json:"gcash"`
	Paymaya bool `json:"paymaya"`
	Card    bool `json:"card"`
}

type Post struct {
	ID        string `json:"id"`
	Title     string `json:"title"`
	Content   string `json:"content"`
	UserID    string `json:"userId"`
	CreatedAt string `json:"createdAt"`
}

type PublicProduct struct {
	ID            string   `json:"id"`
	ShopID        string   `json:"shopId"`
	ItemName      string   `json:"itemName"`
	Description   *string  `json:"description,omitempty"`
	Category      *string  `json:"category,omitempty"`
	UnitOfMeasure *string  `json:"unitOfMeasure,omitempty"`
	Photo         *string  `json:"photo,omitempty"`
	SellingPrice  *float64 `json:"sellingPrice,omitempty"`
	StockQuantity *int     `json:"stockQuantity,omitempty"`
}

type Query struct {
}

type RefreshResponse struct {
	AccessToken string `json:"accessToken"`
	User        *User  `json:"user"`
}

type Shop struct {
	ID             string           `json:"id"`
	ShopName       string           `json:"shopName"`
	Address        string           `json:"address"`
	Coordinates    *Coordinates     `json:"coordinates"`
	Description    *string          `json:"description,omitempty"`
	BusinessHours  *BusinessHours   `json:"businessHours"`
	PaymentMethods *PaymentMethods  `json:"paymentMethods"`
	Delivery       *DeliveryOptions `json:"delivery"`
	SocialMedia    *SocialMedia     `json:"socialMedia"`
	Verification   *Verification    `json:"verification"`
	ContactDetails *ContactDetails  `json:"contactDetails"`
	Status         *ShopStatus      `json:"status"`
	Photo          *string          `json:"photo,omitempty"`
	Photos         []string         `json:"photos"`
	Reviews        []*ShopReview    `json:"reviews"`
	CreatedAt      string           `json:"createdAt"`
}

type ShopReview struct {
	ID        string   `json:"id"`
	UserID    string   `json:"userId"`
	Rating    int      `json:"rating"`
	Comment   *string  `json:"comment,omitempty"`
	Photos    []string `json:"photos"`
	CreatedAt string   `json:"createdAt"`
}

type ShopStatus struct {
	IsActive bool `json:"isActive"`
}

type SocialMedia struct {
	Facebook  *string `json:"facebook,omitempty"`
	Instagram *string `json:"instagram,omitempty"`
}

type SocialMediaInput struct {
	Facebook  *string `json:"facebook,omitempty"`
	Instagram *string `json:"instagram,omitempty"`
}

type UpdateInventoryItemInput struct {
	ItemID        string          `json:"itemId"`
	ItemName      string          `json:"itemName"`
	Description   *string         `json:"description,omitempty"`
	Barcode       *string         `json:"barcode,omitempty"`
	Category      *string         `json:"category,omitempty"`
	UnitOfMeasure *string         `json:"unitOfMeasure,omitempty"`
	CostPrice     *float64        `json:"costPrice,omitempty"`
	SellingPrice  *float64        `json:"sellingPrice,omitempty"`
	StockQuantity *int            `json:"stockQuantity,omitempty"`
	ReorderLevel  *int            `json:"reorderLevel,omitempty"`
	Photo         *string         `json:"photo,omitempty"`
	NewPhoto      *graphql.Upload `json:"newPhoto,omitempty"`
}

type UpdatePostInput struct {
	ID      string `json:"id"`
	Title   string `json:"title"`
	Content string `json:"content"`
}

type UpdateShopInput struct {
	ShopID         string                `json:"shopId"`
	ShopName       string                `json:"shopName"`
	Description    *string               `json:"description,omitempty"`
	BusinessHours  *BusinessHoursInput   `json:"businessHours"`
	PaymentMethods *PaymentMethodsInput  `json:"paymentMethods"`
	Delivery       *DeliveryOptionsInput `json:"delivery"`
	SocialMedia    *SocialMediaInput     `json:"socialMedia"`
	ContactDetails *ContactDetailsInput  `json:"contactDetails"`
	Address        string                `json:"address"`
	Coordinates    *CoordinatesInput     `json:"coordinates"`
	Photo          *string               `json:"photo,omitempty"`
	NewPhoto       *graphql.Upload       `json:"newPhoto,omitempty"`
	Photos         []string              `json:"photos,omitempty"`
	NewPhotos      []*graphql.Upload     `json:"newPhotos,omitempty"`
}

type User struct {
	ID           string               `json:"id"`
	FirstName    string               `json:"firstName"`
	LastName     string               `json:"lastName"`
	Email        string               `json:"email"`
	ProfilePhoto string               `json:"profilePhoto"`
	Shops        *PaginatedOwnerShops `json:"shops"`
}

type Verification struct {
	IsVerified     bool    `json:"isVerified"`
	VerifiedDate   *string `json:"verifiedDate,omitempty"`
	VerificationID *string `json:"verificationId,omitempty"`
}
