package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"bytes"
	"context"
	"crypto/rand"
	"encoding/json"
	"fmt"
	"go-backend/internal/database"
	"go-backend/internal/graph/model"
	dbmodel "go-backend/internal/model"
	"log"
	"net/http"
	"net/url"
	"os"
	"strings"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// LoginWithGoogle is the resolver for the loginWithGoogle field.
func (r *mutationResolver) LoginWithGoogle(ctx context.Context, input model.GoogleLoginInput) (*model.AuthResponse, error) {
	// 1. Exchange the Authorization Code for tokens from Google
	data := url.Values{}
	data.Set("code", input.Code) // The code sent from your React variables
	data.Set("client_id", os.Getenv("GOOGLE_CLIENT_ID"))
	data.Set("client_secret", os.Getenv("GOOGLE_CLIENT_SECRET"))
	data.Set("redirect_uri", os.Getenv("GOOGLE_REDIRECT_URI")) // "postmessage"
	data.Set("grant_type", "authorization_code")
	data.Set("access_type", "offline")
	data.Set("prompt", "consent")

	tokenURL := "https://oauth2.googleapis.com/token"
	req, err := http.NewRequestWithContext(ctx, "POST", tokenURL, bytes.NewBufferString(data.Encode()))
	if err != nil {
		return nil, fmt.Errorf("failed to build token request: %w", err)
	}
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")

	httpClient := &http.Client{Timeout: 10 * time.Second}
	resp, err := httpClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("google communication failure: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("google rejected code with status: %d", resp.StatusCode)
	}

	var tokenRes dbmodel.GoogleTokenResponse
	if err := json.NewDecoder(resp.Body).Decode(&tokenRes); err != nil {
		return nil, fmt.Errorf("failed parsing google token json: %w", err)
	}

	// 2. Use the AccessToken to fetch the real profile details from Google
	userInfoURL := "https://www.googleapis.com/oauth2/v3/userinfo"
	userReq, err := http.NewRequestWithContext(ctx, "GET", userInfoURL, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to build user info request: %w", err)
	}
	userReq.Header.Set("Authorization", fmt.Sprintf("Bearer %s", tokenRes.AccessToken))

	userResp, err := httpClient.Do(userReq)
	if err != nil {
		return nil, fmt.Errorf("failed fetching user info: %w", err)
	}
	defer userResp.Body.Close()

	var googleUser dbmodel.GoogleUserInfo
	if err := json.NewDecoder(userResp.Body).Decode(&googleUser); err != nil {
		return nil, fmt.Errorf("failed parsing google user profile: %w", err)
	}

	// 3. Drop the HTTP-Only cookie for the refresh token
	if tokenRes.RefreshToken != "" {
		log.Println("➜ Writing 'refresh_token' HttpOnly cookie to browser...")

		// Extract the Gin Context safely
		ginCtx, ok := ctx.Value("ginContext").(*gin.Context)
		if ok {
			isProduction := os.Getenv("GO_ENV") == "production"
			var sameSiteCode http.SameSite
			var isSecure bool
			var cookieDomain string

			if isProduction {
				sameSiteCode = http.SameSiteNoneMode
				cookieDomain = ".hanaptindahan.com"
				isSecure = true
			} else {
				sameSiteCode = http.SameSiteLaxMode
				cookieDomain = ""
				isSecure = false
			}

			// Use the standard net/http writer directly on top of Gin's writer stream
			// to guarantee SameSite configurations pass accurately
			http.SetCookie(ginCtx.Writer, &http.Cookie{
				Name:     "refresh_token",
				Value:    tokenRes.RefreshToken,
				Path:     "/",
				MaxAge:   60 * 60 * 24 * 30, // 30 Days
				HttpOnly: true,
				Secure:   isSecure,
				SameSite: sameSiteCode,
				Domain:   cookieDomain,
			})
			log.Printf("✅ Cookie set successfully via Gin Context Writer (isProduction=%v)", isProduction)
		} else {
			log.Println("⚠️ Failed to write cookie: ginContext not found or invalid type assertion")
		}
	}

	// 4. Map the Google response fields into your PostgreSQL db model
	userRepo := database.NewUserRepo(r.Resolver.DB)
	incomingUser := &dbmodel.User{
		ID:           googleUser.ID,
		FirstName:    googleUser.GivenName,
		LastName:     googleUser.FamilyName,
		Email:        googleUser.Email,
		ProfilePhoto: googleUser.Picture,
	}

	savedUser, err := userRepo.FindOrCreateUser(ctx, incomingUser)
	if err != nil {
		return nil, fmt.Errorf("failed to sync user data in database: %w", err)
	}

	// 5. Cache session token in Redis
	tokenBytes := make([]byte, 32)
	if _, err := rand.Read(tokenBytes); err != nil { // Uses "crypto/rand"
		return nil, fmt.Errorf("failed to generate secure session token: %w", err)
	}
	sessionToken := fmt.Sprintf("%x", tokenBytes) // A random 64-character hex string

	// FIX 2: Group essential user attributes into a portable cache payload
	sessionData := map[string]interface{}{
		"id":    savedUser.ID,
		"email": savedUser.Email,
	}
	sessionPayload, err := json.Marshal(sessionData)
	if err != nil {
		return nil, fmt.Errorf("failed serialization of redis session object: %w", err)
	}

	// FIX 3: Isolate keys using a structured prefix namespace ("auth:")
	redisKey := fmt.Sprintf("auth:%s", sessionToken)
	err = r.Resolver.Redis.Set(ctx, redisKey, sessionPayload, 1*time.Hour).Err()
	if err != nil {
		return nil, fmt.Errorf("failed to cache user session in redis: %w", err)
	}

	// 6. Return response matching your schema contract
	return &model.AuthResponse{
		User: &model.User{
			ID:           savedUser.ID,
			FirstName:    savedUser.FirstName,
			LastName:     savedUser.LastName,
			Email:        savedUser.Email,
			ProfilePhoto: savedUser.ProfilePhoto,
		},
		AccessToken: sessionToken,
	}, nil
}

// RefreshToken is the resolver for the refreshToken field.
// RefreshToken is the resolver for the refreshToken field.
func (r *mutationResolver) RefreshToken(ctx context.Context) (*model.RefreshResponse, error) {
	// 1. Safely extract the Gin Context stream to access incoming browser cookies
	ginCtx, ok := ctx.Value("ginContext").(*gin.Context)
	if !ok {
		return nil, &gqlerror.Error{
			Message:    "internal server error: network stream context missing",
			Extensions: map[string]interface{}{"code": "INTERNAL_SERVER_ERROR"},
		}
	}

	// 2. Read the secure HttpOnly cookie containing Google's long-term refresh token
	cookieToken, err := ginCtx.Cookie("refresh_token")
	if err != nil {
		// If the cookie is missing or expired, the user must log in again completely
		return nil, &gqlerror.Error{
			Message:    "session expired: refresh token cookie missing or invalid",
			Extensions: map[string]interface{}{"code": "UNAUTHENTICATED"},
		}
	}

	// 3. Trade the Google Refresh Token for a brand-new live Access Token from Google
	data := url.Values{}
	data.Set("client_id", os.Getenv("GOOGLE_CLIENT_ID"))
	data.Set("client_secret", os.Getenv("GOOGLE_CLIENT_SECRET"))
	data.Set("refresh_token", cookieToken)
	data.Set("grant_type", "refresh_token")

	tokenURL := "https://oauth2.googleapis.com/token"
	req, err := http.NewRequestWithContext(ctx, "POST", tokenURL, bytes.NewBufferString(data.Encode()))
	if err != nil {
		return nil, fmt.Errorf("failed to build refresh token request: %w", err)
	}
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")

	httpClient := &http.Client{Timeout: 10 * time.Second}
	resp, err := httpClient.Do(req)
	if err != nil {
		return nil, fmt.Errorf("google communication failure: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return nil, &gqlerror.Error{
			Message:    "session revoked: google rejected the refresh token sequence",
			Extensions: map[string]interface{}{"code": "UNAUTHENTICATED"},
		}
	}

	var tokenRes dbmodel.GoogleTokenResponse
	if err := json.NewDecoder(resp.Body).Decode(&tokenRes); err != nil {
		return nil, fmt.Errorf("failed parsing google token JSON response: %w", err)
	}

	// 4. Use Google's fresh access token to fetch the profile details and identify who this is
	userInfoURL := "https://www.googleapis.com/oauth2/v3/userinfo"
	userReq, err := http.NewRequestWithContext(ctx, "GET", userInfoURL, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to build user info request: %w", err)
	}
	userReq.Header.Set("Authorization", fmt.Sprintf("Bearer %s", tokenRes.AccessToken))

	userResp, err := httpClient.Do(userReq)
	if err != nil {
		return nil, fmt.Errorf("failed fetching updated user info payload: %w", err)
	}
	defer userResp.Body.Close()

	var googleUser dbmodel.GoogleUserInfo
	if err := json.NewDecoder(userResp.Body).Decode(&googleUser); err != nil {
		return nil, fmt.Errorf("failed parsing user identity profile: %w", err)
	}

	// 5. Look up the true database record matching this Google Sub identity string
	userRepo := database.NewUserRepo(r.Resolver.DB)
	incomingUser := &dbmodel.User{ID: googleUser.ID, Email: googleUser.Email}
	savedUser, err := userRepo.FindOrCreateUser(ctx, incomingUser)
	if err != nil {
		return nil, fmt.Errorf("failed to sync user verification data properties: %w", err)
	}

	// 6. Generate a brand new, cryptographically secure 64-character local access token
	tokenBytes := make([]byte, 32)
	if _, err := rand.Read(tokenBytes); err != nil {
		return nil, fmt.Errorf("failed to generate secure session token: %w", err)
	}
	newSessionToken := fmt.Sprintf("%x", tokenBytes)

	// 7. Package the user payload back up and save it inside your Redis cache for another hour
	sessionData := map[string]interface{}{
		"id":    savedUser.ID,
		"email": savedUser.Email,
	}
	sessionPayload, err := json.Marshal(sessionData)
	if err != nil {
		return nil, fmt.Errorf("failed serialization of redis session object: %w", err)
	}

	redisKey := fmt.Sprintf("auth:%s", newSessionToken)
	err = r.Resolver.Redis.Set(ctx, redisKey, sessionPayload, 1*time.Hour).Err()
	if err != nil {
		return nil, fmt.Errorf("failed to cache fresh user session in redis: %w", err)
	}

	// 8. Return the fresh token and user metadata object matching your schema contract
	return &model.RefreshResponse{
		AccessToken: newSessionToken,
		User: &model.User{
			ID:           savedUser.ID,
			FirstName:    savedUser.FirstName,
			LastName:     savedUser.LastName,
			Email:        savedUser.Email,
			ProfilePhoto: savedUser.ProfilePhoto,
		},
	}, nil
}

// Logout is the resolver for the logout field.
// Logout is the resolver for the logout field.
func (r *mutationResolver) Logout(ctx context.Context) (bool, error) {
	// 1. Extract the Gin Context stream safely to manipulate browser cookie headers
	ginCtx, ok := ctx.Value("ginContext").(*gin.Context)
	if !ok {
		return false, fmt.Errorf("internal server error: network context stream missing")
	}

	// 2. Extract the active Access Token from the request's Authorization Header
	authHeader := ginCtx.GetHeader("Authorization")
	if authHeader != "" {
		parts := strings.Split(authHeader, " ")
		if len(parts) == 2 && parts[0] == "Bearer" {
			accessToken := parts[1]

			// 🔒 REDIS ERASURE: Explicitly delete this specific token key from cache memory instantly
			redisKey := fmt.Sprintf("auth:%s", accessToken)
			r.Resolver.Redis.Del(ctx, redisKey)
			log.Printf("🗑️ Redis cache key '%s' successfully destroyed.", redisKey)
		}
	}

	// 3. WIPE THE HTTP-ONLY COOKIE: Overwrite the cookie with an immediate expiration date
	isProduction := os.Getenv("GO_ENV") == "production"
	var sameSiteCode http.SameSite
	var cookieDomain string

	if isProduction {
		sameSiteCode = http.SameSiteNoneMode
		cookieDomain = ".hanaptindahan.com"
	} else {
		sameSiteCode = http.SameSiteLaxMode
		cookieDomain = ""
	}

	// Setting MaxAge to -1 flags the browser to delete the cookie file from disk instantly
	http.SetCookie(ginCtx.Writer, &http.Cookie{
		Name:     "refresh_token",
		Value:    "",
		Path:     "/",
		MaxAge:   -1, // 👈 Clears the cookie instantly!
		HttpOnly: true,
		Secure:   isProduction,
		SameSite: sameSiteCode,
		Domain:   cookieDomain,
	})
	log.Println("✅ 'refresh_token' HttpOnly cookie cleared from client browser stream.")

	return true, nil
}
