package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.93

import (
	"context"
	"errors"
	"go-backend/internal/graph/model"
	"go-backend/internal/middleware"
	"log"
	"time"

	"github.com/99designs/gqlgen/graphql"
	pgx "github.com/jackc/pgx/v5"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// CreatePost is the resolver for the createPost field.
func (r *mutationResolver) CreatePost(ctx context.Context, input model.CreatePostInput) (*model.Post, error) {
	// SECURITY GUARD: Enforce valid user identity state from Redis session
	currentUser := ctx.Value("currentUser").(middleware.CachedUser)

	// Insert record and use RETURNING to grab post database configurations
	query := `
		INSERT INTO posts (title, content, user_id, created_at) 
		VALUES ($1, $2, $3, NOW()) 
		RETURNING id, created_at
	`
	var insertedID string
	var createdAt time.Time

	err := r.Resolver.DB.QueryRow(ctx, query, input.Title, input.Content, currentUser.ID).Scan(&insertedID, &createdAt)
	if err != nil {
		graphql.AddError(ctx, &gqlerror.Error{
			Message: "internal server error: failed to create post entry",
			Extensions: map[string]interface{}{
				"code": "INTERNAL_SERVER_ERROR",
			},
		})
		return nil, nil
	}

	return &model.Post{
		ID:        insertedID,
		Title:     input.Title,
		Content:   input.Content,
		UserID:    currentUser.ID,
		CreatedAt: createdAt.Format(time.RFC3339),
	}, nil
}

// UpdatePost is the resolver for the updatePost field.
func (r *mutationResolver) UpdatePost(ctx context.Context, input model.UpdatePostInput) (*model.Post, error) {
	// SECURITY GUARD 1: Is the client authenticated?
	currentUser := ctx.Value("currentUser").(middleware.CachedUser)

	// 1. Fetch the user_id of the post to evaluate resource ownership
	var dbUserID string
	checkQuery := "SELECT user_id FROM posts WHERE id = $1 LIMIT 1"
	err := r.Resolver.DB.QueryRow(ctx, checkQuery, input.ID).Scan(&dbUserID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			graphql.AddError(ctx, &gqlerror.Error{
				Message: "not found: target post resource does not exist",
				Extensions: map[string]interface{}{
					"code": "NOT_FOUND",
				},
			})
			return nil, nil
		}
		graphql.AddError(ctx, &gqlerror.Error{
			Message: "internal server error: resource lookup failure",
			Extensions: map[string]interface{}{
				"code": "INTERNAL_SERVER_ERROR",
			},
		})
		return nil, nil
	}

	// SECURITY GUARD 2: Does the logged-in user match the original creator?
	if dbUserID != currentUser.ID {
		log.Printf("⚠️ SECURITY ALERT: User %s tried to mutate post %s belonging to user %s", currentUser.ID, input.ID, dbUserID)
		graphql.AddError(ctx, &gqlerror.Error{
			Message: "forbidden: you do not have permission to edit this post",
			Extensions: map[string]interface{}{
				"code": "FORBIDDEN",
			},
		})
		return nil, nil
	}

	// 2. Complete updates safely inside PostgreSQL
	updateQuery := `
		UPDATE posts 
		SET title = $1, content = $2 
		WHERE id = $3 
		RETURNING id, title, content, user_id, created_at
	`
	var id, title, content, userID string
	var createdAt time.Time

	err = r.Resolver.DB.QueryRow(ctx, updateQuery, input.Title, input.Content, input.ID).Scan(&id, &title, &content, &userID, &createdAt)
	if err != nil {
		graphql.AddError(ctx, &gqlerror.Error{
			Message: "internal server error: failed saving post updates",
			Extensions: map[string]interface{}{
				"code": "INTERNAL_SERVER_ERROR",
			},
		})
		return nil, nil
	}

	return &model.Post{
		ID:        id,
		Title:     title,
		Content:   content,
		UserID:    userID,
		CreatedAt: createdAt.Format(time.RFC3339),
	}, nil
}

// DeletePost is the resolver for the deletePost field.
func (r *mutationResolver) DeletePost(ctx context.Context, id string) (bool, error) {
	// SECURITY GUARD 1: Is user logged in?
	currentUser := ctx.Value("currentUser").(middleware.CachedUser)

	// 1. Fetch post owner to verify credentials
	var dbUserID string
	checkQuery := "SELECT user_id FROM posts WHERE id = $1 LIMIT 1"
	err := r.Resolver.DB.QueryRow(ctx, checkQuery, id).Scan(&dbUserID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			graphql.AddError(ctx, &gqlerror.Error{
				Message: "not found: target resource does not exist",
				Extensions: map[string]interface{}{
					"code": "NOT_FOUND",
				},
			})
			return false, nil
		}
		graphql.AddError(ctx, &gqlerror.Error{
			Message: "internal server error: lookup failure",
			Extensions: map[string]interface{}{
				"code": "INTERNAL_SERVER_ERROR",
			},
		})
		return false, nil
	}

	// SECURITY GUARD 2: Check resource ownership properties
	if dbUserID != currentUser.ID {
		log.Printf("⚠️ SECURITY ALERT: Deletion bypass attempt blocked on User ID %s", currentUser.ID)
		graphql.AddError(ctx, &gqlerror.Error{
			Message: "forbidden: you can only delete posts that you created",
			Extensions: map[string]interface{}{
				"code": "FORBIDDEN",
			},
		})
		return false, nil
	}

	// 2. Wipe entry out of PostgreSQL database cleanly
	deleteQuery := "DELETE FROM posts WHERE id = $1"
	_, err = r.Resolver.DB.Exec(ctx, deleteQuery, id)
	if err != nil {
		graphql.AddError(ctx, &gqlerror.Error{
			Message: "internal server error: database erasure failure",
			Extensions: map[string]interface{}{
				"code": "INTERNAL_SERVER_ERROR",
			},
		})
		return false, nil
	}

	return true, nil
}

// GetPosts is the resolver for the getPosts field.
func (r *queryResolver) GetPosts(ctx context.Context, limit int, offset int) (*model.PaginatedPosts, error) {
	// 1. Get total record count for metadata pagination calculation
	var totalCount int64
	countQuery := "SELECT COUNT(*) FROM posts"
	err := r.Resolver.DB.QueryRow(ctx, countQuery).Scan(&totalCount)
	if err != nil {
		graphql.AddError(ctx, &gqlerror.Error{
			Message: "internal server error: analytical tracking aggregation failure",
			Extensions: map[string]interface{}{
				"code": "INTERNAL_SERVER_ERROR",
			},
		})
		return nil, nil
	}

	// 2. Fetch the paginated subset from PostgreSQL
	selectQuery := `
		SELECT id, title, content, user_id, created_at 
		FROM posts 
		ORDER BY created_at DESC 
		LIMIT $1 OFFSET $2
	`
	rows, err := r.Resolver.DB.Query(ctx, selectQuery, limit, offset)
	if err != nil {
		graphql.AddError(ctx, &gqlerror.Error{
			Message: "internal server error: collection retrieval failure",
			Extensions: map[string]interface{}{
				"code": "INTERNAL_SERVER_ERROR",
			},
		})
		return nil, nil
	}
	defer rows.Close()

	var graphqlPosts []*model.Post
	for rows.Next() {
		var id, title, content, userID string
		var createdAt time.Time

		err := rows.Scan(&id, &title, &content, &userID, &createdAt)
		if err != nil {
			graphql.AddError(ctx, &gqlerror.Error{
				Message: "internal server error: data decoding anomaly",
				Extensions: map[string]interface{}{
					"code": "INTERNAL_SERVER_ERROR",
				},
			})
			return nil, nil
		}

		graphqlPosts = append(graphqlPosts, &model.Post{
			ID:        id,
			Title:     title,
			Content:   content,
			UserID:    userID,
			CreatedAt: createdAt.Format(time.RFC3339),
		})
	}

	if err := rows.Err(); err != nil {
		graphql.AddError(ctx, &gqlerror.Error{
			Message: "internal server error: active data stream break",
			Extensions: map[string]interface{}{
				"code": "INTERNAL_SERVER_ERROR",
			},
		})
		return nil, nil
	}

	// 3. Compute layout boundary checks
	hasNextPage := int64(offset+limit) < totalCount

	return &model.PaginatedPosts{
		Posts:       graphqlPosts,
		TotalCount:  int(totalCount),
		HasNextPage: hasNextPage,
	}, nil
}

// GetPostByID is the resolver for the getPostById field.
func (r *queryResolver) GetPostByID(ctx context.Context, id string) (*model.Post, error) {
	query := "SELECT id, title, content, user_id, created_at FROM posts WHERE id = $1 LIMIT 1"

	var postID, title, content, userID string
	var createdAt time.Time

	err := r.Resolver.DB.QueryRow(ctx, query, id).Scan(&postID, &title, &content, &userID, &createdAt)
	if err != nil {
		// Specific catch for standard pgx missing row exception
		if errors.Is(err, pgx.ErrNoRows) {
			graphql.AddError(ctx, &gqlerror.Error{
				Message: "not found: requested post resource does not exist",
				Extensions: map[string]interface{}{
					"code": "NOT_FOUND",
				},
			})
			return nil, nil
		}

		graphql.AddError(ctx, &gqlerror.Error{
			Message: "internal server error: target query extraction broken",
			Extensions: map[string]interface{}{
				"code": "INTERNAL_SERVER_ERROR",
			},
		})
		return nil, nil
	}

	return &model.Post{
		ID:        postID,
		Title:     title,
		Content:   content,
		UserID:    userID,
		CreatedAt: createdAt.Format(time.RFC3339),
	}, nil
}
