package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"errors"
	"go-backend/internal/graph/model"
	"go-backend/internal/middleware"
	"go-backend/internal/utils"
	"log"
	"time"

	"github.com/99designs/gqlgen/graphql"
	pgx "github.com/jackc/pgx/v5"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// RegisterRestaurantOwner creates the account only. Does not create a
// restaurant or grant any role — call createRestaurant next, which grants
// OWNER automatically.
// RegisterRestaurantOwner creates the account only. Does not create a
// restaurant or grant any role — call createRestaurant next, which grants
// OWNER automatically.
func (r *mutationResolver) RegisterRestaurantOwner(ctx context.Context, input model.RestaurantRegisterInput) (*model.RestaurantAuthResponse, error) {
	passwordHash, err := utils.HashPassword(input.Password)
	if err != nil {
		log.Printf("🔴 FAILED TO HASH PASSWORD IN REGISTERRESTAURANTOWNER: %v", err)
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "internal server error",
			Extensions: map[string]any{"code": "INTERNAL_SERVER_ERROR"},
		})
		return nil, nil
	}

	var owner model.RestaurantOwner
	var createdAt, updatedAt time.Time
	err = r.Resolver.DB.QueryRow(ctx, `
		INSERT INTO restaurant_owners (first_name, last_name, email, password_hash)
		VALUES ($1, $2, $3, $4)
		RETURNING id, first_name, last_name, email, created_at, updated_at
	`, input.FirstName, input.LastName, input.Email, passwordHash).
		Scan(&owner.ID, &owner.FirstName, &owner.LastName, &owner.Email, &createdAt, &updatedAt)

	if err != nil {
		if utils.IsUniqueViolation(err) {
			graphql.AddError(ctx, &gqlerror.Error{
				Message:    "an account with this email already exists",
				Extensions: map[string]any{"code": "EMAIL_ALREADY_EXISTS"},
			})
			return nil, nil
		}
		log.Printf("🔴 DATABASE TRANSACTION FAILED IN REGISTERRESTAURANTOWNER: %v", err)
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "internal server error: failed to create account",
			Extensions: map[string]any{"code": "INTERNAL_SERVER_ERROR"},
		})
		return nil, nil
	}

	owner.CreatedAt = createdAt.Format(time.RFC3339)
	owner.UpdatedAt = updatedAt.Format(time.RFC3339)
	owner.Restaurants = []*model.RestaurantStaffRole{} // brand new account, no restaurants yet

	accessToken, err := utils.CreateRestaurantSessionAndCookie(ctx, r.Resolver.Redis, owner.ID, owner.Email)
	if err != nil {
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "internal server error: failed to start session",
			Extensions: map[string]any{"code": "INTERNAL_SERVER_ERROR"},
		})
		return nil, nil
	}

	return &model.RestaurantAuthResponse{Owner: &owner, AccessToken: accessToken}, nil
}

// LoginRestaurantOwner verifies credentials and starts a session.
// LoginRestaurantOwner verifies credentials and starts a session.
func (r *mutationResolver) LoginRestaurantOwner(ctx context.Context, input model.RestaurantLoginInput) (*model.RestaurantAuthResponse, error) {
	var owner model.RestaurantOwner
	var passwordHash string
	var createdAt, updatedAt time.Time
	err := r.Resolver.DB.QueryRow(ctx, `
		SELECT id, first_name, last_name, email, password_hash, created_at, updated_at
		FROM restaurant_owners WHERE email = $1
	`, input.Email).Scan(&owner.ID, &owner.FirstName, &owner.LastName, &owner.Email, &passwordHash, &createdAt, &updatedAt)

	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			graphql.AddError(ctx, &gqlerror.Error{
				Message:    "invalid email or password",
				Extensions: map[string]any{"code": "INVALID_CREDENTIALS"},
			})
			return nil, nil
		}
		log.Printf("🔴 DATABASE QUERY FAILED IN LOGINRESTAURANTOWNER: %v", err)
		return nil, err
	}

	if !utils.CheckPassword(input.Password, passwordHash) {
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "invalid email or password",
			Extensions: map[string]any{"code": "INVALID_CREDENTIALS"},
		})
		return nil, nil
	}

	owner.CreatedAt = createdAt.Format(time.RFC3339)
	owner.UpdatedAt = updatedAt.Format(time.RFC3339)

	restaurants, err := utils.LoadOwnerRestaurantRoles(ctx, r.Resolver.DB, owner.ID)
	if err != nil {
		return nil, err
	}
	owner.Restaurants = restaurants

	accessToken, err := utils.CreateRestaurantSessionAndCookie(ctx, r.Resolver.Redis, owner.ID, owner.Email)
	if err != nil {
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "internal server error: failed to start session",
			Extensions: map[string]any{"code": "INTERNAL_SERVER_ERROR"},
		})
		return nil, nil
	}

	return &model.RestaurantAuthResponse{Owner: &owner, AccessToken: accessToken}, nil
}

// RefreshRestaurantToken swaps the HttpOnly cookie for a fresh access token.
// RefreshRestaurantToken swaps the HttpOnly cookie for a fresh access token.
func (r *mutationResolver) RefreshRestaurantToken(ctx context.Context) (*model.RestaurantRefreshResponse, error) {
	gc := utils.GetGinContext(ctx)
	if gc == nil {
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "internal server error: missing request context",
			Extensions: map[string]any{"code": "INTERNAL_SERVER_ERROR"},
		})
		return nil, nil
	}

	refreshToken, err := gc.Cookie(utils.RestaurantRefreshCookieName)
	if err != nil || refreshToken == "" {
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "unauthorized: no refresh token",
			Extensions: map[string]any{"code": "UNAUTHORIZED"},
		})
		return nil, nil
	}

	cached, err := utils.GetRestaurantSession(ctx, r.Resolver.Redis, refreshToken)
	if err != nil {
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "unauthorized: invalid or expired refresh token",
			Extensions: map[string]any{"code": "UNAUTHORIZED"},
		})
		return nil, nil
	}

	var owner model.RestaurantOwner
	var createdAt, updatedAt time.Time
	if err := r.Resolver.DB.QueryRow(ctx, `
		SELECT id, first_name, last_name, email, created_at, updated_at FROM restaurant_owners WHERE id = $1
	`, cached.ID).Scan(&owner.ID, &owner.FirstName, &owner.LastName, &owner.Email, &createdAt, &updatedAt); err != nil {
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "unauthorized: account no longer exists",
			Extensions: map[string]any{"code": "UNAUTHORIZED"},
		})
		return nil, nil
	}

	owner.CreatedAt = createdAt.Format(time.RFC3339)
	owner.UpdatedAt = updatedAt.Format(time.RFC3339)

	restaurants, err := utils.LoadOwnerRestaurantRoles(ctx, r.Resolver.DB, owner.ID)
	if err != nil {
		return nil, err
	}
	owner.Restaurants = restaurants

	accessToken, err := utils.CreateRestaurantSessionAndCookie(ctx, r.Resolver.Redis, owner.ID, owner.Email)
	if err != nil {
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "internal server error: failed to refresh session",
			Extensions: map[string]any{"code": "INTERNAL_SERVER_ERROR"},
		})
		return nil, nil
	}

	return &model.RestaurantRefreshResponse{AccessToken: accessToken, Owner: &owner}, nil
}

// LogoutRestaurantOwner wipes the Redis session and clears the cookie.
func (r *mutationResolver) LogoutRestaurantOwner(ctx context.Context) (bool, error) {
	gc := utils.GetGinContext(ctx)
	if gc != nil {
		accessToken := utils.ExtractBearerToken(gc)
		if accessToken != "" {
			if err := utils.DeleteRestaurantSession(ctx, r.Resolver.Redis, accessToken); err != nil {
				log.Printf("⚠️ Failed to delete restaurant session on logout: %v", err)
			}
		}
		gc.SetCookie(utils.RestaurantRefreshCookieName, "", -1, "/", "", true, true)
	}

	return true, nil
}

// InviteRestaurantStaff is the resolver for the inviteRestaurantStaff field.
func (r *mutationResolver) InviteRestaurantStaff(ctx context.Context, input model.InviteRestaurantStaffInput) (*model.RestaurantStaffRole, error) {
	if _, err := utils.RequireRestaurantStaff(ctx, r.Resolver.DB, input.RestaurantID, false); err != nil {
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    err.Error(),
			Extensions: map[string]any{"code": "FORBIDDEN"},
		})
		return nil, nil
	}

	if input.Role == model.RestaurantUserRoleOwner {
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "cannot grant owner role via invite",
			Extensions: map[string]any{"code": "BAD_USER_INPUT"},
		})
		return nil, nil
	}

	var targetOwnerID string
	if err := r.Resolver.DB.QueryRow(ctx, `SELECT id FROM restaurant_owners WHERE email = $1`, input.Email).Scan(&targetOwnerID); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			graphql.AddError(ctx, &gqlerror.Error{
				Message:    "no account found with that email — they need to register first",
				Extensions: map[string]any{"code": "NOT_FOUND"},
			})
			return nil, nil
		}
		return nil, err
	}

	if _, err := r.Resolver.DB.Exec(ctx, `
		INSERT INTO restaurant_staff (restaurant_id, owner_id, role)
		VALUES ($1, $2, $3)
		ON CONFLICT (restaurant_id, owner_id) DO UPDATE SET role = $3
	`, input.RestaurantID, targetOwnerID, input.Role); err != nil {
		log.Printf("🔴 DATABASE TRANSACTION FAILED IN INVITERESTAURANTSTAFF: %v", err)
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "internal server error: failed to invite staff",
			Extensions: map[string]any{"code": "INTERNAL_SERVER_ERROR"},
		})
		return nil, nil
	}

	restaurant, err := utils.GetRestaurantByID(ctx, r.Resolver.DB, input.RestaurantID)
	if err != nil || restaurant == nil {
		return nil, err
	}

	return &model.RestaurantStaffRole{Restaurant: restaurant, Role: input.Role}, nil
}

// RevokeRestaurantStaff is the resolver for the revokeRestaurantStaff field.
func (r *mutationResolver) RevokeRestaurantStaff(ctx context.Context, restaurantID string, ownerID string) (bool, error) {
	if _, err := utils.RequireRestaurantStaff(ctx, r.Resolver.DB, restaurantID, false); err != nil {
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    err.Error(),
			Extensions: map[string]any{"code": "FORBIDDEN"},
		})
		return false, nil
	}

	if _, err := r.Resolver.DB.Exec(ctx, `
		DELETE FROM restaurant_staff WHERE restaurant_id = $1 AND owner_id = $2
	`, restaurantID, ownerID); err != nil {
		log.Printf("🔴 DATABASE DELETE FAILED IN REVOKERESTAURANTSTAFF: %v", err)
		return false, err
	}

	return true, nil
}

// CurrentRestaurantOwner is the resolver for the currentRestaurantOwner field.
// CurrentRestaurantOwner is the resolver for the currentRestaurantOwner field.
func (r *queryResolver) CurrentRestaurantOwner(ctx context.Context) (*model.RestaurantOwner, error) {
	currentUser, ok := ctx.Value("currentRestaurantUser").(middleware.CachedRestaurantUser)
	if !ok {
		return nil, nil
	}

	var owner model.RestaurantOwner
	var createdAt, updatedAt time.Time
	err := r.Resolver.DB.QueryRow(ctx, `
		SELECT id, first_name, last_name, email, created_at, updated_at
		FROM restaurant_owners WHERE id = $1
	`, currentUser.ID).Scan(&owner.ID, &owner.FirstName, &owner.LastName, &owner.Email, &createdAt, &updatedAt)

	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, nil
		}
		return nil, err
	}

	owner.CreatedAt = createdAt.Format(time.RFC3339)
	owner.UpdatedAt = updatedAt.Format(time.RFC3339)

	restaurants, err := utils.LoadOwnerRestaurantRoles(ctx, r.Resolver.DB, owner.ID)
	if err != nil {
		return nil, err
	}
	owner.Restaurants = restaurants

	return &owner, nil
}
