package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"errors"
	"fmt"
	"go-backend/internal/graph/model"
	"go-backend/internal/middleware"
	"go-backend/internal/utils"
	"log"
	"time"

	"github.com/99designs/gqlgen/graphql"
	pgx "github.com/jackc/pgx/v5"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// CreateRestaurant is the resolver for the createRestaurant field.
// CreateRestaurant is the resolver for the createRestaurant field.
func (r *mutationResolver) CreateRestaurant(ctx context.Context, input model.CreateRestaurantInput) (*model.Restaurant, error) {
	currentUser, ok := ctx.Value("currentRestaurantUser").(middleware.CachedRestaurantUser)
	if !ok {
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "unauthorized: no restaurant session found",
			Extensions: map[string]any{"code": "UNAUTHORIZED"},
		})
		return nil, nil
	}

	tx, err := r.Resolver.DB.Begin(ctx)
	if err != nil {
		log.Printf("🔴 FAILED TO ACQUIRE TRANSACTION IN CREATERESTAURANT: %v", err)
		return nil, fmt.Errorf("internal server error")
	}
	defer tx.Rollback(ctx)

	timezone := "Australia/Sydney"
	if input.Timezone != nil {
		timezone = *input.Timezone
	}
	seatingType := model.SeatingTypeStandard
	if input.SeatingType != nil {
		seatingType = *input.SeatingType
	}
	turnDuration := 90
	if input.DefaultTurnDurationMin != nil {
		turnDuration = *input.DefaultTurnDurationMin
	}
	bufferMin := 15
	if input.BookingBufferMin != nil {
		bufferMin = *input.BookingBufferMin
	}
	maxParty := 12
	if input.MaxPartySize != nil {
		maxParty = *input.MaxPartySize
	}

	var res model.Restaurant
	var createdAt, updatedAt time.Time
	err = tx.QueryRow(ctx, `
		INSERT INTO restaurants (
			name, phone, email, address_line1, suburb, state, postcode, timezone,
			cuisine_type, seating_type, default_turn_duration_min, booking_buffer_min, max_party_size
		)
		VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
		RETURNING id, created_at, updated_at
	`, input.Name, input.Phone, input.Email, input.AddressLine1, input.Suburb, input.State, input.Postcode,
		timezone, input.CuisineType, seatingType, turnDuration, bufferMin, maxParty,
	).Scan(&res.ID, &createdAt, &updatedAt)

	if err != nil {
		log.Printf("🔴 DATABASE TRANSACTION FAILED IN CREATERESTAURANT: %v", err)
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "internal server error: failed to create restaurant",
			Extensions: map[string]any{"code": "INTERNAL_SERVER_ERROR"},
		})
		return nil, nil
	}

	// Grant the creator OWNER role on their new restaurant.
	// NOTE: role must match the migration's CHECK constraint exactly —
	// chk_restaurant_staff_role only allows 'OWNER', 'MANAGER', 'STAFF'
	// (uppercase). Lowercase 'owner' fails the constraint on every call.
	if _, err = tx.Exec(ctx, `
		INSERT INTO restaurant_staff (restaurant_id, owner_id, role)
		VALUES ($1, $2, 'OWNER')
	`, res.ID, currentUser.ID); err != nil {
		log.Printf("🔴 FAILED TO GRANT OWNER ROLE IN CREATERESTAURANT: %v", err)
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "internal server error: failed to link owner to restaurant",
			Extensions: map[string]any{"code": "INTERNAL_SERVER_ERROR"},
		})
		return nil, nil
	}

	if err = tx.Commit(ctx); err != nil {
		log.Printf("🔴 TRANSACTION COMMIT FAILED IN CREATERESTAURANT: %v", err)
		return nil, fmt.Errorf("internal server error")
	}

	res.Name = input.Name
	res.Phone = input.Phone
	res.Email = input.Email
	res.AddressLine1 = input.AddressLine1
	res.Suburb = input.Suburb
	res.State = input.State
	res.Postcode = input.Postcode
	res.Timezone = timezone
	res.CuisineType = input.CuisineType
	res.SeatingType = seatingType
	res.DefaultTurnDurationMin = turnDuration
	res.BookingBufferMin = bufferMin
	res.MaxPartySize = maxParty
	res.IsActive = true
	res.CreatedAt = createdAt.Format(time.RFC3339)
	res.UpdatedAt = updatedAt.Format(time.RFC3339)
	return &res, nil
}

// UpdateRestaurant is the resolver for the updateRestaurant field.
func (r *mutationResolver) UpdateRestaurant(ctx context.Context, id string, input model.UpdateRestaurantInput) (*model.Restaurant, error) {
	if _, err := utils.RequireRestaurantStaff(ctx, r.Resolver.DB, id, false); err != nil {
		return nil, nil
	}

	// Partial update pattern: COALESCE against existing row so callers only
	// need to send the fields that changed.
	query := `
		UPDATE restaurants SET
			name = COALESCE($1, name),
			phone = COALESCE($2, phone),
			email = COALESCE($3, email),
			address_line1 = COALESCE($4, address_line1),
			suburb = COALESCE($5, suburb),
			state = COALESCE($6, state),
			postcode = COALESCE($7, postcode),
			cuisine_type = COALESCE($8, cuisine_type),
			seating_type = COALESCE($9, seating_type),
			default_turn_duration_min = COALESCE($10, default_turn_duration_min),
			booking_buffer_min = COALESCE($11, booking_buffer_min),
			max_party_size = COALESCE($12, max_party_size),
			is_active = COALESCE($13, is_active),
			updated_at = NOW()
		WHERE id = $14
		RETURNING id, name, phone, email, address_line1, suburb, state, postcode, timezone,
			cuisine_type, seating_type, default_turn_duration_min, booking_buffer_min,
			max_party_size, is_active, created_at, updated_at
	`

	var res model.Restaurant
	var createdAt, updatedAt time.Time

	err := r.Resolver.DB.QueryRow(ctx, query,
		input.Name, input.Phone, input.Email, input.AddressLine1, input.Suburb, input.State, input.Postcode,
		input.CuisineType, input.SeatingType, input.DefaultTurnDurationMin, input.BookingBufferMin,
		input.MaxPartySize, input.IsActive, id,
	).Scan(
		&res.ID, &res.Name, &res.Phone, &res.Email, &res.AddressLine1, &res.Suburb, &res.State, &res.Postcode,
		&res.Timezone, &res.CuisineType, &res.SeatingType, &res.DefaultTurnDurationMin, &res.BookingBufferMin,
		&res.MaxPartySize, &res.IsActive, &createdAt, &updatedAt,
	)

	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			graphql.AddError(ctx, &gqlerror.Error{
				Message:    "not found: restaurant does not exist",
				Extensions: map[string]any{"code": "NOT_FOUND"},
			})
			return nil, nil
		}
		log.Printf("🔴 DATABASE UPDATE FAILED IN UPDATERESTAURANT: %v", err)
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "internal server error: failed saving restaurant updates",
			Extensions: map[string]any{"code": "INTERNAL_SERVER_ERROR"},
		})
		return nil, nil
	}

	res.CreatedAt = createdAt.Format(time.RFC3339)
	res.UpdatedAt = updatedAt.Format(time.RFC3339)
	return &res, nil
}

// CreateTable is the resolver for the createTable field.
func (r *mutationResolver) CreateTable(ctx context.Context, input model.CreateTableInput) (*model.RestaurantTable, error) {
	if _, err := utils.RequireRestaurantStaff(ctx, r.Resolver.DB, input.RestaurantID, true); err != nil {
		return nil, nil
	}

	query := `
		INSERT INTO restaurant_tables (restaurant_id, table_number, capacity_min, capacity_max, section)
		VALUES ($1, $2, $3, $4, $5)
		RETURNING id
	`

	var id string
	err := r.Resolver.DB.QueryRow(ctx, query,
		input.RestaurantID, input.TableNumber, input.CapacityMin, input.CapacityMax, input.Section,
	).Scan(&id)

	if err != nil {
		if utils.IsUniqueViolation(err) {
			graphql.AddError(ctx, &gqlerror.Error{
				Message:    fmt.Sprintf("table number %q already exists for this restaurant", input.TableNumber),
				Extensions: map[string]any{"code": "TABLE_NUMBER_ALREADY_EXISTS"},
			})
			return nil, nil
		}
		log.Printf("🔴 DATABASE TRANSACTION FAILED IN CREATETABLE: %v", err)
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "internal server error: failed to create table",
			Extensions: map[string]any{"code": "INTERNAL_SERVER_ERROR"},
		})
		return nil, nil
	}

	return &model.RestaurantTable{
		ID:           id,
		RestaurantID: input.RestaurantID,
		TableNumber:  input.TableNumber,
		CapacityMin:  input.CapacityMin,
		CapacityMax:  input.CapacityMax,
		Section:      input.Section,
		IsActive:     true,
	}, nil
}

// UpdateTable is the resolver for the updateTable field.
func (r *mutationResolver) UpdateTable(ctx context.Context, id string, input model.UpdateTableInput) (*model.RestaurantTable, error) {
	// Look up the table's restaurant first so we can run the ownership guard.
	var restaurantID string
	if err := r.Resolver.DB.QueryRow(ctx, `SELECT restaurant_id FROM restaurant_tables WHERE id = $1`, id).Scan(&restaurantID); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			graphql.AddError(ctx, &gqlerror.Error{
				Message:    "not found: table does not exist",
				Extensions: map[string]any{"code": "NOT_FOUND"},
			})
			return nil, nil
		}
		return nil, err
	}

	if _, err := utils.RequireRestaurantStaff(ctx, r.Resolver.DB, restaurantID, true); err != nil {
		return nil, nil
	}

	query := `
		UPDATE restaurant_tables SET
			table_number = COALESCE($1, table_number),
			capacity_min = COALESCE($2, capacity_min),
			capacity_max = COALESCE($3, capacity_max),
			section = COALESCE($4, section),
			is_active = COALESCE($5, is_active)
		WHERE id = $6
		RETURNING id, restaurant_id, table_number, capacity_min, capacity_max, section, is_active
	`

	var t model.RestaurantTable
	err := r.Resolver.DB.QueryRow(ctx, query,
		input.TableNumber, input.CapacityMin, input.CapacityMax, input.Section, input.IsActive, id,
	).Scan(&t.ID, &t.RestaurantID, &t.TableNumber, &t.CapacityMin, &t.CapacityMax, &t.Section, &t.IsActive)

	if err != nil {
		log.Printf("🔴 DATABASE UPDATE FAILED IN UPDATETABLE: %v", err)
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "internal server error: failed saving table updates",
			Extensions: map[string]any{"code": "INTERNAL_SERVER_ERROR"},
		})
		return nil, nil
	}

	return &t, nil
}

// DeleteTable is the resolver for the deleteTable field.
func (r *mutationResolver) DeleteTable(ctx context.Context, id string) (bool, error) {
	var restaurantID string
	if err := r.Resolver.DB.QueryRow(ctx, `SELECT restaurant_id FROM restaurant_tables WHERE id = $1`, id).Scan(&restaurantID); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			graphql.AddError(ctx, &gqlerror.Error{
				Message:    "not found: table does not exist",
				Extensions: map[string]any{"code": "NOT_FOUND"},
			})
			return false, nil
		}
		return false, err
	}

	if _, err := utils.RequireRestaurantStaff(ctx, r.Resolver.DB, restaurantID, false); err != nil {
		return false, nil
	}

	// Soft-delete via is_active rather than a hard DELETE, since historical
	// bookings still reference this table_id and we don't want to orphan them.
	_, err := r.Resolver.DB.Exec(ctx, `UPDATE restaurant_tables SET is_active = false WHERE id = $1`, id)
	if err != nil {
		log.Printf("🔴 DATABASE DELETE FAILED IN DELETETABLE: %v", err)
		return false, err
	}

	return true, nil
}

// SetOperatingHours is the resolver for the setOperatingHours field.
func (r *mutationResolver) SetOperatingHours(ctx context.Context, restaurantID string, hours []*model.SetOperatingHoursInput) ([]*model.OperatingHours, error) {
	if _, err := utils.RequireRestaurantStaff(ctx, r.Resolver.DB, restaurantID, false); err != nil {
		return nil, nil
	}

	tx, err := r.Resolver.DB.Begin(ctx)
	if err != nil {
		log.Printf("🔴 FAILED TO ACQUIRE TRANSACTION IN SETOPERATINGHOURS: %v", err)
		return nil, fmt.Errorf("internal server error")
	}
	defer tx.Rollback(ctx)

	var results []*model.OperatingHours
	for _, h := range hours {
		isClosed := false
		if h.IsClosed != nil {
			isClosed = *h.IsClosed
		}

		var oh model.OperatingHours
		err := tx.QueryRow(ctx, `
			INSERT INTO operating_hours (restaurant_id, day_of_week, open_time, close_time, is_closed)
			VALUES ($1, $2, $3, $4, $5)
			ON CONFLICT (restaurant_id, day_of_week)
			DO UPDATE SET open_time = $3, close_time = $4, is_closed = $5
			RETURNING id, day_of_week, open_time, close_time, is_closed
		`, restaurantID, h.DayOfWeek, h.OpenTime, h.CloseTime, isClosed).
			Scan(&oh.ID, &oh.DayOfWeek, &oh.OpenTime, &oh.CloseTime, &oh.IsClosed)

		if err != nil {
			log.Printf("🔴 FAILED TO UPSERT OPERATING HOURS FOR DAY %d: %v", h.DayOfWeek, err)
			return nil, fmt.Errorf("internal server error: failed saving operating hours")
		}
		results = append(results, &oh)
	}

	if err := tx.Commit(ctx); err != nil {
		log.Printf("🔴 TRANSACTION COMMIT FAILED IN SETOPERATINGHOURS: %v", err)
		return nil, fmt.Errorf("internal server error")
	}

	return results, nil
}

// CreateClosure is the resolver for the createClosure field.
func (r *mutationResolver) CreateClosure(ctx context.Context, input model.CreateClosureInput) (*model.Closure, error) {
	if _, err := utils.RequireRestaurantStaff(ctx, r.Resolver.DB, input.RestaurantID, true); err != nil {
		return nil, nil
	}

	var c model.Closure
	err := r.Resolver.DB.QueryRow(ctx, `
		INSERT INTO closures (restaurant_id, closure_date, reason)
		VALUES ($1, $2, $3)
		RETURNING id, closure_date, reason
	`, input.RestaurantID, input.ClosureDate, input.Reason).Scan(&c.ID, &c.ClosureDate, &c.Reason)

	if err != nil {
		if utils.IsUniqueViolation(err) {
			graphql.AddError(ctx, &gqlerror.Error{
				Message:    "a closure already exists for this date",
				Extensions: map[string]any{"code": "CLOSURE_ALREADY_EXISTS"},
			})
			return nil, nil
		}
		log.Printf("🔴 DATABASE TRANSACTION FAILED IN CREATECLOSURE: %v", err)
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "internal server error: failed to create closure",
			Extensions: map[string]any{"code": "INTERNAL_SERVER_ERROR"},
		})
		return nil, nil
	}

	return &c, nil
}

// DeleteClosure is the resolver for the deleteClosure field.
func (r *mutationResolver) DeleteClosure(ctx context.Context, id string) (bool, error) {
	var restaurantID string
	if err := r.Resolver.DB.QueryRow(ctx, `SELECT restaurant_id FROM closures WHERE id = $1`, id).Scan(&restaurantID); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return false, nil
		}
		return false, err
	}

	if _, err := utils.RequireRestaurantStaff(ctx, r.Resolver.DB, restaurantID, true); err != nil {
		return false, nil
	}

	if _, err := r.Resolver.DB.Exec(ctx, `DELETE FROM closures WHERE id = $1`, id); err != nil {
		log.Printf("🔴 DATABASE DELETE FAILED IN DELETECLOSURE: %v", err)
		return false, err
	}

	return true, nil
}

// FindOrCreateCustomer is the resolver for the findOrCreateCustomer field.
// Called by the Go webhook handler when Vapi passes through the caller's
// phone number — no dashboard auth guard, see assumptions note at top.
func (r *mutationResolver) FindOrCreateCustomer(ctx context.Context, input model.FindOrCreateCustomerInput) (*model.Customer, error) {
	var c model.Customer
	var createdAt time.Time

	err := r.Resolver.DB.QueryRow(ctx, `
		INSERT INTO customers (phone, name, email)
		VALUES ($1, $2, $3)
		ON CONFLICT (phone) DO UPDATE SET
			name = COALESCE(EXCLUDED.name, customers.name),
			email = COALESCE(EXCLUDED.email, customers.email)
		RETURNING id, phone, name, email, created_at
	`, input.Phone, input.Name, input.Email).Scan(&c.ID, &c.Phone, &c.Name, &c.Email, &createdAt)

	if err != nil {
		log.Printf("🔴 DATABASE TRANSACTION FAILED IN FINDORCREATECUSTOMER: %v", err)
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "internal server error: failed to resolve customer",
			Extensions: map[string]any{"code": "INTERNAL_SERVER_ERROR"},
		})
		return nil, nil
	}

	c.CreatedAt = createdAt.Format(time.RFC3339)
	return &c, nil
}

// CreateBooking is the resolver for the createBooking field.
// CreateBooking is the resolver for the createBooking field.
func (r *mutationResolver) CreateBooking(ctx context.Context, input model.CreateBookingInput) (*model.Booking, error) {
	// Idempotency check first — if a webhook retry sends the same key, return
	// the existing booking instead of erroring or double-inserting.
	var existingID string
	err := r.Resolver.DB.QueryRow(ctx,
		`SELECT id FROM bookings WHERE idempotency_key = $1`, input.IdempotencyKey,
	).Scan(&existingID)
	if err == nil {
		return r.Query().Booking(ctx, existingID)
	}
	if !errors.Is(err, pgx.ErrNoRows) {
		log.Printf("🔴 DATABASE QUERY FAILED IN CREATEBOOKING IDEMPOTENCY CHECK: %v", err)
		return nil, err
	}

	var turnDuration int
	if err := r.Resolver.DB.QueryRow(ctx,
		`SELECT default_turn_duration_min FROM restaurants WHERE id = $1`, input.RestaurantID,
	).Scan(&turnDuration); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			graphql.AddError(ctx, &gqlerror.Error{
				Message:    "not found: restaurant does not exist",
				Extensions: map[string]any{"code": "NOT_FOUND"},
			})
			return nil, nil
		}
		return nil, err
	}

	bookingTime, err := time.Parse(time.RFC3339, input.BookingTime)
	if err != nil {
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "invalid bookingTime: must be ISO 8601 / RFC3339",
			Extensions: map[string]any{"code": "BAD_USER_INPUT"},
		})
		return nil, nil
	}

	endTime := bookingTime.Add(time.Duration(turnDuration) * time.Minute)
	timeRange := fmt.Sprintf("[%s,%s)", bookingTime.Format(time.RFC3339), endTime.Format(time.RFC3339))

	source := model.BookingSourcePhone
	if input.Source != nil {
		source = *input.Source
	}

	query := `
		INSERT INTO bookings (
			restaurant_id, customer_id, table_id, party_size, booking_time,
			duration_minutes, time_range, special_requests, source, idempotency_key
		)
		VALUES ($1, $2, $3, $4, $5, $6, $7::tstzrange, $8, $9, $10)
		RETURNING id, status, payment_status, created_at, updated_at
	`

	var b model.Booking
	b.RestaurantID = input.RestaurantID
	b.CustomerID = input.CustomerID
	b.TableID = input.TableID
	b.PartySize = input.PartySize
	b.BookingTime = input.BookingTime
	b.DurationMinutes = turnDuration
	b.SpecialRequests = input.SpecialRequests
	b.Source = source

	var createdAt, updatedAt time.Time
	err = r.Resolver.DB.QueryRow(ctx, query,
		input.RestaurantID, input.CustomerID, input.TableID, input.PartySize, bookingTime,
		turnDuration, timeRange, input.SpecialRequests, source, input.IdempotencyKey,
	).Scan(&b.ID, &b.Status, &b.PaymentStatus, &createdAt, &updatedAt)

	if err != nil {
		if utils.IsExclusionViolation(err) {
			graphql.AddError(ctx, &gqlerror.Error{
				Message:    "that table is already booked for the requested time",
				Extensions: map[string]any{"code": "TABLE_ALREADY_BOOKED"},
			})
			return nil, nil
		}
		if utils.IsUniqueViolation(err) {
			var raceID string
			if lookupErr := r.Resolver.DB.QueryRow(ctx,
				`SELECT id FROM bookings WHERE idempotency_key = $1`, input.IdempotencyKey,
			).Scan(&raceID); lookupErr == nil {
				return r.Query().Booking(ctx, raceID)
			}
		}
		log.Printf("🔴 DATABASE TRANSACTION FAILED IN CREATEBOOKING: %v", err)
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "internal server error: failed to create booking",
			Extensions: map[string]any{"code": "INTERNAL_SERVER_ERROR"},
		})
		return nil, nil
	}

	b.CreatedAt = createdAt.Format(time.RFC3339)
	b.UpdatedAt = updatedAt.Format(time.RFC3339)
	return &b, nil
}

// UpdateBooking is the resolver for the updateBooking field.
// UpdateBooking is the resolver for the updateBooking field.
func (r *mutationResolver) UpdateBooking(ctx context.Context, id string, input model.UpdateBookingInput) (*model.Booking, error) {
	var bookingTime *time.Time
	var timeRange *string

	if input.BookingTime != nil {
		parsed, err := time.Parse(time.RFC3339, *input.BookingTime)
		if err != nil {
			graphql.AddError(ctx, &gqlerror.Error{
				Message:    "invalid bookingTime: must be ISO 8601 / RFC3339",
				Extensions: map[string]any{"code": "BAD_USER_INPUT"},
			})
			return nil, nil
		}
		bookingTime = &parsed

		// booking_time changed — time_range must be recalculated to match,
		// or the EXCLUDE constraint checks a stale window. Duration doesn't
		// change here, so pull the current duration_minutes to compute the
		// new end time.
		var durationMinutes int
		if err := r.Resolver.DB.QueryRow(ctx,
			`SELECT duration_minutes FROM bookings WHERE id = $1`, id,
		).Scan(&durationMinutes); err != nil {
			if errors.Is(err, pgx.ErrNoRows) {
				graphql.AddError(ctx, &gqlerror.Error{
					Message:    "not found: booking does not exist",
					Extensions: map[string]any{"code": "NOT_FOUND"},
				})
				return nil, nil
			}
			return nil, err
		}

		end := parsed.Add(time.Duration(durationMinutes) * time.Minute)
		tr := fmt.Sprintf("[%s,%s)", parsed.Format(time.RFC3339), end.Format(time.RFC3339))
		timeRange = &tr
	}

	query := `
		UPDATE bookings SET
			table_id = COALESCE($1, table_id),
			party_size = COALESCE($2, party_size),
			booking_time = COALESCE($3, booking_time),
			time_range = COALESCE($4::tstzrange, time_range),
			status = COALESCE($5, status),
			special_requests = COALESCE($6, special_requests),
			payment_status = COALESCE($7, payment_status),
			updated_at = NOW()
		WHERE id = $8
		RETURNING id, restaurant_id, customer_id, table_id, party_size, booking_time,
			duration_minutes, status, special_requests, payment_status, source, created_at, updated_at
	`

	var b model.Booking
	var bt, createdAt, updatedAt time.Time
	err := r.Resolver.DB.QueryRow(ctx, query,
		input.TableID, input.PartySize, bookingTime, timeRange, input.Status, input.SpecialRequests, input.PaymentStatus, id,
	).Scan(
		&b.ID, &b.RestaurantID, &b.CustomerID, &b.TableID, &b.PartySize, &bt,
		&b.DurationMinutes, &b.Status, &b.SpecialRequests, &b.PaymentStatus, &b.Source, &createdAt, &updatedAt,
	)

	if err != nil {
		if utils.IsExclusionViolation(err) {
			graphql.AddError(ctx, &gqlerror.Error{
				Message:    "that table is already booked for the requested time",
				Extensions: map[string]any{"code": "TABLE_ALREADY_BOOKED"},
			})
			return nil, nil
		}
		if errors.Is(err, pgx.ErrNoRows) {
			graphql.AddError(ctx, &gqlerror.Error{
				Message:    "not found: booking does not exist",
				Extensions: map[string]any{"code": "NOT_FOUND"},
			})
			return nil, nil
		}
		log.Printf("🔴 DATABASE UPDATE FAILED IN UPDATEBOOKING: %v", err)
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "internal server error: failed saving booking updates",
			Extensions: map[string]any{"code": "INTERNAL_SERVER_ERROR"},
		})
		return nil, nil
	}

	b.BookingTime = bt.Format(time.RFC3339)
	b.CreatedAt = createdAt.Format(time.RFC3339)
	b.UpdatedAt = updatedAt.Format(time.RFC3339)
	return &b, nil
}

// CancelBooking is the resolver for the cancelBooking field.
func (r *mutationResolver) CancelBooking(ctx context.Context, id string) (*model.Booking, error) {
	cancelled := model.BookingStatusCancelled
	return r.UpdateBooking(ctx, id, model.UpdateBookingInput{Status: &cancelled})
}

// AssignTable is the resolver for the assignTable field.
// Kept as its own mutation (rather than routing through UpdateBooking) since
// this is the action a host takes at the podium, distinct from a diner-facing
// change like party size.
func (r *mutationResolver) AssignTable(ctx context.Context, bookingID string, tableID string) (*model.Booking, error) {
	return r.UpdateBooking(ctx, bookingID, model.UpdateBookingInput{TableID: &tableID})
}

// CreateWaitlistEntry is the resolver for the createWaitlistEntry field.
func (r *mutationResolver) CreateWaitlistEntry(ctx context.Context, input model.CreateWaitlistEntryInput) (*model.WaitlistEntry, error) {
	requestedTime, err := time.Parse(time.RFC3339, input.RequestedTime)
	if err != nil {
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "invalid requestedTime: must be ISO 8601 / RFC3339",
			Extensions: map[string]any{"code": "BAD_USER_INPUT"},
		})
		return nil, nil
	}

	var w model.WaitlistEntry
	var createdAt time.Time
	err = r.Resolver.DB.QueryRow(ctx, `
		INSERT INTO waitlist (restaurant_id, customer_id, party_size, requested_time)
		VALUES ($1, $2, $3, $4)
		RETURNING id, status, created_at
	`, input.RestaurantID, input.CustomerID, input.PartySize, requestedTime).Scan(&w.ID, &w.Status, &createdAt)

	if err != nil {
		log.Printf("🔴 DATABASE TRANSACTION FAILED IN CREATEWAITLISTENTRY: %v", err)
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "internal server error: failed to join waitlist",
			Extensions: map[string]any{"code": "INTERNAL_SERVER_ERROR"},
		})
		return nil, nil
	}

	w.RestaurantID = input.RestaurantID
	w.CustomerID = input.CustomerID
	w.PartySize = input.PartySize
	w.RequestedTime = input.RequestedTime
	w.CreatedAt = createdAt.Format(time.RFC3339)
	return &w, nil
}

// UpdateWaitlistStatus is the resolver for the updateWaitlistStatus field.
func (r *mutationResolver) UpdateWaitlistStatus(ctx context.Context, id string, status model.WaitlistStatus) (*model.WaitlistEntry, error) {
	var w model.WaitlistEntry
	var requestedTime, createdAt time.Time
	err := r.Resolver.DB.QueryRow(ctx, `
		UPDATE waitlist SET status = $1 WHERE id = $2
		RETURNING id, restaurant_id, customer_id, party_size, requested_time, status, created_at
	`, status, id).Scan(&w.ID, &w.RestaurantID, &w.CustomerID, &w.PartySize, &requestedTime, &w.Status, &createdAt)

	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			graphql.AddError(ctx, &gqlerror.Error{
				Message:    "not found: waitlist entry does not exist",
				Extensions: map[string]any{"code": "NOT_FOUND"},
			})
			return nil, nil
		}
		log.Printf("🔴 DATABASE UPDATE FAILED IN UPDATEWAITLISTSTATUS: %v", err)
		return nil, err
	}

	w.RequestedTime = requestedTime.Format(time.RFC3339)
	w.CreatedAt = createdAt.Format(time.RFC3339)
	return &w, nil
}

// ConvertWaitlistToBooking is the resolver for the convertWaitlistToBooking field.
// Runs as a transaction: create the booking, then mark the waitlist entry
// converted — if the table got taken in the meantime, the EXCLUDE constraint
// on bookings will reject the insert and we roll back cleanly rather than
// leaving the waitlist entry in a half-converted state.
func (r *mutationResolver) ConvertWaitlistToBooking(ctx context.Context, id string, tableID string) (*model.Booking, error) {
	tx, err := r.Resolver.DB.Begin(ctx)
	if err != nil {
		log.Printf("🔴 FAILED TO ACQUIRE TRANSACTION IN CONVERTWAITLISTTOBOOKING: %v", err)
		return nil, fmt.Errorf("internal server error")
	}
	defer tx.Rollback(ctx)

	var restaurantID, customerID string
	var partySize int
	var requestedTime time.Time
	// NOTE: status literals must match the migration's CHECK constraint
	// exactly — chk_waitlist_status only allows 'WAITING', 'NOTIFIED',
	// 'CONVERTED', 'EXPIRED' (uppercase). Lowercase 'waiting' never matches
	// any real row.
	err = tx.QueryRow(ctx, `
		SELECT restaurant_id, customer_id, party_size, requested_time FROM waitlist WHERE id = $1 AND status = 'WAITING'
	`, id).Scan(&restaurantID, &customerID, &partySize, &requestedTime)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			graphql.AddError(ctx, &gqlerror.Error{
				Message:    "not found: no waiting waitlist entry with that id",
				Extensions: map[string]any{"code": "NOT_FOUND"},
			})
			return nil, nil
		}
		return nil, err
	}

	var turnDuration int
	if err := tx.QueryRow(ctx, `SELECT default_turn_duration_min FROM restaurants WHERE id = $1`, restaurantID).Scan(&turnDuration); err != nil {
		return nil, err
	}

	// time_range is NOT NULL with no default — compute it here just like
	// CreateBooking does, or this insert fails with a not-null violation.
	requestedEnd := requestedTime.Add(time.Duration(turnDuration) * time.Minute)
	timeRange := fmt.Sprintf("[%s,%s)", requestedTime.Format(time.RFC3339), requestedEnd.Format(time.RFC3339))

	var b model.Booking
	var createdAt, updatedAt time.Time
	err = tx.QueryRow(ctx, `
		INSERT INTO bookings (restaurant_id, customer_id, table_id, party_size, booking_time, duration_minutes, time_range, source, idempotency_key)
		VALUES ($1, $2, $3, $4, $5, $6, $7::tstzrange, 'phone', $8)
		RETURNING id, status, payment_status, created_at, updated_at
	`, restaurantID, customerID, tableID, partySize, requestedTime, turnDuration, timeRange, "waitlist-"+id).
		Scan(&b.ID, &b.Status, &b.PaymentStatus, &createdAt, &updatedAt)

	if err != nil {
		if utils.IsExclusionViolation(err) {
			graphql.AddError(ctx, &gqlerror.Error{
				Message:    "that table is already booked for the requested time",
				Extensions: map[string]any{"code": "TABLE_ALREADY_BOOKED"},
			})
			return nil, nil
		}
		log.Printf("🔴 FAILED TO CREATE BOOKING FROM WAITLIST %s: %v", id, err)
		return nil, fmt.Errorf("internal server error: failed converting waitlist entry")
	}

	if _, err = tx.Exec(ctx, `UPDATE waitlist SET status = 'CONVERTED' WHERE id = $1`, id); err != nil {
		log.Printf("🔴 FAILED TO MARK WAITLIST ENTRY %s CONVERTED: %v", id, err)
		return nil, fmt.Errorf("internal server error")
	}

	if err = tx.Commit(ctx); err != nil {
		log.Printf("🔴 TRANSACTION COMMIT FAILED IN CONVERTWAITLISTTOBOOKING: %v", err)
		return nil, fmt.Errorf("internal server error")
	}

	b.RestaurantID = restaurantID
	b.CustomerID = customerID
	b.TableID = &tableID
	b.PartySize = partySize
	b.BookingTime = requestedTime.Format(time.RFC3339)
	b.DurationMinutes = turnDuration
	b.CreatedAt = createdAt.Format(time.RFC3339)
	b.UpdatedAt = updatedAt.Format(time.RFC3339)
	return &b, nil
}

// LogCall is the resolver for the logCall field.
// Written by the Go webhook handler as the call progresses / completes.
func (r *mutationResolver) LogCall(ctx context.Context, input model.LogCallInput) (*model.CallLog, error) {
	var c model.CallLog
	var createdAt time.Time
	err := r.Resolver.DB.QueryRow(ctx, `
		INSERT INTO call_logs (restaurant_id, vapi_call_id, customer_phone, booking_id, transcript, outcome)
		VALUES ($1, $2, $3, $4, $5, $6)
		RETURNING id, created_at
	`, input.RestaurantID, input.VapiCallID, input.CustomerPhone, input.BookingID, input.Transcript, input.Outcome).
		Scan(&c.ID, &createdAt)

	if err != nil {
		log.Printf("🔴 DATABASE TRANSACTION FAILED IN LOGCALL: %v", err)
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "internal server error: failed to log call",
			Extensions: map[string]any{"code": "INTERNAL_SERVER_ERROR"},
		})
		return nil, nil
	}

	c.RestaurantID = input.RestaurantID
	c.VapiCallID = input.VapiCallID
	c.CustomerPhone = input.CustomerPhone
	c.BookingID = input.BookingID
	c.Transcript = input.Transcript
	c.Outcome = input.Outcome
	c.CreatedAt = createdAt.Format(time.RFC3339)
	return &c, nil
}

// Restaurant is the resolver for the restaurant field.
func (r *queryResolver) Restaurant(ctx context.Context, id string) (*model.Restaurant, error) {
	query := `
		SELECT id, name, phone, email, address_line1, suburb, state, postcode, timezone,
			cuisine_type, seating_type, default_turn_duration_min, booking_buffer_min,
			max_party_size, is_active, created_at, updated_at
		FROM restaurants WHERE id = $1
	`

	var res model.Restaurant
	var createdAt, updatedAt time.Time

	err := r.Resolver.DB.QueryRow(ctx, query, id).Scan(
		&res.ID, &res.Name, &res.Phone, &res.Email, &res.AddressLine1, &res.Suburb, &res.State, &res.Postcode,
		&res.Timezone, &res.CuisineType, &res.SeatingType, &res.DefaultTurnDurationMin, &res.BookingBufferMin,
		&res.MaxPartySize, &res.IsActive, &createdAt, &updatedAt,
	)

	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, nil
		}
		log.Printf("🔴 DATABASE QUERY FAILED IN RESTAURANT: %v", err)
		return nil, err
	}

	res.CreatedAt = createdAt.Format(time.RFC3339)
	res.UpdatedAt = updatedAt.Format(time.RFC3339)
	return &res, nil
}

// Restaurants is the resolver for the restaurants field.
func (r *queryResolver) Restaurants(ctx context.Context, suburb *string, cuisineType *string) ([]*model.Restaurant, error) {
	query := `
		SELECT id, name, phone, email, address_line1, suburb, state, postcode, timezone,
			cuisine_type, seating_type, default_turn_duration_min, booking_buffer_min,
			max_party_size, is_active, created_at, updated_at
		FROM restaurants
		WHERE is_active = true
			AND ($1::text IS NULL OR suburb ILIKE $1)
			AND ($2::text IS NULL OR cuisine_type ILIKE $2)
		ORDER BY name ASC
	`

	rows, err := r.Resolver.DB.Query(ctx, query, suburb, cuisineType)
	if err != nil {
		log.Printf("🔴 DATABASE QUERY FAILED IN RESTAURANTS: %v", err)
		return nil, err
	}
	defer rows.Close()

	var results []*model.Restaurant
	for rows.Next() {
		var res model.Restaurant
		var createdAt, updatedAt time.Time
		if err := rows.Scan(
			&res.ID, &res.Name, &res.Phone, &res.Email, &res.AddressLine1, &res.Suburb, &res.State, &res.Postcode,
			&res.Timezone, &res.CuisineType, &res.SeatingType, &res.DefaultTurnDurationMin, &res.BookingBufferMin,
			&res.MaxPartySize, &res.IsActive, &createdAt, &updatedAt,
		); err != nil {
			log.Printf("⚠️ Failed to scan restaurant row: %v", err)
			continue
		}
		res.CreatedAt = createdAt.Format(time.RFC3339)
		res.UpdatedAt = updatedAt.Format(time.RFC3339)
		results = append(results, &res)
	}

	return results, nil
}

// Customer is the resolver for the customer field.
func (r *queryResolver) Customer(ctx context.Context, phone string) (*model.Customer, error) {
	var c model.Customer
	var createdAt time.Time

	err := r.Resolver.DB.QueryRow(ctx, `
		SELECT id, phone, name, email, created_at FROM customers WHERE phone = $1
	`, phone).Scan(&c.ID, &c.Phone, &c.Name, &c.Email, &createdAt)

	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, nil
		}
		log.Printf("🔴 DATABASE QUERY FAILED IN CUSTOMER: %v", err)
		return nil, err
	}

	c.CreatedAt = createdAt.Format(time.RFC3339)
	return &c, nil
}

// Booking is the resolver for the booking field.
func (r *queryResolver) Booking(ctx context.Context, id string) (*model.Booking, error) {
	query := `
		SELECT id, restaurant_id, customer_id, table_id, party_size, booking_time,
			duration_minutes, status, special_requests, payment_status, source, created_at, updated_at
		FROM bookings WHERE id = $1
	`

	var b model.Booking
	var bt, createdAt, updatedAt time.Time
	err := r.Resolver.DB.QueryRow(ctx, query, id).Scan(
		&b.ID, &b.RestaurantID, &b.CustomerID, &b.TableID, &b.PartySize, &bt,
		&b.DurationMinutes, &b.Status, &b.SpecialRequests, &b.PaymentStatus, &b.Source, &createdAt, &updatedAt,
	)

	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, nil
		}
		log.Printf("🔴 DATABASE QUERY FAILED IN BOOKING: %v", err)
		return nil, err
	}

	b.BookingTime = bt.Format(time.RFC3339)
	b.CreatedAt = createdAt.Format(time.RFC3339)
	b.UpdatedAt = updatedAt.Format(time.RFC3339)
	return &b, nil
}

// Bookings is the resolver for the bookings field.
func (r *queryResolver) Bookings(ctx context.Context, restaurantID string, date *string, status *model.BookingStatus) ([]*model.Booking, error) {
	query := `
		SELECT id, restaurant_id, customer_id, table_id, party_size, booking_time,
			duration_minutes, status, special_requests, payment_status, source, created_at, updated_at
		FROM bookings
		WHERE restaurant_id = $1
			AND ($2::date IS NULL OR booking_time::date = $2::date)
			AND ($3::text IS NULL OR status = $3)
		ORDER BY booking_time ASC
	`

	rows, err := r.Resolver.DB.Query(ctx, query, restaurantID, date, status)
	if err != nil {
		log.Printf("🔴 DATABASE QUERY FAILED IN BOOKINGS: %v", err)
		return nil, err
	}
	defer rows.Close()

	var results []*model.Booking
	for rows.Next() {
		var b model.Booking
		var bt, createdAt, updatedAt time.Time
		if err := rows.Scan(
			&b.ID, &b.RestaurantID, &b.CustomerID, &b.TableID, &b.PartySize, &bt,
			&b.DurationMinutes, &b.Status, &b.SpecialRequests, &b.PaymentStatus, &b.Source, &createdAt, &updatedAt,
		); err != nil {
			log.Printf("⚠️ Failed to scan booking row: %v", err)
			continue
		}
		b.BookingTime = bt.Format(time.RFC3339)
		b.CreatedAt = createdAt.Format(time.RFC3339)
		b.UpdatedAt = updatedAt.Format(time.RFC3339)
		results = append(results, &b)
	}

	return results, nil
}

// CheckAvailability is the resolver for the checkAvailability field.
// This is the query your voice agent calls to answer "do you have a table
// for 4 at 7pm". Correctness is ultimately backed by the EXCLUDE constraint
// on bookings — this query is the fast-path check, the constraint is the
// guarantee if two requests race.
func (r *queryResolver) CheckAvailability(ctx context.Context, input model.CheckAvailabilityInput) ([]*model.AvailableSlot, error) {
	requestedTime, err := time.Parse(time.RFC3339, input.RequestedTime)
	if err != nil {
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "invalid requestedTime: must be ISO 8601 / RFC3339",
			Extensions: map[string]any{"code": "BAD_USER_INPUT"},
		})
		return nil, nil
	}

	var turnDuration int
	if err := r.Resolver.DB.QueryRow(ctx,
		`SELECT default_turn_duration_min FROM restaurants WHERE id = $1`, input.RestaurantID,
	).Scan(&turnDuration); err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			graphql.AddError(ctx, &gqlerror.Error{
				Message:    "not found: restaurant does not exist",
				Extensions: map[string]any{"code": "NOT_FOUND"},
			})
			return nil, nil
		}
		return nil, err
	}

	// NOTE: status literals must match the migration's CHECK constraint
	// exactly — chk_bookings_status only allows 'CANCELLED', 'NO_SHOW', etc.
	// (uppercase). Lowercase never matched, so cancelled/no-show bookings
	// were incorrectly still blocking their table.
	query := `
		SELECT rt.id, rt.table_number, rt.capacity_min, rt.capacity_max, rt.section
		FROM restaurant_tables rt
		WHERE rt.restaurant_id = $1
			AND rt.is_active = true
			AND rt.capacity_max >= $2
			AND rt.capacity_min <= $2
			AND NOT EXISTS (
				SELECT 1 FROM bookings b
				WHERE b.table_id = rt.id
					AND b.status NOT IN ('CANCELLED', 'NO_SHOW')
					AND b.time_range && tstzrange($3::timestamptz, $3::timestamptz + ($4 || ' minutes')::interval)
			)
		ORDER BY rt.capacity_max ASC
	`

	rows, err := r.Resolver.DB.Query(ctx, query, input.RestaurantID, input.PartySize, requestedTime, turnDuration)
	if err != nil {
		log.Printf("🔴 DATABASE QUERY FAILED IN CHECKAVAILABILITY: %v", err)
		return nil, err
	}
	defer rows.Close()

	endTime := requestedTime.Add(time.Duration(turnDuration) * time.Minute)

	var slots []*model.AvailableSlot
	for rows.Next() {
		var t model.RestaurantTable
		t.RestaurantID = input.RestaurantID
		t.IsActive = true
		if err := rows.Scan(&t.ID, &t.TableNumber, &t.CapacityMin, &t.CapacityMax, &t.Section); err != nil {
			log.Printf("⚠️ Failed to scan table row in checkAvailability: %v", err)
			continue
		}
		slots = append(slots, &model.AvailableSlot{
			Table:     &t,
			StartTime: requestedTime.Format(time.RFC3339),
			EndTime:   endTime.Format(time.RFC3339),
		})
	}

	return slots, nil
}

// Waitlist is the resolver for the waitlist field.
func (r *queryResolver) Waitlist(ctx context.Context, restaurantID string, status *model.WaitlistStatus) ([]*model.WaitlistEntry, error) {
	query := `
		SELECT id, restaurant_id, customer_id, party_size, requested_time, status, created_at
		FROM waitlist
		WHERE restaurant_id = $1 AND ($2::text IS NULL OR status = $2)
		ORDER BY requested_time ASC
	`

	rows, err := r.Resolver.DB.Query(ctx, query, restaurantID, status)
	if err != nil {
		log.Printf("🔴 DATABASE QUERY FAILED IN WAITLIST: %v", err)
		return nil, err
	}
	defer rows.Close()

	var results []*model.WaitlistEntry
	for rows.Next() {
		var w model.WaitlistEntry
		var requestedTime, createdAt time.Time
		if err := rows.Scan(&w.ID, &w.RestaurantID, &w.CustomerID, &w.PartySize, &requestedTime, &w.Status, &createdAt); err != nil {
			log.Printf("⚠️ Failed to scan waitlist row: %v", err)
			continue
		}
		w.RequestedTime = requestedTime.Format(time.RFC3339)
		w.CreatedAt = createdAt.Format(time.RFC3339)
		results = append(results, &w)
	}

	return results, nil
}

// CallLog is the resolver for the callLog field.
func (r *queryResolver) CallLog(ctx context.Context, vapiCallID string) (*model.CallLog, error) {
	var c model.CallLog
	var createdAt time.Time
	err := r.Resolver.DB.QueryRow(ctx, `
		SELECT id, restaurant_id, vapi_call_id, customer_phone, booking_id, transcript, outcome, created_at
		FROM call_logs WHERE vapi_call_id = $1
	`, vapiCallID).Scan(&c.ID, &c.RestaurantID, &c.VapiCallID, &c.CustomerPhone, &c.BookingID, &c.Transcript, &c.Outcome, &createdAt)

	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			return nil, nil
		}
		log.Printf("🔴 DATABASE QUERY FAILED IN CALLLOG: %v", err)
		return nil, err
	}

	c.CreatedAt = createdAt.Format(time.RFC3339)
	return &c, nil
}
