package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"go-backend/internal/graph/model"
	"go-backend/internal/middleware"
	"go-backend/internal/utils"
	"log"
	"os"
	"time"

	"github.com/99designs/gqlgen/graphql"
	pgx "github.com/jackc/pgx/v5"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// CreateShop is the resolver for the createShop field.
func (r *mutationResolver) CreateShop(ctx context.Context, input model.CreateShopInput) (*model.OwnerShop, error) {
	// SECURITY GUARD: Enforce valid user identity state from Redis session
	currentUser := ctx.Value("currentUser").(middleware.CachedUser)

	// 1. INITIALIZE IMAGE UPLOADER WITH THE BASE PATH
	uploader, err := utils.NewImageUploader(
		os.Getenv("CLOUDINARY_CLOUD_NAME"),
		os.Getenv("CLOUDINARY_API_KEY"),
		os.Getenv("CLOUDINARY_API_SECRET"),
		os.Getenv("CLOUDINARY_FOLDER"),
	)
	if err != nil {
		log.Printf("🔴 FAILED TO INITIALIZE CLOUDINARY UPLOADER: %v", err)
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "internal server error: media processing failure",
			Extensions: map[string]any{"code": "INTERNAL_SERVER_ERROR"},
		})
		return nil, nil
	}
	if err != nil {
		log.Printf("🔴 FAILED TO INITIALIZE CLOUDINARY UPLOADER: %v", err)
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "internal server error: media processing failure",
			Extensions: map[string]any{"code": "INTERNAL_SERVER_ERROR"},
		})
		return nil, nil
	}

	// Dynamic target isolation mapping: /userId/shops
	uploadFolder := fmt.Sprintf("%s/%s/shops", os.Getenv("CLOUDINARY_FOLDER"), currentUser.ID)
	shopUploader := uploader.WithFolder(uploadFolder)

	// 2. UPLOAD PRIMARY LOGO/BANNER TO USER'S SHOPS CONTAINER
	finalPrimaryPhoto := ""
	if input.Photo != nil && input.Photo.File != nil {
		result, err := shopUploader.UploadImage(ctx, input.Photo.File, input.Photo.Filename)
		if err == nil {
			finalPrimaryPhoto = result.URL
		} else {
			log.Printf("⚠️ Primary photo upload failed: %v", err)
		}
	}

	// 3. STREAM MULTIPLE CAROUSEL GALLERY SLICES INDEPENDENTLY
	var finalPhotosSlice []string = []string{}
	for _, upload := range input.Photos {
		if upload != nil && upload.File != nil {
			result, err := shopUploader.UploadImage(ctx, upload.File, upload.Filename)
			if err != nil {
				log.Printf("⚠️ Additional photo slice failed to upload: %v", err)
				continue // Gracefully skip failed slice tracks
			}
			finalPhotosSlice = append(finalPhotosSlice, result.URL)
		}
	}

	// Marshal dynamic user configuration properties to structural JSON strings
	hoursJSON, _ := json.Marshal(input.BusinessHours)
	paymentsJSON, _ := json.Marshal(input.PaymentMethods)
	deliveryJSON, _ := json.Marshal(input.Delivery)
	socialJSON, _ := json.Marshal(input.SocialMedia)
	contactJSON, _ := json.Marshal(input.ContactDetails)
	coordinatesJSON, _ := json.Marshal(input.Coordinates)

	statusJSON, _ := json.Marshal(map[string]any{"isActive": true})
	verificationJSON, _ := json.Marshal(map[string]any{"isVerified": false, "verifiedDate": nil, "verificationId": ""})

	// 4. RETRIEVE ID VALUES STRAIGHT FROM POSTGRESQL DEFAULT SEQUENCES
	query := `
		INSERT INTO shops (
			shop_name, address, description, photo, photos, owner_id, created_at,
			business_hours, payment_methods, delivery, social_media, contact_details,
			coordinates, status, verification
		) 
		VALUES ($1, $2, $3, $4, $5, $6, NOW(), $7, $8, $9, $10, $11, $12, $13, $14) 
		RETURNING id, created_at
	`
	var insertedID string
	var createdAt time.Time

	// Execute storage bindings including newly obtained secure asset links
	err = r.Resolver.DB.QueryRow(ctx, query,
		input.ShopName,    // $1
		input.Address,     // $2
		input.Description, // $3
		finalPrimaryPhoto, // $4 <-- Saved secure string URL path reference
		finalPhotosSlice,  // $5 <-- Saved string array paths references
		currentUser.ID,    // $6
		hoursJSON,         // $7
		paymentsJSON,      // $8
		deliveryJSON,      // $9
		socialJSON,        // $10
		contactJSON,       // $11
		coordinatesJSON,   // $12
		statusJSON,        // $13
		verificationJSON,  // $14
	).Scan(&insertedID, &createdAt)

	if err != nil {
		log.Printf("🔴 DATABASE TRANSACTION FAILED IN CREATESHOP: %v", err)
		graphql.AddError(ctx, &gqlerror.Error{
			Message: "internal server error: failed to create shop entry",
			Extensions: map[string]any{
				"code": "INTERNAL_SERVER_ERROR",
			},
		})
		return nil, nil
	}

	// 5. MAP PERSISTED PARAMS TO SYSTEM REPRESENTATION INTERFACES
	return &model.OwnerShop{
		ID:          insertedID, // Uses native ID from SQL table schema
		OwnerID:     currentUser.ID,
		ShopName:    input.ShopName,
		Address:     input.Address,
		Description: input.Description,
		Photo:       &finalPrimaryPhoto,
		Photos:      finalPhotosSlice,
		CreatedAt:   createdAt.Format(time.RFC3339),
		Coordinates: &model.Coordinates{
			Lat: input.Coordinates.Lat,
			Lng: input.Coordinates.Lng,
		},
		BusinessHours: &model.BusinessHours{
			OpenTime:  input.BusinessHours.OpenTime,
			CloseTime: input.BusinessHours.CloseTime,
			Days:      input.BusinessHours.Days,
		},
		PaymentMethods: &model.PaymentMethods{
			Cash:    input.PaymentMethods.Cash,
			Gcash:   input.PaymentMethods.Gcash,
			Paymaya: input.PaymentMethods.Paymaya,
			Card:    input.PaymentMethods.Card,
		},
		Delivery: &model.DeliveryOptions{
			Available: input.Delivery.Available,
			Radius:    input.Delivery.Radius,
			Fee:       input.Delivery.Fee,
			MinOrder:  input.Delivery.MinOrder,
		},
		SocialMedia: &model.SocialMedia{
			Facebook:  input.SocialMedia.Facebook,
			Instagram: input.SocialMedia.Instagram,
		},
		ContactDetails: &model.ContactDetails{
			Phone:   input.ContactDetails.Phone,
			Email:   input.ContactDetails.Email,
			Address: input.ContactDetails.Address,
		},
		Status: &model.ShopStatus{
			IsActive: true,
		},
		Verification: &model.Verification{
			IsVerified: false,
		},
	}, nil
}

// UpdateShop is the resolver for the updateShop field.
func (r *mutationResolver) UpdateShop(ctx context.Context, input model.UpdateShopInput) (*model.OwnerShop, error) {
	// SECURITY GUARD 1: Is user logged in?
	currentUser := ctx.Value("currentUser").(middleware.CachedUser)

	// SECURITY GUARD 2: Fetch current database values to compare against
	var dbOwnerID string
	var verificationJSON []byte
	var statusJSON []byte
	var oldPrimaryPhoto *string
	var oldPhotosSlice []string

	checkQuery := "SELECT owner_id, status, verification, photo, photos FROM shops WHERE id = $1 LIMIT 1"
	err := r.Resolver.DB.QueryRow(ctx, checkQuery, input.ShopID).Scan(
		&dbOwnerID, &statusJSON, &verificationJSON, &oldPrimaryPhoto, &oldPhotosSlice,
	)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			graphql.AddError(ctx, &gqlerror.Error{
				Message:    "not found: target shop resource does not exist",
				Extensions: map[string]interface{}{"code": "NOT_FOUND"},
			})
			return nil, nil
		}
		return nil, err
	}

	if dbOwnerID != currentUser.ID {
		log.Printf("⚠️ SECURITY ALERT: User %s tried to mutate shop %s owned by %s", currentUser.ID, input.ShopID, dbOwnerID)
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "forbidden: you do not have permission to edit this shop",
			Extensions: map[string]interface{}{"code": "FORBIDDEN"},
		})
		return nil, nil
	}

	// INITIALIZE THE CLOUDINARY UPLOADER UTILITY VIA REGULAR ENVS
	uploader, err := utils.NewImageUploader(
		os.Getenv("CLOUDINARY_CLOUD_NAME"),
		os.Getenv("CLOUDINARY_API_KEY"),
		os.Getenv("CLOUDINARY_API_SECRET"),
		os.Getenv("CLOUDINARY_FOLDER"),
	)
	if err != nil {
		log.Printf("🔴 FAILED TO INITIALIZE CLOUDINARY UPLOADER IN UPDATESHOP: %v", err)
		return nil, fmt.Errorf("media processor error")
	}

	uploadFolder := fmt.Sprintf("%s/%s/shops", os.Getenv("CLOUDINARY_FOLDER"), currentUser.ID)
	shopUploader := uploader.WithFolder(uploadFolder)

	// =========================================================================
	// 1. PRIMARY COVER PHOTO REFACTOR (Matches your old Post logic)
	// =========================================================================
	finalPrimaryPhoto := ""
	if input.Photo != nil {
		finalPrimaryPhoto = *input.Photo // Take what the frontend wants to preserve
	}

	// Compare DB record with incoming state: if it changed or cleared, flag it for cleanup
	var deletedPrimaryPhoto string
	if oldPrimaryPhoto != nil && *oldPrimaryPhoto != "" && *oldPrimaryPhoto != finalPrimaryPhoto {
		deletedPrimaryPhoto = *oldPrimaryPhoto
	}

	// Process the new cover binary upload if sent by the client
	if input.NewPhoto != nil && input.NewPhoto.File != nil {
		result, uploadErr := shopUploader.UploadImage(ctx, input.NewPhoto.File, input.NewPhoto.Filename)
		if uploadErr == nil {
			finalPrimaryPhoto = result.URL
		} else {
			log.Printf("🔴 Primary photo upload failed: %v", uploadErr)
		}
	}

	// =========================================================================
	// 2. GALLERY CAROUSEL REFACTOR (Matches your old Post logic)
	// =========================================================================
	finalPhotosSlice := []string{}
	if input.Photos != nil {
		finalPhotosSlice = append([]string{}, input.Photos...) // Seed with retained URLs
	}

	// Diffs old database array against incoming retained slice to find deletions
	var deletedGalleryPhotos []string
	if input.Photos != nil {
		deletedGalleryPhotos = utils.DiffPhotoURLs(oldPhotosSlice, finalPhotosSlice)
	}

	// Stream and append any brand new image uploads into the gallery container slice
	for _, upload := range input.NewPhotos {
		if upload != nil && upload.File != nil {
			result, uploadErr := shopUploader.UploadImage(ctx, upload.File, upload.Filename)
			if uploadErr != nil {
				log.Printf("⚠️ Additional photo upload failed: %v", uploadErr)
				continue
			}
			finalPhotosSlice = append(finalPhotosSlice, result.URL)
		}
	}

	// =========================================================================
	// 3. SERIALIZE & UPDATE DATABASE
	// =========================================================================
	hoursJSON, _ := json.Marshal(input.BusinessHours)
	paymentsJSON, _ := json.Marshal(input.PaymentMethods)
	deliveryJSON, _ := json.Marshal(input.Delivery)
	socialJSON, _ := json.Marshal(input.SocialMedia)
	contactJSON, _ := json.Marshal(input.ContactDetails)
	coordinatesJSON, _ := json.Marshal(input.Coordinates)

	var currentStatus model.ShopStatus
	var currentVerification model.Verification
	_ = json.Unmarshal(statusJSON, &currentStatus)
	_ = json.Unmarshal(verificationJSON, &currentVerification)

	if finalPhotosSlice == nil {
		finalPhotosSlice = []string{}
	}

	updateQuery := `
		UPDATE shops 
		SET shop_name = $1, address = $2, description = $3, photo = $4, photos = $5,
			business_hours = $6, payment_methods = $7, delivery = $8, social_media = $9, 
			contact_details = $10, coordinates = $11
		WHERE id = $12
		RETURNING id, created_at
	`
	var id string
	var createdAt time.Time

	err = r.Resolver.DB.QueryRow(ctx, updateQuery,
		input.ShopName, input.Address, input.Description, finalPrimaryPhoto, finalPhotosSlice,
		hoursJSON, paymentsJSON, deliveryJSON, socialJSON, contactJSON, coordinatesJSON, input.ShopID,
	).Scan(&id, &createdAt)

	if err != nil {
		log.Printf("🔴 DATABASE UPDATE FAILED IN UPDATESHOP: %v", err)
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "internal server error: failed saving shop updates",
			Extensions: map[string]interface{}{"code": "INTERNAL_SERVER_ERROR"},
		})
		return nil, nil
	}

	// =========================================================================
	// 4. SECURE CLOUDINARY CLEANUP SWEEPS (Best-effort execution pipeline)
	// =========================================================================
	// Clean up cover image from Cloudinary if deleted or overwritten
	if deletedPrimaryPhoto != "" {
		_ = shopUploader.DeleteImageByURL(ctx, deletedPrimaryPhoto)
	}

	// Clean up individual deleted gallery carousel items from Cloudinary
	for _, photoURL := range deletedGalleryPhotos {
		if photoURL != "" {
			_ = shopUploader.DeleteImageByURL(ctx, photoURL)
		}
	}

	return &model.OwnerShop{
		ID:             id,
		OwnerID:        currentUser.ID,
		ShopName:       input.ShopName,
		Address:        input.Address,
		Description:    input.Description,
		Photo:          &finalPrimaryPhoto,
		Photos:         finalPhotosSlice,
		CreatedAt:      createdAt.Format(time.RFC3339),
		Coordinates:    &model.Coordinates{Lat: input.Coordinates.Lat, Lng: input.Coordinates.Lng},
		BusinessHours:  &model.BusinessHours{OpenTime: input.BusinessHours.OpenTime, CloseTime: input.BusinessHours.CloseTime, Days: input.BusinessHours.Days},
		PaymentMethods: &model.PaymentMethods{Cash: input.PaymentMethods.Cash, Gcash: input.PaymentMethods.Gcash, Paymaya: input.PaymentMethods.Paymaya, Card: input.PaymentMethods.Card},
		Delivery:       &model.DeliveryOptions{Available: input.Delivery.Available, Radius: input.Delivery.Radius, Fee: input.Delivery.Fee, MinOrder: input.Delivery.MinOrder},
		SocialMedia:    &model.SocialMedia{Facebook: input.SocialMedia.Facebook, Instagram: input.SocialMedia.Instagram},
		ContactDetails: &model.ContactDetails{Phone: input.ContactDetails.Phone, Email: input.ContactDetails.Email, Address: input.ContactDetails.Address},
		Status:         &currentStatus,
		Verification:   &currentVerification,
	}, nil
}

// DeleteShop is the resolver for the deleteShop field.
func (r *mutationResolver) DeleteShop(ctx context.Context, shopID string) (bool, error) {
	// SECURITY GUARD 1: Is user logged in?
	currentUser := ctx.Value("currentUser").(middleware.CachedUser)

	// SECURITY GUARD 2 & ASSET ACQUISITION: Fetch owner id and all associated photos before deleting the row
	var dbOwnerID string
	var oldPrimaryPhoto *string
	var oldPhotosSlice []string

	checkQuery := "SELECT owner_id, photo, photos FROM shops WHERE id = $1 LIMIT 1"
	err := r.Resolver.DB.QueryRow(ctx, checkQuery, shopID).Scan(&dbOwnerID, &oldPrimaryPhoto, &oldPhotosSlice)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			graphql.AddError(ctx, &gqlerror.Error{
				Message:    "not found: target resource does not exist",
				Extensions: map[string]interface{}{"code": "NOT_FOUND"},
			})
			return false, nil
		}
		return false, err
	}

	if dbOwnerID != currentUser.ID {
		log.Printf("⚠️ SECURITY ALERT: Deletion bypass attempt blocked on User ID %s for shop %s", currentUser.ID, shopID)
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "forbidden: you can only delete shops that you created",
			Extensions: map[string]interface{}{"code": "FORBIDDEN"},
		})
		return false, nil
	}

	// 1. INITIALIZE THE CLOUDINARY UPLOADER UTILITY DIRECTLY VIA OS ENVS
	uploader, err := utils.NewImageUploader(
		os.Getenv("CLOUDINARY_CLOUD_NAME"),
		os.Getenv("CLOUDINARY_API_KEY"),
		os.Getenv("CLOUDINARY_API_SECRET"),
		os.Getenv("CLOUDINARY_FOLDER"),
	)
	if err != nil {
		log.Printf("🔴 FAILED TO INITIALIZE CLOUDINARY UPLOADER IN DELETESHOP: %v", err)
		return false, fmt.Errorf("media processor error")
	}

	uploadFolder := fmt.Sprintf("%s/%s/shops", os.Getenv("CLOUDINARY_FOLDER"), currentUser.ID)
	shopUploader := uploader.WithFolder(uploadFolder)

	// 2. TRIGGER CLOUDINARY CLEANUP CODES FOR PRIMARY PHOTO
	if oldPrimaryPhoto != nil && *oldPrimaryPhoto != "" {
		if cleanErr := shopUploader.DeleteImageByURL(ctx, *oldPrimaryPhoto); cleanErr != nil {
			log.Printf("⚠️ Failed to remove primary shop image %s on deletion: %v", *oldPrimaryPhoto, cleanErr)
		}
	}

	// 3. TRIGGER CLOUDINARY CLEANUP CODES FOR ALL GALLERY CAROUSEL PHOTOS
	for _, oldURL := range oldPhotosSlice {
		if oldURL != "" {
			if cleanErr := shopUploader.DeleteImageByURL(ctx, oldURL); cleanErr != nil {
				log.Printf("⚠️ Failed to remove gallery shop image %s on deletion: %v", oldURL, cleanErr)
			}
		}
	}

	// 4. DATABASE ROW ELIMINATION
	deleteQuery := "DELETE FROM shops WHERE id = $1"
	_, err = r.Resolver.DB.Exec(ctx, deleteQuery, shopID)
	if err != nil {
		log.Printf("🔴 DATABASE DELETION FAILED IN DELETESHOP: %v", err)
		return false, err
	}

	return true, nil
}

// AddInventoryItem is the resolver for the addInventoryItem field.
func (r *mutationResolver) AddInventoryItem(ctx context.Context, input model.AddInventoryItemInput) (*model.OwnerInventoryItem, error) {
	// SECURITY GUARD 1: Enforce valid user identity state from Redis session
	currentUser := ctx.Value("currentUser").(middleware.CachedUser)

	// SECURITY GUARD 2: Verify the caller is the actual owner of the target shop
	var shopOwnerID string
	var shopName string
	checkQuery := "SELECT owner_id, shop_name FROM shops WHERE id = $1 LIMIT 1"
	err := r.Resolver.DB.QueryRow(ctx, checkQuery, input.ShopID).Scan(&shopOwnerID, &shopName)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			graphql.AddError(ctx, &gqlerror.Error{
				Message:    "not found: target shop resource does not exist",
				Extensions: map[string]interface{}{"code": "NOT_FOUND"},
			})
			return nil, nil
		}
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "internal server error: shop lookup failure",
			Extensions: map[string]interface{}{"code": "INTERNAL_SERVER_ERROR"},
		})
		return nil, nil
	}

	if shopOwnerID != currentUser.ID {
		log.Printf("⚠️ SECURITY ALERT: User %s tried to add items to shop %s owned by user %s", currentUser.ID, input.ShopID, shopOwnerID)
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "forbidden: you do not have permission to modify this shop",
			Extensions: map[string]interface{}{"code": "FORBIDDEN"},
		})
		return nil, nil
	}

	// 1. INITIALIZE IMAGE UPLOADER WITH THE BASE PATH
	uploader, err := utils.NewImageUploader(
		os.Getenv("CLOUDINARY_CLOUD_NAME"),
		os.Getenv("CLOUDINARY_API_KEY"),
		os.Getenv("CLOUDINARY_API_SECRET"),
		os.Getenv("CLOUDINARY_FOLDER"),
	)
	if err != nil {
		log.Printf("🔴 FAILED TO INITIALIZE CLOUDINARY UPLOADER FOR INVENTORY: %v", err)
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "internal server error: media processing failure",
			Extensions: map[string]any{"code": "INTERNAL_SERVER_ERROR"},
		})
		return nil, nil
	}

	// Dynamic target isolation mapping: /userId/shops/shopId/inventory
	uploadFolder := fmt.Sprintf("%s/%s/shops/%s/inventory/%s", os.Getenv("CLOUDINARY_FOLDER"), currentUser.ID, shopName, input.ItemName)
	inventoryUploader := uploader.WithFolder(uploadFolder)

	// 2. UPLOAD PRODUCT PHOTO TO CLOUDINARY IF PROVIDED
	finalProductPhoto := ""
	if input.Photo != nil && input.Photo.File != nil {

		result, err := inventoryUploader.UploadImage(ctx, input.Photo.File, input.Photo.Filename)
		if err == nil {
			finalProductPhoto = result.URL
		} else {
			log.Printf("⚠️ Product photo upload failed: %v", err)
			// Optional: Return a graphql error here if photos are strictly mandatory
		}
	}

	// 3. PERSIST RECORD TO POSTGRES CONFIGURED WITH SECURE CLOUDINARY PATH URL
	query := `
		INSERT INTO inventory_items (
			shop_id, item_name, description, barcode, category, 
			unit_of_measure, photo, cost_price, selling_price, 
			stock_quantity, reorder_level, updated_at
		)
		VALUES ($1, $2, $3, $4, $5, $6, $7, COALESCE($8, 0.00), COALESCE($9, 0.00), COALESCE($10, 0), COALESCE($11, 5), NOW())
		RETURNING id, cost_price, selling_price, stock_quantity, reorder_level, updated_at
	`

	var insertedID string
	var costPrice, sellingPrice float64
	var stockQuantity, reorderLevel int
	var updatedAt time.Time

	err = r.Resolver.DB.QueryRow(ctx, query,
		input.ShopID, input.ItemName, input.Description, input.Barcode, input.Category,
		input.UnitOfMeasure, finalProductPhoto, input.CostPrice, input.SellingPrice, input.StockQuantity, input.ReorderLevel,
	).Scan(&insertedID, &costPrice, &sellingPrice, &stockQuantity, &reorderLevel, &updatedAt)

	if err == nil {
		initialQuantity := stockQuantity
		_ = utils.RecordItemActionHistory(ctx, r.Resolver.DB, utils.ItemActionHistoryInput{
			ShopID:          input.ShopID,
			InventoryItemID: insertedID,
			ItemName:        input.ItemName,
			Action:          "added item",
			Quantity:        &initialQuantity,
		})
	}

	if err != nil {
		log.Printf("🔴 DATABASE TRANSACTION FAILED IN ADDINVENTORYITEM: %v", err)
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "internal server error: failed to create inventory item entry",
			Extensions: map[string]interface{}{"code": "INTERNAL_SERVER_ERROR"},
		})
		return nil, nil
	}

	return &model.OwnerInventoryItem{
		ID:            insertedID,
		ShopID:        input.ShopID,
		ItemName:      input.ItemName,
		Description:   input.Description,
		Barcode:       input.Barcode,
		Category:      input.Category,
		UnitOfMeasure: input.UnitOfMeasure,
		Photo:         &finalProductPhoto, // Pointers sync accurately with your models schema representation
		CostPrice:     &costPrice,
		SellingPrice:  &sellingPrice,
		StockQuantity: &stockQuantity,
		ReorderLevel:  &reorderLevel,
		UpdatedAt:     updatedAt.Format(time.RFC3339),
	}, nil
}

// UpdateInventoryItem is the resolver for the updateInventoryItem field.
func (r *mutationResolver) UpdateInventoryItem(ctx context.Context, input model.UpdateInventoryItemInput) (*model.OwnerInventoryItem, error) {
	// SECURITY GUARD 1: Is user logged in?
	currentUser := ctx.Value("currentUser").(middleware.CachedUser)

	// SECURITY GUARD 2: Fetch current database values to evaluate owner and grab old photo
	var shopOwnerID string
	var oldPhoto *string
	var shopName string // 🚀 Rename variable to capture name
	checkQuery := `
		SELECT s.owner_id, i.photo, s.shop_name FROM inventory_items i
		JOIN shops s ON i.shop_id = s.id
		WHERE i.id = $1 LIMIT 1
	`
	err := r.Resolver.DB.QueryRow(ctx, checkQuery, input.ItemID).Scan(&shopOwnerID, &oldPhoto, &shopName)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			graphql.AddError(ctx, &gqlerror.Error{
				Message:    "not found: target item does not exist",
				Extensions: map[string]interface{}{"code": "NOT_FOUND"},
			})
			return nil, nil
		}
		return nil, err
	}

	if shopOwnerID != currentUser.ID {
		log.Printf("⚠️ SECURITY ALERT: User %s tried to edit item %s owned by %s", currentUser.ID, input.ItemID, shopOwnerID)
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "forbidden: access denied to modify this item",
			Extensions: map[string]interface{}{"code": "FORBIDDEN"},
		})
		return nil, nil
	}

	// INITIALIZE THE CLOUDINARY UPLOADER UTILITY VIA REGULAR ENVS
	uploader, err := utils.NewImageUploader(
		os.Getenv("CLOUDINARY_CLOUD_NAME"),
		os.Getenv("CLOUDINARY_API_KEY"),
		os.Getenv("CLOUDINARY_API_SECRET"),
		os.Getenv("CLOUDINARY_FOLDER"),
	)
	if err != nil {
		log.Printf("🔴 FAILED TO INITIALIZE CLOUDINARY UPLOADER IN UPDATEINVENTORYITEM: %v", err)
		return nil, fmt.Errorf("media processor error")
	}

	// Dynamic target isolation mapping: /userId/shops/shopId/inventory
	uploadFolder := fmt.Sprintf("%s/%s/shops/%s/inventory/%s", os.Getenv("CLOUDINARY_FOLDER"), currentUser.ID, shopName, input.ItemName)
	inventoryUploader := uploader.WithFolder(uploadFolder)

	// =========================================================================
	// 1. PRODUCT PHOTO UPDATES REFACTOR (Matches UpdateShop pattern exactly)
	// =========================================================================
	finalPhoto := ""
	if input.Photo != nil {
		finalPhoto = *input.Photo // Take what the frontend wants to retain
	}

	// Compare DB record with incoming state: if it changed or cleared, flag it for cleanup
	var deletedPhoto string
	if oldPhoto != nil && *oldPhoto != "" && *oldPhoto != finalPhoto {
		deletedPhoto = *oldPhoto
	}

	// Process the new binary upload stream if sent by the client input layer
	if input.NewPhoto != nil && input.NewPhoto.File != nil {

		result, uploadErr := inventoryUploader.UploadImage(ctx, input.NewPhoto.File, input.NewPhoto.Filename)
		if uploadErr == nil {
			finalPhoto = result.URL
		} else {
			log.Printf("🔴 Product photo upload failed during update: %v", uploadErr)
		}
	}

	// =========================================================================
	// 2. PERSIST AND EXECUTE SQL DATABASE UPDATE MATRIX
	// =========================================================================
	updateQuery := `
		UPDATE inventory_items 
		SET item_name = $1, description = $2, barcode = $3, category = $4, unit_of_measure = $5, photo = $6,
		    cost_price = COALESCE($7, 0.00), selling_price = COALESCE($8, 0.00), stock_quantity = COALESCE($9, 0), reorder_level = COALESCE($10, 5), updated_at = NOW() 
		WHERE id = $11
		RETURNING id, shop_id, item_name, description, barcode, category, unit_of_measure, photo, cost_price, selling_price, stock_quantity, reorder_level, updated_at
	`
	var item model.OwnerInventoryItem
	var updatedAt time.Time

	err = r.Resolver.DB.QueryRow(ctx, updateQuery,
		input.ItemName, input.Description, input.Barcode, input.Category, input.UnitOfMeasure, finalPhoto,
		input.CostPrice, input.SellingPrice, input.StockQuantity, input.ReorderLevel, input.ItemID,
	).Scan(
		&item.ID, &item.ShopID, &item.ItemName, &item.Description, &item.Barcode, &item.Category,
		&item.UnitOfMeasure, &item.Photo, &item.CostPrice, &item.SellingPrice, &item.StockQuantity, &item.ReorderLevel, &updatedAt,
	)
	if err != nil {
		log.Printf("🔴 DATABASE UPDATE FAILED IN UPDATEINVENTORYITEM: %v", err)
		return nil, err
	}

	item.UpdatedAt = updatedAt.Format(time.RFC3339)
	_ = utils.RecordItemActionHistory(ctx, r.Resolver.DB, utils.ItemActionHistoryInput{
		ShopID:          item.ShopID,
		InventoryItemID: item.ID,
		ItemName:        item.ItemName,
		Action:          "edited item",
	})

	// =========================================================================
	// 3. SECURE CLOUDINARY CLEANUP SWEEPS (Best-effort execution pipeline)
	// =========================================================================
	// Purges old orphaned asset from Cloudinary storage if overwritten or cleared
	if deletedPhoto != "" {
		_ = inventoryUploader.DeleteImageByURL(ctx, deletedPhoto)
	}

	return &item, nil
}

// DeleteInventoryItem is the resolver for the deleteInventoryItem field.
func (r *mutationResolver) DeleteInventoryItem(ctx context.Context, itemID string) (bool, error) {
	// SECURITY GUARD 1: Is user logged in?
	currentUser := ctx.Value("currentUser").(middleware.CachedUser)

	// SECURITY GUARD 2 & ASSET ACQUISITION: Fetch owner id, photo link, and shop id before resource wipeout
	var shopOwnerID string
	var oldPhoto *string
	var shopID string
	var itemName string

	checkQuery := `
		SELECT s.owner_id, i.photo, i.shop_id, i.item_name FROM inventory_items i
		JOIN shops s ON i.shop_id = s.id
		WHERE i.id = $1 LIMIT 1
	`
	err := r.Resolver.DB.QueryRow(ctx, checkQuery, itemID).Scan(&shopOwnerID, &oldPhoto, &shopID, &itemName)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			graphql.AddError(ctx, &gqlerror.Error{
				Message:    "not found: item does not exist",
				Extensions: map[string]interface{}{"code": "NOT_FOUND"},
			})
			return false, nil
		}
		return false, err
	}

	if shopOwnerID != currentUser.ID {
		log.Printf("⚠️ SECURITY ALERT: User %s tried to delete item %s owned by %s", currentUser.ID, itemID, shopOwnerID)
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "forbidden: access denied to delete this item",
			Extensions: map[string]interface{}{"code": "FORBIDDEN"},
		})
		return false, nil
	}

	// 1. INITIALIZE THE CLOUDINARY UPLOADER UTILITY DIRECTLY VIA OS ENVS
	uploader, err := utils.NewImageUploader(
		os.Getenv("CLOUDINARY_CLOUD_NAME"),
		os.Getenv("CLOUDINARY_API_KEY"),
		os.Getenv("CLOUDINARY_API_SECRET"),
		os.Getenv("CLOUDINARY_FOLDER"),
	)
	if err != nil {
		log.Printf("🔴 FAILED TO INITIALIZE CLOUDINARY UPLOADER IN DELETEINVENTORYITEM: %v", err)
		return false, fmt.Errorf("media processor error")
	}

	// Dynamic target isolation mapping: /userId/shops/shopId/inventory
	uploadFolder := fmt.Sprintf("%s/%s/shops/%s/inventory", os.Getenv("CLOUDINARY_FOLDER"), currentUser.ID, shopID)
	inventoryUploader := uploader.WithFolder(uploadFolder)

	// 2. TRIGGER CLOUDINARY CLEANUP CODES FOR SINGLE PRODUCT PHOTO
	if oldPhoto != nil && *oldPhoto != "" {
		if cleanErr := inventoryUploader.DeleteImageByURL(ctx, *oldPhoto); cleanErr != nil {
			log.Printf("⚠️ Failed to remove inventory product image %s on deletion: %v", *oldPhoto, cleanErr)
		}
	}

	// 3. DATABASE ROW ELIMINATION
	deleteQuery := "DELETE FROM inventory_items WHERE id = $1"
	_, err = r.Resolver.DB.Exec(ctx, deleteQuery, itemID)
	if err != nil {
		log.Printf("🔴 DATABASE DELETION FAILED IN DELETEINVENTORYITEM: %v", err)
		return false, err
	}

	_ = utils.RecordItemActionHistory(ctx, r.Resolver.DB, utils.ItemActionHistoryInput{
		ShopID:          shopID,
		InventoryItemID: itemID,
		ItemName:        itemName,
		Action:          "deleted item",
	})

	return true, nil
}

// IncrementStock is the resolver for the incrementStock field.
func (r *mutationResolver) IncrementStock(ctx context.Context, input model.IncrementStockInput) (*model.OwnerInventoryItem, error) {
	// SECURITY GUARD 1: Is user logged in?
	currentUser := ctx.Value("currentUser").(middleware.CachedUser)

	// SECURITY GUARD 2: Fetch the owner_id of the shop holding this item via a JOIN
	var shopOwnerID string
	var shopID string
	checkQuery := `
		SELECT s.owner_id, i.shop_id FROM inventory_items i
		JOIN shops s ON i.shop_id = s.id
		WHERE i.id = $1 LIMIT 1
	`
	err := r.Resolver.DB.QueryRow(ctx, checkQuery, input.ItemID).Scan(&shopOwnerID, &shopID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			graphql.AddError(ctx, &gqlerror.Error{
				Message: "not found: target item does not exist",
				Extensions: map[string]interface{}{
					"code": "NOT_FOUND",
				},
			})
			return nil, nil
		}
		graphql.AddError(ctx, &gqlerror.Error{
			Message: "internal server error: item verification failure",
			Extensions: map[string]interface{}{
				"code": "INTERNAL_SERVER_ERROR",
			},
		})
		return nil, nil
	}

	if shopOwnerID != currentUser.ID {
		log.Printf("⚠️ SECURITY ALERT: User %s tried to increment stock for item %s owned by user %s", currentUser.ID, input.ItemID, shopOwnerID)
		graphql.AddError(ctx, &gqlerror.Error{
			Message: "forbidden: access denied to modify this item",
			Extensions: map[string]interface{}{
				"code": "FORBIDDEN",
			},
		})
		return nil, nil
	}

	// Perform atomic addition update directly in PostgreSQL
	updateQuery := `
		UPDATE inventory_items 
		SET stock_quantity = stock_quantity + $1, updated_at = NOW() 
		WHERE id = $2
		RETURNING id, shop_id, item_name, description, barcode, category, unit_of_measure, photo, cost_price, selling_price, stock_quantity, reorder_level, updated_at
	`

	var item model.OwnerInventoryItem
	var updatedAt time.Time

	err = r.Resolver.DB.QueryRow(ctx, updateQuery, input.QuantityToAdd, input.ItemID).Scan(
		&item.ID, &item.ShopID, &item.ItemName, &item.Description, &item.Barcode, &item.Category,
		&item.UnitOfMeasure, &item.Photo, &item.CostPrice, &item.SellingPrice, &item.StockQuantity, &item.ReorderLevel, &updatedAt,
	)

	if err != nil {
		graphql.AddError(ctx, &gqlerror.Error{
			Message: "internal server error: stock adjustment execution failure",
			Extensions: map[string]interface{}{
				"code": "INTERNAL_SERVER_ERROR",
			},
		})
		return nil, nil
	}

	item.UpdatedAt = updatedAt.Format(time.RFC3339)
	quantityAdded := input.QuantityToAdd
	_ = utils.RecordItemActionHistory(ctx, r.Resolver.DB, utils.ItemActionHistoryInput{
		ShopID:          shopID,
		InventoryItemID: item.ID,
		ItemName:        item.ItemName,
		Action:          "added stock",
		Quantity:        &quantityAdded,
	})
	return &item, nil
}

// DecrementStock is the resolver for the decrementStock field.
func (r *mutationResolver) DecrementStock(ctx context.Context, input model.DecrementStockInput) (*model.OwnerInventoryItem, error) {
	// SECURITY GUARD 1: Is user logged in?
	currentUser := ctx.Value("currentUser").(middleware.CachedUser)

	// SECURITY GUARD 2: Fetch the owner_id of the shop holding this item via a JOIN to verify resource ownership
	var shopOwnerID string
	checkQuery := `
		SELECT s.owner_id FROM inventory_items i
		JOIN shops s ON i.shop_id = s.id
		WHERE i.id = $1 LIMIT 1
	`
	err := r.Resolver.DB.QueryRow(ctx, checkQuery, input.ItemID).Scan(&shopOwnerID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			graphql.AddError(ctx, &gqlerror.Error{
				Message: "not found: target item does not exist",
				Extensions: map[string]interface{}{
					"code": "NOT_FOUND",
				},
			})
			return nil, nil
		}
		graphql.AddError(ctx, &gqlerror.Error{
			Message: "internal server error: item verification failure",
			Extensions: map[string]interface{}{
				"code": "INTERNAL_SERVER_ERROR",
			},
		})
		return nil, nil
	}

	// Block operation if the logged-in user does not own the shop containing this item
	if shopOwnerID != currentUser.ID {
		log.Printf("⚠️ SECURITY ALERT: User %s tried to decrement stock for item %s owned by user %s", currentUser.ID, input.ItemID, shopOwnerID)
		graphql.AddError(ctx, &gqlerror.Error{
			Message: "forbidden: access denied to modify this item",
			Extensions: map[string]interface{}{
				"code": "FORBIDDEN",
			},
		})
		return nil, nil
	}

	// Perform atomic deduction update directly in PostgreSQL
	// GREATEST(0, stock_quantity - $1) ensures stock level never dips below zero
	updateQuery := `
		UPDATE inventory_items 
		SET stock_quantity = GREATEST(0, stock_quantity - $1), updated_at = NOW() 
		WHERE id = $2
		RETURNING id, shop_id, item_name, description, barcode, category, unit_of_measure, photo, cost_price, selling_price, stock_quantity, reorder_level, updated_at
	`
	var item model.OwnerInventoryItem
	var updatedAt time.Time

	err = r.Resolver.DB.QueryRow(ctx, updateQuery, input.QuantityToRemove, input.ItemID).Scan(
		&item.ID, &item.ShopID, &item.ItemName, &item.Description, &item.Barcode, &item.Category,
		&item.UnitOfMeasure, &item.Photo, &item.CostPrice, &item.SellingPrice, &item.StockQuantity, &item.ReorderLevel, &updatedAt,
	)
	if err != nil {
		graphql.AddError(ctx, &gqlerror.Error{
			Message: "internal server error: stock adjustment failed",
			Extensions: map[string]interface{}{
				"code": "INTERNAL_SERVER_ERROR",
			},
		})
		return nil, nil
	}

	item.UpdatedAt = updatedAt.Format(time.RFC3339)
	return &item, nil
}

// CheckoutCart is the resolver for the checkoutCart field.
func (r *mutationResolver) CheckoutCart(ctx context.Context, input model.CheckoutCartInput) (*model.CheckoutBatch, error) {
	currentUser := ctx.Value("currentUser").(middleware.CachedUser)
	if err := utils.EnsureShopOwnership(ctx, r.Resolver.DB, input.ShopID, currentUser.ID); err != nil {
		utils.AddHistoryGraphQLError(ctx, err)
		return nil, nil
	}

	tx, err := r.Resolver.DB.Begin(ctx)
	if err != nil {
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "internal server error: checkout transaction start failure",
			Extensions: map[string]interface{}{"code": "INTERNAL_SERVER_ERROR"},
		})
		return nil, nil
	}
	defer tx.Rollback(ctx)

	batch, err := utils.BuildCheckoutBatch(ctx, tx, input)
	if err != nil {
		utils.AddHistoryGraphQLError(ctx, err)
		return nil, nil
	}

	if err := tx.Commit(ctx); err != nil {
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "internal server error: checkout commit failure",
			Extensions: map[string]interface{}{"code": "INTERNAL_SERVER_ERROR"},
		})
		return nil, nil
	}

	return batch, nil
}

// UnifiedBatchSync is the resolver for the unifiedBatchSync field.
func (r *mutationResolver) UnifiedBatchSync(ctx context.Context, input model.UnifiedBatchSyncInput) (*model.UnifiedBatchSyncPayload, error) {
	// 1. SECURITY GUARD: Validate active user context
	currentUser, ok := ctx.Value("currentUser").(middleware.CachedUser)
	if !ok {
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "Unauthorized access",
			Extensions: map[string]any{"code": "UNAUTHENTICATED"},
		})
		return nil, nil
	}

	// 2. BEGIN ACQUIRING ATOMIC TRANSACTION PIPE
	tx, err := r.Resolver.DB.Begin(ctx)
	if err != nil {
		log.Printf("🔴 FAILED TO ACQUIRE POSTGRES TRANSACTION: %v", err)
		return nil, errors.New("internal server error")
	}
	defer tx.Rollback(ctx) // Safe fallback rollback if execution fails halfway

	// Caches to map temporary localIds to genuine server database UUIDs
	shopIDMap := make(map[string]string)
	itemIDMap := make(map[string]string)

	// Arrays to keep track of confirmations returning down to this client
	var upsertedShops []map[string]any
	var upsertedInventory []map[string]any
	var upsertedCheckouts []map[string]any
	var upsertedHistories []map[string]any

	// =========================================================================
	// PHASE 1: PROCESS SHOPS BATCH ARRAY
	// =========================================================================
	for _, s := range input.Shops {
		if s.IsDeleted {
			// Process Soft Delete State Anchor
			_, err = tx.Exec(ctx, `UPDATE shops SET deleted_at = NOW() WHERE id = $1 AND owner_id = $2`, s.LocalID, currentUser.ID)
			if err != nil {
				log.Printf("🔴 BATCH SYNC: Failed to soft-delete shop %s: %v", s.LocalID, err)
				return nil, err
			}

			// Append a confirmation map so the frontend knows the delete succeeded!
			upsertedShops = append(upsertedShops, map[string]any{
				"id":        s.LocalID,
				"localId":   s.LocalID,
				"isDeleted": true,
			})
			continue
		}

		hoursJSON, _ := json.Marshal(s.BusinessHours)
		paymentsJSON, _ := json.Marshal(s.PaymentMethods)
		deliveryJSON, _ := json.Marshal(s.Delivery)
		socialJSON, _ := json.Marshal(s.SocialMedia)
		contactJSON, _ := json.Marshal(s.ContactDetails)
		coordinatesJSON, _ := json.Marshal(s.Coordinates)

		var finalServerID string
		var finalCreatedAt time.Time

		if s.IsServerSynced {
			// UPDATE Existing Record
			query := `
				UPDATE shops SET 
					shop_name = $1, address = $2, description = $3, photo = $4, photos = $5,
					business_hours = $6, payment_methods = $7, delivery = $8, social_media = $9, contact_details = $10, coordinates = $11
				WHERE id = $12 AND owner_id = $13
				RETURNING id, created_at
			`
			err = tx.QueryRow(ctx, query,
				s.ShopName, s.Address, s.Description, s.Photo, s.Photos,
				hoursJSON, paymentsJSON, deliveryJSON, socialJSON, contactJSON, coordinatesJSON,
				s.LocalID, currentUser.ID,
			).Scan(&finalServerID, &finalCreatedAt)
		} else {
			// INSERT New Record (Preserving true offline history via client_created_at if passed)
			createdAtAnchor := time.Now()
			if s.ClientCreatedAt != nil {
				if parsedTime, parseErr := time.Parse(time.RFC3339, *s.ClientCreatedAt); parseErr == nil {
					createdAtAnchor = parsedTime
				}
			}

			statusJSON, _ := json.Marshal(map[string]any{"isActive": true})
			verificationJSON, _ := json.Marshal(map[string]any{"isVerified": false})

			query := `
				INSERT INTO shops (
					shop_name, address, description, photo, photos, owner_id, created_at, 
					business_hours, payment_methods, delivery, social_media, contact_details, coordinates, status, verification
				) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
				RETURNING id, created_at
			`
			err = tx.QueryRow(ctx, query,
				s.ShopName, s.Address, s.Description, s.Photo, s.Photos, currentUser.ID, createdAtAnchor,
				hoursJSON, paymentsJSON, deliveryJSON, socialJSON, contactJSON, coordinatesJSON, statusJSON, verificationJSON,
			).Scan(&finalServerID, &finalCreatedAt)
		}

		if err != nil {
			log.Printf("🔴 BATCH SYNC: Shop processing collapsed on ID %s: %v", s.LocalID, err)
			return nil, err
		}

		// Hydrate ID Translation Table
		shopIDMap[s.LocalID] = finalServerID

		// FIX: Map the full properties manually to match what your frontend sync engine expects.
		// This keeps your UI fully populated without throwing undefined helper errors.
		upsertedShops = append(upsertedShops, map[string]any{
			"id":             finalServerID,
			"localId":        s.LocalID,
			"shopName":       s.ShopName,
			"address":        s.Address,
			"description":    s.Description,
			"photo":          s.Photo,
			"photos":         s.Photos,
			"coordinates":    s.Coordinates,
			"businessHours":  s.BusinessHours,
			"paymentMethods": s.PaymentMethods,
			"delivery":       s.Delivery,
			"socialMedia":    s.SocialMedia,
			"contactDetails": s.ContactDetails,
			"createdAt":      finalCreatedAt.Format(time.RFC3339),
		})
	}

	// =========================================================================
	// PHASE 2: PROCESS INVENTORY ITEMS BATCH ARRAY
	// =========================================================================
	for _, item := range input.Inventory {
		// Resolve dynamic parent foreign key using translation tables
		targetShopID := item.ShopID
		if realShopID, exists := shopIDMap[item.ShopID]; exists {
			targetShopID = realShopID
		}

		if item.IsDeleted {
			_, err = tx.Exec(ctx, `UPDATE inventory_items SET deleted_at = NOW() WHERE id = $1 AND shop_id = $2`, item.LocalID, targetShopID)
			if err != nil {
				log.Printf("🔴 BATCH SYNC: Failed to soft-delete item %s: %v", item.LocalID, err)
				return nil, err
			}

			// Append deletion confirmation back down to the frontend
			upsertedInventory = append(upsertedInventory, map[string]any{
				"id":        item.LocalID,
				"localId":   item.LocalID,
				"isDeleted": true,
			})
			continue
		}

		var finalItemID string
		if item.IsServerSynced {
			query := `
				UPDATE inventory_items SET 
					item_name = $1, description = $2, barcode = $3, category = $4, unit_of_measure = $5,
					cost_price = $6, selling_price = $7, stock_quantity = $8, reorder_level = $9, photo = $10
				WHERE id = $11 AND shop_id = $12
				RETURNING id
			`
			err = tx.QueryRow(ctx, query,
				item.ItemName, item.Description, item.Barcode, item.Category, item.UnitOfMeasure,
				item.CostPrice, item.SellingPrice, item.StockQuantity, item.ReorderLevel, item.Photo,
				item.LocalID, targetShopID,
			).Scan(&finalItemID)
		} else {
			query := `
				INSERT INTO inventory_items (
					shop_id, item_name, description, barcode, category, unit_of_measure, 
					cost_price, selling_price, stock_quantity, reorder_level, photo
				) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
				RETURNING id
			`
			err = tx.QueryRow(ctx, query,
				targetShopID, item.ItemName, item.Description, item.Barcode, item.Category, item.UnitOfMeasure,
				item.CostPrice, item.SellingPrice, item.StockQuantity, item.ReorderLevel, item.Photo,
			).Scan(&finalItemID)
		}

		if err != nil {
			log.Printf("🔴 BATCH SYNC: Inventory item collapsed on local ID %s: %v", item.LocalID, err)
			return nil, err
		}

		itemIDMap[item.LocalID] = finalItemID

		// FIX: Map the full item properties back down to the response slice manually
		// using your exact incoming input values to completely satisfy your frontend fields.
		upsertedInventory = append(upsertedInventory, map[string]any{
			"id":            finalItemID,
			"localId":       item.LocalID,
			"shopId":        targetShopID,
			"itemName":      item.ItemName,
			"description":   item.Description,
			"barcode":       item.Barcode,
			"category":      item.Category,
			"unitOfMeasure": item.UnitOfMeasure,
			"costPrice":     item.CostPrice,
			"sellingPrice":  item.SellingPrice,
			"stockQuantity": item.StockQuantity,
			"reorderLevel":  item.ReorderLevel,
			"photo":         item.Photo,
			"updatedAt":     time.Now().Format(time.RFC3339),
		})
	}

	// =========================================================================
	// PHASE 3: PROCESS CHECKOUT TRANSACTIONS BATCH ARRAY (Append-Only)
	// =========================================================================
	for _, c := range input.Checkouts {
		targetShopID := c.ShopID
		if realShopID, exists := shopIDMap[c.ShopID]; exists {
			targetShopID = realShopID
		}

		soldAtAnchor := time.Now()
		if c.ClientCreatedAt != nil {
			if parsedTime, parseErr := time.Parse(time.RFC3339, *c.ClientCreatedAt); parseErr == nil {
				soldAtAnchor = parsedTime
			}
		}

		// We will temporarily initialize counters to zero and compute sums during internal calculations
		var batchID string
		err = tx.QueryRow(ctx, `
			INSERT INTO checkout_batches (shop_id, sold_at, total_items, total_cost, gross_sale, gross_profit) 
			VALUES ($1, $2, 0, 0, 0, 0) RETURNING id`, targetShopID, soldAtAnchor).Scan(&batchID)
		if err != nil {
			return nil, err
		}

		var runningTotalItems int
		var runningTotalCost, runningGrossSale float64

		for _, itemInput := range c.Items {
			resolvedItemID := itemInput.ItemID
			if realItemID, exists := itemIDMap[itemInput.ItemID]; exists {
				resolvedItemID = realItemID
			}

			// Gather pricing reality directly inside database bounds to prevent spoofing variables
			var itemName string
			var costPrice, sellingPrice float64
			err = tx.QueryRow(ctx, `SELECT item_name, cost_price, selling_price FROM inventory_items WHERE id = $1`, resolvedItemID).Scan(&itemName, &costPrice, &sellingPrice)
			if err != nil {
				log.Printf("🔴 BATCH SYNC: Internal item validation lookup failure for checkout match: %v", err)
				return nil, err
			}

			lineCostTotal := costPrice * float64(itemInput.Quantity)
			lineSaleTotal := sellingPrice * float64(itemInput.Quantity)

			_, err = tx.Exec(ctx, `
				INSERT INTO checkout_batch_items (id, inventory_item_id, item_name, quantity, cost_price, selling_price, line_cost_total, line_sale_total)
				VALUES ($1, $2, $3, $4, $5, $6, $7, $8)`, batchID, resolvedItemID, itemName, itemInput.Quantity, costPrice, sellingPrice, lineCostTotal, lineSaleTotal)
			if err != nil {
				return nil, err
			}

			// Atomically decrement live stock balances
			_, err = tx.Exec(ctx, `UPDATE inventory_items SET stock_quantity = stock_quantity - $1 WHERE id = $2`, itemInput.Quantity, resolvedItemID)
			if err != nil {
				return nil, err
			}

			runningTotalItems += itemInput.Quantity
			runningTotalCost += lineCostTotal
			runningGrossSale += lineSaleTotal
		}

		// Update batch header aggregations with final totals
		grossProfit := runningGrossSale - runningTotalCost
		_, err = tx.Exec(ctx, `
			UPDATE checkout_batches 
			SET total_items = $1, total_cost = $2, gross_sale = $3, gross_profit = $4 
			WHERE id = $5`, runningTotalItems, runningTotalCost, runningGrossSale, grossProfit, batchID)
		if err != nil {
			return nil, err
		}

		upsertedCheckouts = append(upsertedCheckouts, map[string]any{
			"id":      batchID,
			"localId": c.LocalID,
			"shopId":  targetShopID,
		})
	}
	// =========================================================================
	// PHASE 4: PROCESS ITEM ACTION HISTORIES ARRAY (Append-Only)
	// =========================================================================
	for _, h := range input.ActionHistories {
		targetShopID := h.ShopID
		if realShopID, exists := shopIDMap[h.ShopID]; exists {
			targetShopID = realShopID
		}

		// Resolve dynamic inventory item foreign key using translation tables
		var resolvedItemID *string
		if h.InventoryItemID != nil {
			if realItemID, exists := itemIDMap[*h.InventoryItemID]; exists {
				// The item was newly created in this batch; use its real database ID
				realIDCopy := realItemID
				resolvedItemID = &realIDCopy
			} else {
				// The item already existed server-side; keep its provided ID
				providedIDCopy := *h.InventoryItemID
				resolvedItemID = &providedIDCopy
			}
		}

		// Parse the true offline historical time when the action was logged
		createdAtAnchor := time.Now()
		if parsedTime, parseErr := time.Parse(time.RFC3339, h.ClientCreatedAt); parseErr == nil {
			createdAtAnchor = parsedTime
		}

		var historyID string
		query := `
			INSERT INTO item_action_history (shop_id, inventory_item_id, item_name, action, quantity, created_at)
			VALUES ($1, $2, $3, $4, $5, $6)
			RETURNING id
		`
		err = tx.QueryRow(ctx, query, targetShopID, resolvedItemID, h.ItemName, h.Action, h.Quantity, createdAtAnchor).Scan(&historyID)
		if err != nil {
			log.Printf("🔴 BATCH SYNC: Failed appending history log for local ID %s: %v", h.LocalID, err)
			return nil, err
		}

		// FIX: Use accurate key formatting matching your target data models
		upsertedHistories = append(upsertedHistories, map[string]any{
			"id":              historyID,
			"localId":         h.LocalID,
			"shopId":          targetShopID,
			"inventoryItemId": resolvedItemID,
			"itemName":        h.ItemName,
			"action":          h.Action,
			"quantity":        h.Quantity,
			"date":            createdAtAnchor.Format(time.RFC3339),
		})
	}

	// =========================================================================
	// PHASE 5: FETCH GLOBAL DELTAS FROM PULL ANCHORS
	// =========================================================================
	// Capture the current authoritative backend clock time to send back as the next sync checkpoint
	serverCheckpointTime := time.Now().Format(time.RFC3339)

	lastSyncedAnchor, parseErr := time.Parse(time.RFC3339, input.LastSyncedAt)
	if parseErr != nil {
		// Fallback to Unix epoch baseline if the frontend sends an empty or invalid format
		lastSyncedAnchor = time.Unix(0, 0)
	}

	// 1. Fetch IDs of shops owned by this user that were deleted on other devices since last sync
	var deletedShops []string
	shopRows, err := tx.Query(ctx, `SELECT id FROM shops WHERE owner_id = $1 AND deleted_at > $2`, currentUser.ID, lastSyncedAnchor)
	if err == nil {
		for shopRows.Next() {
			var id string
			if errScan := shopRows.Scan(&id); errScan == nil {
				deletedShops = append(deletedShops, id)
			}
		}
		shopRows.Close()
	}

	// 2. Fetch IDs of inventory items in this user's shops that were deleted on other devices since last sync
	var deletedItems []string
	itemRows, err := tx.Query(ctx, `
		SELECT i.id 
		FROM inventory_items i 
		JOIN shops s ON i.shop_id = s.id 
		WHERE s.owner_id = $1 AND i.deleted_at > $2`,
		currentUser.ID, lastSyncedAnchor,
	)
	if err == nil {
		for itemRows.Next() {
			var id string
			if errScan := itemRows.Scan(&id); errScan == nil {
				deletedItems = append(deletedItems, id)
			}
		}
		itemRows.Close()
	}

	// =========================================================================
	// PHASE 6: TRANSACTION COMMIT AND PAYLOAD DISPATCH
	// =========================================================================
	// Everything succeeded atomically! Safely save all batch mutations to disk
	if errCommit := tx.Commit(ctx); errCommit != nil {
		log.Printf("🔴 BATCH SYNC: Transaction commit collision: %v", errCommit)
		return nil, fmt.Errorf("transaction commit collision: %w", errCommit)
	}

	// Package up all confirmation data and remote deltas for the frontend client
	return &model.UnifiedBatchSyncPayload{
		ShopsDelta: &model.DeltaResponse{
			Upserted:   upsertedShops,
			DeletedIds: deletedShops,
		},
		InventoryDelta: &model.DeltaResponse{
			Upserted:   upsertedInventory,
			DeletedIds: deletedItems,
		},
		CheckoutsDelta: &model.DeltaResponse{
			Upserted:   upsertedCheckouts,
			DeletedIds: []string{},
		},
		ActionHistoriesDelta: &model.DeltaResponse{
			Upserted:   upsertedHistories,
			DeletedIds: []string{},
		},
		ServerTime: serverCheckpointTime,
	}, nil

}

// GetMyShops is the resolver for the getMyShops field.
func (r *queryResolver) GetMyShops(ctx context.Context, limit int, offset int) (*model.PaginatedOwnerShops, error) {
	// SECURITY GUARD: Enforce valid user identity state from Redis session
	currentUser := ctx.Value("currentUser").(middleware.CachedUser)

	// 1. Get total record count for metadata pagination calculation based on current owner
	var totalCount int64
	countQuery := "SELECT COUNT(*) FROM shops WHERE owner_id = $1 AND deleted_at IS NULL "
	err := r.Resolver.DB.QueryRow(ctx, countQuery, currentUser.ID).Scan(&totalCount)
	if err != nil {
		graphql.AddError(ctx, &gqlerror.Error{
			Message: "internal server error: analytical tracking aggregation failure",
			Extensions: map[string]interface{}{
				"code": "INTERNAL_SERVER_ERROR",
			},
		})
		return nil, nil
	}

	// 2. Fetch the paginated subset from PostgreSQL (Matching your exact table schema columns)
	selectQuery := `
		SELECT id, shop_name, address, description, photo, photos, owner_id, created_at, 
		       verification, contact_details, status, coordinates, business_hours, payment_methods, delivery, social_media
		FROM shops 
		WHERE owner_id = $1
		 AND deleted_at IS NULL
		ORDER BY created_at DESC 
		LIMIT $2 OFFSET $3
	`
	rows, err := r.Resolver.DB.Query(ctx, selectQuery, currentUser.ID, limit, offset)
	if err != nil {
		log.Printf("🔴 Error getting shops: %v", err)
		graphql.AddError(ctx, &gqlerror.Error{
			Message: "internal server error: collection retrieval failure",
			Extensions: map[string]interface{}{
				"code": "INTERNAL_SERVER_ERROR",
			},
		})
		return nil, nil
	}
	defer rows.Close()

	var shops []*model.OwnerShop
	for rows.Next() {
		var shop model.OwnerShop
		var createdAt time.Time

		// Allocate temporary raw byte buffers to hold JSONB structures from PostgreSQL columns
		var verificationBytes []byte
		var contactBytes []byte
		var statusBytes []byte
		var coordinatesBytes []byte
		var hoursBytes []byte
		var paymentsBytes []byte
		var deliveryBytes []byte
		var socialBytes []byte

		// FIXED: Scan all 16 incoming column positions perfectly 1-to-1
		err := rows.Scan(
			&shop.ID, &shop.ShopName, &shop.Address, &shop.Description,
			&shop.Photo, &shop.Photos, &shop.OwnerID, &createdAt,
			&verificationBytes, &contactBytes, &statusBytes, &coordinatesBytes,
			&hoursBytes, &paymentsBytes, &deliveryBytes, &socialBytes,
		)
		if err != nil {
			log.Printf("🔴 Rows scan decoding anomaly details: %v", err)
			graphql.AddError(ctx, &gqlerror.Error{
				Message: "internal server error: data decoding anomaly",
				Extensions: map[string]interface{}{
					"code": "INTERNAL_SERVER_ERROR",
				},
			})
			return nil, nil
		}

		// Initialize structural payload containers to prevent nil pointer encoding memory exceptions
		shop.Verification = &model.Verification{}
		shop.ContactDetails = &model.ContactDetails{}
		shop.Status = &model.ShopStatus{}
		shop.Coordinates = &model.Coordinates{}
		shop.BusinessHours = &model.BusinessHours{}
		shop.PaymentMethods = &model.PaymentMethods{}
		shop.Delivery = &model.DeliveryOptions{}
		shop.SocialMedia = &model.SocialMedia{}

		// Safely decode JSON buffers straight back into your model layouts
		_ = json.Unmarshal(verificationBytes, shop.Verification)
		_ = json.Unmarshal(contactBytes, shop.ContactDetails)
		_ = json.Unmarshal(statusBytes, shop.Status)
		_ = json.Unmarshal(coordinatesBytes, shop.Coordinates)
		_ = json.Unmarshal(hoursBytes, shop.BusinessHours)
		_ = json.Unmarshal(paymentsBytes, shop.PaymentMethods)
		_ = json.Unmarshal(deliveryBytes, shop.Delivery)
		_ = json.Unmarshal(socialBytes, shop.SocialMedia)

		shop.CreatedAt = createdAt.Format(time.RFC3339)
		shops = append(shops, &shop)
	}

	if err := rows.Err(); err != nil {
		graphql.AddError(ctx, &gqlerror.Error{
			Message: "internal server error: active data stream break",
			Extensions: map[string]interface{}{
				"code": "INTERNAL_SERVER_ERROR",
			},
		})
		return nil, nil
	}

	// 3. Compute structural limits for layout boundary checks
	hasNextPage := int64(offset+limit) < totalCount

	return &model.PaginatedOwnerShops{
		Shops:       shops,
		TotalCount:  int(totalCount),
		HasNextPage: hasNextPage,
	}, nil
}

// GetShopByID is the resolver for the getShopById field.
func (r *queryResolver) GetShopByID(ctx context.Context, shopID string) (*model.OwnerShop, error) {
	// SECURITY GUARD: Enforce valid user identity state from Redis session
	currentUser := ctx.Value("currentUser").(middleware.CachedUser)

	// Fetch the specific row matching the target UUID
	selectQuery := `
		SELECT id, shop_name, address, description, photo, photos, owner_id, created_at, 
		       verification, contact_details, status, coordinates, business_hours, payment_methods, delivery, social_media
		FROM shops 
		WHERE id = $1 AND deleted_at IS NULL LIMIT 1
	`
	row := r.Resolver.DB.QueryRow(ctx, selectQuery, shopID)

	var shop model.OwnerShop
	var createdAt time.Time

	// Allocate temporary raw byte buffers to hold JSONB structures from PostgreSQL columns
	var verificationBytes []byte
	var contactBytes []byte
	var statusBytes []byte
	var coordinatesBytes []byte
	var hoursBytes []byte
	var paymentsBytes []byte
	var deliveryBytes []byte
	var socialBytes []byte

	// Scan all 16 distinct columns perfectly 1-to-1 matching your model layout
	err := row.Scan(
		&shop.ID, &shop.ShopName, &shop.Address, &shop.Description,
		&shop.Photo, &shop.Photos, &shop.OwnerID, &createdAt,
		&verificationBytes, &contactBytes, &statusBytes, &coordinatesBytes,
		&hoursBytes, &paymentsBytes, &deliveryBytes, &socialBytes,
	)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			graphql.AddError(ctx, &gqlerror.Error{
				Message:    "not found: target shop resource does not exist",
				Extensions: map[string]interface{}{"code": "NOT_FOUND"},
			})
			return nil, nil
		}
		log.Printf("🔴 Single shop row scan failure: %v", err)
		return nil, err
	}

	// 🔒 OWNERSHIP SECURITY VALIDATION GATE: Ensure user actually owns this row
	if shop.OwnerID != currentUser.ID {
		log.Printf("⚠️ SECURITY ALERT: User %s tried to fetch shop detail parameters for %s owned by %s", currentUser.ID, shopID, shop.OwnerID)
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "forbidden: access denied to view this shop dashboard context",
			Extensions: map[string]interface{}{"code": "FORBIDDEN"},
		})
		return nil, nil
	}

	// Initialize structural payload containers to prevent nil pointer encoding memory exceptions
	shop.Verification = &model.Verification{}
	shop.ContactDetails = &model.ContactDetails{}
	shop.Status = &model.ShopStatus{}
	shop.Coordinates = &model.Coordinates{}
	shop.BusinessHours = &model.BusinessHours{}
	shop.PaymentMethods = &model.PaymentMethods{}
	shop.Delivery = &model.DeliveryOptions{}
	shop.SocialMedia = &model.SocialMedia{}

	// Safely decode JSON buffers straight back into your model layouts
	_ = json.Unmarshal(verificationBytes, shop.Verification)
	_ = json.Unmarshal(contactBytes, shop.ContactDetails)
	_ = json.Unmarshal(statusBytes, shop.Status)
	_ = json.Unmarshal(coordinatesBytes, shop.Coordinates)
	_ = json.Unmarshal(hoursBytes, shop.BusinessHours)
	_ = json.Unmarshal(paymentsBytes, shop.PaymentMethods)
	_ = json.Unmarshal(deliveryBytes, shop.Delivery)
	_ = json.Unmarshal(socialBytes, shop.SocialMedia)

	shop.CreatedAt = createdAt.Format(time.RFC3339)

	return &shop, nil
}

// GetShopInventory is the resolver for the getShopInventory field.
func (r *queryResolver) GetShopInventory(ctx context.Context, shopID string, limit int, offset int, search *string, sortBy *string, sortOrder *string) (*model.PaginatedOwnerInventory, error) {
	// SECURITY GUARD 1: Is user logged in?
	currentUser := ctx.Value("currentUser").(middleware.CachedUser)

	// SECURITY GUARD 2: Verify the caller is the actual owner of the shop before pulling internal records
	var shopOwnerID string
	checkQuery := "SELECT owner_id FROM shops WHERE id = $1 AND deleted_at IS NULL LIMIT 1"
	err := r.Resolver.DB.QueryRow(ctx, checkQuery, shopID).Scan(&shopOwnerID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			graphql.AddError(ctx, &gqlerror.Error{
				Message:    "not found: target shop resource does not exist",
				Extensions: map[string]interface{}{"code": "NOT_FOUND"},
			})
			return nil, nil
		}
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "internal server error: ownership confirmation failure",
			Extensions: map[string]interface{}{"code": "INTERNAL_SERVER_ERROR"},
		})
		return nil, nil
	}

	// Block operation if the logged-in user doesn't own this shop
	if shopOwnerID != currentUser.ID {
		log.Printf("⚠️ SECURITY ALERT: User %s tried to view internal inventory records for shop %s owned by user %s", currentUser.ID, shopID, shopOwnerID)
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "forbidden: access denied to view inventory metrics",
			Extensions: map[string]interface{}{"code": "FORBIDDEN"},
		})
		return nil, nil
	}

	// Build WHERE clause with search filter - 🚀 ADDED AND deleted_at IS NULL
	whereClause := "WHERE shop_id = $1 AND deleted_at IS NULL"
	args := []interface{}{shopID}
	argIndex := 2

	if search != nil && *search != "" {
		// Keep using the same argIndex ($2) for all fields
		whereClause += fmt.Sprintf(" AND (item_name ILIKE $%d OR description ILIKE $%d OR category ILIKE $%d OR barcode ILIKE $%d)", argIndex, argIndex, argIndex, argIndex)
		// ✅ FIX: Only append the search pattern ONCE to match the single index
		searchPattern := "%" + *search + "%"
		args = append(args, searchPattern)
		argIndex++ // Now argIndex moves to 3 for the LIMIT/OFFSET variables later
	}

	// 1. Fetch total item count with search applied
	countQuery := "SELECT COUNT(*) FROM inventory_items " + whereClause
	var totalCount int64
	err = r.Resolver.DB.QueryRow(ctx, countQuery, args...).Scan(&totalCount)
	if err != nil {
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "internal server error: analytical tracking aggregation failure",
			Extensions: map[string]interface{}{"code": "INTERNAL_SERVER_ERROR"},
		})
		return nil, nil
	}

	// Determine sort column and order
	sortColumn := "item_name"
	sortDirection := "ASC"
	if sortBy != nil && *sortBy != "" {
		// Whitelist valid columns to prevent SQL injection
		validColumns := map[string]bool{
			"item_name":      true,
			"category":       true,
			"selling_price":  true,
			"stock_quantity": true,
			"cost_price":     true,
			"updated_at":     true,
		}
		if validColumns[*sortBy] {
			sortColumn = *sortBy
		}
	}
	if sortOrder != nil && *sortOrder != "" {
		if *sortOrder == "DESC" {
			sortDirection = "DESC"
		}
	}

	// 2. Fetch complete list including sensitive details (cost_price, reorder_level)
	selectQuery := fmt.Sprintf(`
		SELECT id, shop_id, item_name, description, barcode, category, unit_of_measure, photo, cost_price, selling_price, stock_quantity, reorder_level, updated_at
		FROM inventory_items
		%s
		ORDER BY %s %s
		LIMIT $%d OFFSET $%d
	`, whereClause, sortColumn, sortDirection, argIndex, argIndex+1)

	args = append(args, limit, offset)
	rows, err := r.Resolver.DB.Query(ctx, selectQuery, args...)
	if err != nil {
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "internal server error: collection retrieval failure",
			Extensions: map[string]interface{}{"code": "INTERNAL_SERVER_ERROR"},
		})
		return nil, nil
	}
	defer rows.Close()

	var items []*model.OwnerInventoryItem
	for rows.Next() {
		var item model.OwnerInventoryItem
		var updatedAt time.Time
		err := rows.Scan(
			&item.ID, &item.ShopID, &item.ItemName, &item.Description, &item.Barcode, &item.Category, &item.UnitOfMeasure, &item.Photo,
			&item.CostPrice, &item.SellingPrice, &item.StockQuantity, &item.ReorderLevel, &updatedAt,
		)
		if err != nil {
			graphql.AddError(ctx, &gqlerror.Error{
				Message:    "internal server error: data decoding anomaly",
				Extensions: map[string]interface{}{"code": "INTERNAL_SERVER_ERROR"},
			})
			return nil, nil
		}
		item.UpdatedAt = updatedAt.Format(time.RFC3339)
		items = append(items, &item)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	hasNextPage := int64(offset+limit) < totalCount
	return &model.PaginatedOwnerInventory{
		Items:       items,
		TotalCount:  int(totalCount),
		HasNextPage: hasNextPage,
	}, nil
}

// GetCheckoutHistory is the resolver for the getCheckoutHistory field.
func (r *queryResolver) GetCheckoutHistory(ctx context.Context, shopID string, limit int, offset int) (*model.PaginatedCheckoutBatches, error) {
	currentUser := ctx.Value("currentUser").(middleware.CachedUser)
	if err := utils.EnsureShopOwnership(ctx, r.Resolver.DB, shopID, currentUser.ID); err != nil {
		utils.AddHistoryGraphQLError(ctx, err)
		return nil, nil
	}

	var totalCount int64
	err := r.Resolver.DB.QueryRow(ctx, "SELECT COUNT(*) FROM checkout_batches WHERE shop_id = $1", shopID).Scan(&totalCount)
	if err != nil {
		graphql.AddError(ctx, &gqlerror.Error{Message: "internal server error: checkout history count failure", Extensions: map[string]interface{}{"code": "INTERNAL_SERVER_ERROR"}})
		return nil, nil
	}

	rows, err := r.Resolver.DB.Query(ctx, `
		SELECT id, shop_id, sold_at, total_items, total_cost, gross_sale, gross_profit
		FROM checkout_batches
		WHERE shop_id = $1
		ORDER BY sold_at DESC
		LIMIT $2 OFFSET $3
	`, shopID, limit, offset)
	if err != nil {
		graphql.AddError(ctx, &gqlerror.Error{Message: "internal server error: checkout history retrieval failure", Extensions: map[string]interface{}{"code": "INTERNAL_SERVER_ERROR"}})
		return nil, nil
	}
	defer rows.Close()

	batches := []*model.CheckoutBatch{}
	for rows.Next() {
		var batch model.CheckoutBatch
		var soldAt time.Time
		if err := rows.Scan(&batch.ID, &batch.ShopID, &soldAt, &batch.TotalItems, &batch.TotalCost, &batch.GrossSale, &batch.GrossProfit); err != nil {
			log.Printf("checkout history decode failure: %v", err)
			graphql.AddError(ctx, &gqlerror.Error{Message: "internal server error: checkout history decode failure", Extensions: map[string]interface{}{"code": "INTERNAL_SERVER_ERROR"}})
			return nil, nil
		}
		batch.SoldAt = soldAt.Format(time.RFC3339)

		itemRows, err := r.Resolver.DB.Query(ctx, `
			SELECT id, inventory_item_id, item_name, quantity, cost_price, selling_price, line_cost_total, line_sale_total
			FROM checkout_batch_items
			WHERE checkout_batch_id = $1
			ORDER BY item_name ASC
		`, batch.ID)
		if err != nil {
			graphql.AddError(ctx, &gqlerror.Error{Message: "internal server error: checkout item history retrieval failure", Extensions: map[string]interface{}{"code": "INTERNAL_SERVER_ERROR"}})
			return nil, nil
		}

		items := []*model.CheckoutBatchItem{}
		for itemRows.Next() {
			var item model.CheckoutBatchItem
			if err := itemRows.Scan(&item.ID, &item.InventoryItemID, &item.ItemName, &item.Quantity, &item.CostPrice, &item.SellingPrice, &item.LineCostTotal, &item.LineSaleTotal); err != nil {
				itemRows.Close()
				log.Printf("checkout item history decode failure: %v", err)
				graphql.AddError(ctx, &gqlerror.Error{Message: "internal server error: checkout item history decode failure", Extensions: map[string]interface{}{"code": "INTERNAL_SERVER_ERROR"}})
				return nil, nil
			}
			items = append(items, &item)
		}
		itemRows.Close()
		batch.Items = items
		batches = append(batches, &batch)
	}

	return &model.PaginatedCheckoutBatches{
		Batches:     batches,
		TotalCount:  int(totalCount),
		HasNextPage: int64(offset+limit) < totalCount,
	}, nil
}

// GetItemActionHistory is the resolver for the getItemActionHistory field.
func (r *queryResolver) GetItemActionHistory(ctx context.Context, shopID string, limit int, offset int) (*model.PaginatedItemActionHistory, error) {
	currentUser := ctx.Value("currentUser").(middleware.CachedUser)
	if err := utils.EnsureShopOwnership(ctx, r.Resolver.DB, shopID, currentUser.ID); err != nil {
		utils.AddHistoryGraphQLError(ctx, err)
		return nil, nil
	}

	var totalCount int64
	err := r.Resolver.DB.QueryRow(ctx, "SELECT COUNT(*) FROM item_action_history WHERE shop_id = $1", shopID).Scan(&totalCount)
	if err != nil {
		graphql.AddError(ctx, &gqlerror.Error{Message: "internal server error: item history count failure", Extensions: map[string]interface{}{"code": "INTERNAL_SERVER_ERROR"}})
		return nil, nil
	}

	rows, err := r.Resolver.DB.Query(ctx, `
		SELECT id, shop_id, inventory_item_id, item_name, action, quantity, created_at
		FROM item_action_history
		WHERE shop_id = $1
		ORDER BY created_at DESC
		LIMIT $2 OFFSET $3
	`, shopID, limit, offset)
	if err != nil {
		graphql.AddError(ctx, &gqlerror.Error{Message: "internal server error: item history retrieval failure", Extensions: map[string]interface{}{"code": "INTERNAL_SERVER_ERROR"}})
		return nil, nil
	}
	defer rows.Close()

	records := []*model.ItemActionHistory{}
	for rows.Next() {
		var record model.ItemActionHistory
		var createdAt time.Time
		if err := rows.Scan(&record.ID, &record.ShopID, &record.InventoryItemID, &record.ItemName, &record.Action, &record.Quantity, &createdAt); err != nil {
			log.Printf("item history decode failure: %v", err)
			graphql.AddError(ctx, &gqlerror.Error{Message: "internal server error: item history decode failure", Extensions: map[string]interface{}{"code": "INTERNAL_SERVER_ERROR"}})
			return nil, nil
		}
		record.Date = createdAt.Format(time.RFC3339)
		records = append(records, &record)
	}

	return &model.PaginatedItemActionHistory{
		Records:     records,
		TotalCount:  int(totalCount),
		HasNextPage: int64(offset+limit) < totalCount,
	}, nil
}

// SearchShop is the resolver for the searchShop field.
func (r *queryResolver) SearchShop(ctx context.Context, query string, limit int, offset int) (*model.PaginatedShops, error) {
	// 1. Get total record count matching search parameter - 🚀 ADDED AND deleted_at IS NULL
	var totalCount int64
	countQuery := "SELECT COUNT(*) FROM shops WHERE (shop_name ILIKE $1 OR address ILIKE $1) AND deleted_at IS NULL"
	searchPattern := "%" + query + "%"
	err := r.Resolver.DB.QueryRow(ctx, countQuery, searchPattern).Scan(&totalCount)
	if err != nil {
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "internal server error: store search aggregation failure",
			Extensions: map[string]interface{}{"code": "INTERNAL_SERVER_ERROR"},
		})
		return nil, nil
	}

	// 2. Fetch the paginated public subset (No ownerId column requested) - 🚀 ADDED AND deleted_at IS NULL
	selectQuery := `
		SELECT id, shop_name, address, description, photo, photos, created_at, 
		       verification, contact_details, status, coordinates, business_hours, payment_methods, delivery, social_media
		FROM shops
		WHERE (shop_name ILIKE $1 OR address ILIKE $1) AND deleted_at IS NULL
		ORDER BY shop_name ASC
		LIMIT $2 OFFSET $3
	`
	rows, err := r.Resolver.DB.Query(ctx, selectQuery, searchPattern, limit, offset)
	if err != nil {
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "internal server error: store collection search failure",
			Extensions: map[string]interface{}{"code": "INTERNAL_SERVER_ERROR"},
		})
		return nil, nil
	}
	defer rows.Close()

	var shops []*model.Shop
	for rows.Next() {
		var shop model.Shop
		var createdAt time.Time

		// Allocate temporary raw byte buffers to hold JSONB structures from PostgreSQL columns
		var verificationBytes []byte
		var contactBytes []byte
		var statusBytes []byte
		var coordinatesBytes []byte
		var hoursBytes []byte
		var paymentsBytes []byte
		var deliveryBytes []byte
		var socialBytes []byte

		// Scan all 15 columns perfectly 1-to-1 matching position order
		err := rows.Scan(
			&shop.ID, &shop.ShopName, &shop.Address, &shop.Description, &shop.Photo, &shop.Photos, &createdAt,
			&verificationBytes, &contactBytes, &statusBytes, &coordinatesBytes, &hoursBytes, &paymentsBytes, &deliveryBytes, &socialBytes,
		)
		if err != nil {
			log.Printf("🔴 Public search rows scan decoding anomaly details: %v", err)
			graphql.AddError(ctx, &gqlerror.Error{
				Message:    "internal server error: data rendering exception",
				Extensions: map[string]interface{}{"code": "INTERNAL_SERVER_ERROR"},
			})
			return nil, nil
		}

		// Initialize structural payload containers to prevent nil pointer encoding memory exceptions
		shop.Verification = &model.Verification{}
		shop.ContactDetails = &model.ContactDetails{}
		shop.Status = &model.ShopStatus{}
		shop.Coordinates = &model.Coordinates{}
		shop.BusinessHours = &model.BusinessHours{}
		shop.PaymentMethods = &model.PaymentMethods{}
		shop.Delivery = &model.DeliveryOptions{}
		shop.SocialMedia = &model.SocialMedia{}

		// Safely decode JSON buffers straight back into your model layouts
		_ = json.Unmarshal(verificationBytes, shop.Verification)
		_ = json.Unmarshal(contactBytes, shop.ContactDetails)
		_ = json.Unmarshal(statusBytes, shop.Status)
		_ = json.Unmarshal(coordinatesBytes, shop.Coordinates)
		_ = json.Unmarshal(hoursBytes, shop.BusinessHours)
		_ = json.Unmarshal(paymentsBytes, shop.PaymentMethods)
		_ = json.Unmarshal(deliveryBytes, shop.Delivery)
		_ = json.Unmarshal(socialBytes, shop.SocialMedia)

		// Initialize reviews as empty slice to avoid frontend nil panics
		shop.Reviews = []*model.ShopReview{}
		shop.CreatedAt = createdAt.Format(time.RFC3339)
		shops = append(shops, &shop)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	hasNextPage := int64(offset+limit) < totalCount
	return &model.PaginatedShops{
		Shops:       shops,
		TotalCount:  int(totalCount),
		HasNextPage: hasNextPage,
	}, nil
}

// SearchProduct is the resolver for the searchProduct field.
func (r *queryResolver) SearchProduct(ctx context.Context, query string, limit int, offset int) (*model.PaginatedPublicProducts, error) {
	// 1. Get total items matching item name or category string - 🚀 ADDED AND deleted_at IS NULL
	var totalCount int64
	countQuery := "SELECT COUNT(*) FROM inventory_items WHERE (item_name ILIKE $1 OR category ILIKE $1) AND deleted_at IS NULL"
	searchPattern := "%" + query + "%"
	err := r.Resolver.DB.QueryRow(ctx, countQuery, searchPattern).Scan(&totalCount)
	if err != nil {
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "internal server error: product search count failure",
			Extensions: map[string]interface{}{"code": "INTERNAL_SERVER_ERROR"},
		})
		return nil, nil
	}

	// 2. Fetch public fields only - 🚀 ADDED AND deleted_at IS NULL
	selectQuery := `
		SELECT id, shop_id, item_name, description, category, unit_of_measure, photo, selling_price, stock_quantity 
		FROM inventory_items 
		WHERE (item_name ILIKE $1 OR category ILIKE $1) AND deleted_at IS NULL
		ORDER BY item_name ASC 
		LIMIT $2 OFFSET $3
	`
	rows, err := r.Resolver.DB.Query(ctx, selectQuery, searchPattern, limit, offset)
	if err != nil {
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "internal server error: product collection search failure",
			Extensions: map[string]interface{}{"code": "INTERNAL_SERVER_ERROR"},
		})
		return nil, nil
	}
	defer rows.Close()

	var products []*model.PublicProduct
	for rows.Next() {
		var prod model.PublicProduct
		err := rows.Scan(
			&prod.ID,
			&prod.ShopID,
			&prod.ItemName,
			&prod.Description,
			&prod.Category,
			&prod.UnitOfMeasure,
			&prod.Photo,
			&prod.SellingPrice,
			&prod.StockQuantity,
		)
		if err != nil {
			graphql.AddError(ctx, &gqlerror.Error{
				Message:    "internal server error: item decoding failure",
				Extensions: map[string]interface{}{"code": "INTERNAL_SERVER_ERROR"},
			})
			return nil, nil
		}
		products = append(products, &prod)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	hasNextPage := int64(offset+limit) < totalCount
	return &model.PaginatedPublicProducts{
		Products:    products,
		TotalCount:  int(totalCount),
		HasNextPage: hasNextPage,
	}, nil
}

// SearchShopProducts is the resolver for the searchShopProducts field.
func (r *queryResolver) SearchShopProducts(ctx context.Context, shopID string, query string, limit int, offset int) (*model.PaginatedPublicProducts, error) {
	// 1. Get total items matching item name or category string within a specific shop - 🚀 ADDED AND deleted_at IS NULL
	var totalCount int64
	countQuery := "SELECT COUNT(*) FROM inventory_items WHERE shop_id = $1 AND (item_name ILIKE $2 OR category ILIKE $2) AND deleted_at IS NULL"
	searchPattern := "%" + query + "%"
	err := r.Resolver.DB.QueryRow(ctx, countQuery, shopID, searchPattern).Scan(&totalCount)
	if err != nil {
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "internal server error: shop product search count failure",
			Extensions: map[string]interface{}{"code": "INTERNAL_SERVER_ERROR"},
		})
		return nil, nil
	}

	// 2. Fetch public fields only from the specific shop - 🚀 ADDED AND deleted_at IS NULL
	selectQuery := `
		SELECT id, shop_id, item_name, description, category, unit_of_measure, photo, selling_price, stock_quantity 
		FROM inventory_items 
		WHERE shop_id = $1 AND (item_name ILIKE $2 OR category ILIKE $2) AND deleted_at IS NULL
		ORDER BY item_name ASC 
		LIMIT $3 OFFSET $4
	`
	rows, err := r.Resolver.DB.Query(ctx, selectQuery, shopID, searchPattern, limit, offset)
	if err != nil {
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "internal server error: shop product collection search failure",
			Extensions: map[string]interface{}{"code": "INTERNAL_SERVER_ERROR"},
		})
		return nil, nil
	}
	defer rows.Close()

	var products []*model.PublicProduct
	for rows.Next() {
		var prod model.PublicProduct
		err := rows.Scan(
			&prod.ID,
			&prod.ShopID,
			&prod.ItemName,
			&prod.Description,
			&prod.Category,
			&prod.UnitOfMeasure,
			&prod.Photo,
			&prod.SellingPrice,
			&prod.StockQuantity,
		)
		if err != nil {
			graphql.AddError(ctx, &gqlerror.Error{
				Message:    "internal server error: shop item decoding failure",
				Extensions: map[string]interface{}{"code": "INTERNAL_SERVER_ERROR"},
			})
			return nil, nil
		}
		products = append(products, &prod)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	hasNextPage := int64(offset+limit) < totalCount
	return &model.PaginatedPublicProducts{
		Products:    products,
		TotalCount:  int(totalCount),
		HasNextPage: hasNextPage,
	}, nil
}

// GetShopDashboardMetrics is the resolver for the getShopDashboardMetrics field.
func (r *queryResolver) GetShopDashboardMetrics(ctx context.Context, shopID string) (*model.ShopDashboardMetrics, error) {
	// 1. SECURITY & AUTHN GATE
	currentUser, ok := ctx.Value("currentUser").(middleware.CachedUser)
	if !ok {
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "unauthorized: invalid authentication footprint",
			Extensions: map[string]interface{}{"code": "UNAUTHORIZED"},
		})
		return nil, nil
	}

	// Verify the caller is the actual owner of the shop before executing intensive analytical scans
	if err := utils.EnsureShopOwnership(ctx, r.Resolver.DB, shopID, currentUser.ID); err != nil {
		utils.AddHistoryGraphQLError(ctx, err)
		return nil, nil
	}

	var metrics model.ShopDashboardMetrics

	// 2. WIDGET 1 & 2: CALCULATE TODAY'S GROSS SALES & GROWTH RATE VS SAME DAY LAST WEEK
	// Compares today's running sales total to what was made during the exact same period 7 days ago.
	salesQuery := `
		WITH metrics_today AS (
			SELECT COALESCE(SUM(gross_sale), 0.0) as sales
			FROM checkout_batches 
			WHERE shop_id = $1 AND sold_at::timestamp >= CURRENT_DATE
		),
		metrics_last_week AS (
			SELECT COALESCE(SUM(gross_sale), 0.0) as sales
			FROM checkout_batches 
			WHERE shop_id = $1 
			  AND sold_at::timestamp >= CURRENT_DATE - INTERVAL '7 days'
			  AND sold_at::timestamp < CURRENT_DATE - INTERVAL '6 days'
		)
		SELECT t.sales, 
		       CASE WHEN l.sales = 0 THEN 0.0 ELSE ((t.sales - l.sales) / l.sales) * 100.0 END
		FROM metrics_today t, metrics_last_week l;
	`
	err := r.Resolver.DB.QueryRow(ctx, salesQuery, shopID).Scan(
		&metrics.TodaysGrossSales,
		&metrics.TodaysSalesGrowthPct,
	)
	if err != nil {
		log.Printf("Error calculating daily revenue snapshot: %v", err)
		graphql.AddError(ctx, &gqlerror.Error{Message: "internal server error: revenue aggregation failure", Extensions: map[string]interface{}{"code": "INTERNAL_SERVER_ERROR"}})
		return nil, nil
	}

	// 3. WIDGET 3: WEEKLY REVENUE GROWTH INDEX (This week vs Previous week)
	// Balance Score metric. 100 means the store perfectly matched last week's raw performance.
	weeklyQuery := `
		WITH current_7_days AS (
			SELECT COALESCE(SUM(gross_sale), 0.0) as total 
			FROM checkout_batches 
			WHERE shop_id = $1 AND sold_at::timestamp >= NOW() - INTERVAL '7 days'
		),
		previous_7_days AS (
			SELECT COALESCE(SUM(gross_sale), 0.0) as total 
			FROM checkout_batches 
			WHERE shop_id = $1 
			  AND sold_at::timestamp >= NOW() - INTERVAL '14 days' 
			  AND sold_at::timestamp < NOW() - INTERVAL '7 days'
		)
		SELECT CASE WHEN p.total = 0 THEN 100.0 ELSE (c.total / p.total) * 100.0 END
		FROM current_7_days c, previous_7_days p;
	`
	err = r.Resolver.DB.QueryRow(ctx, weeklyQuery, shopID).Scan(&metrics.WeeklyRevenueGrowthIndex)
	if err != nil {
		log.Printf("Error calculating weekly revenue index: %v", err)
		graphql.AddError(ctx, &gqlerror.Error{Message: "internal server error: weekly trend compilation anomaly", Extensions: map[string]interface{}{"code": "INTERNAL_SERVER_ERROR"}})
		return nil, nil
	}

	// 4. WIDGET 4: AVERAGE TICKET SIZE (AOV)
	// Calculates the average monetary transaction value passing through registers.
	aovQuery := `
		SELECT COALESCE(AVG(gross_sale), 0.0) 
		FROM checkout_batches 
		WHERE shop_id = $1;
	`
	err = r.Resolver.DB.QueryRow(ctx, aovQuery, shopID).Scan(&metrics.AverageTicketSize)
	if err != nil {
		log.Printf("Error calculating average basket tickets: %v", err)
		graphql.AddError(ctx, &gqlerror.Error{Message: "internal server error: ticket computation anomaly", Extensions: map[string]interface{}{"code": "INTERNAL_SERVER_ERROR"}})
		return nil, nil
	}

	// 5. WIDGET 5: INVENTORY CAPITAL RATIO (Wholesale Cost vs Retail Value realization)
	// Tracks how much capital liquidity is frozen in shelf stocks.
	capitalQuery := `
		SELECT 
			CASE 
				WHEN SUM(selling_price * stock_quantity) = 0 THEN 0.0
				ELSE (SUM(cost_price * stock_quantity) / SUM(selling_price * stock_quantity)) * 100.0 
			END
		FROM inventory_items
		WHERE shop_id = $1;
	`
	err = r.Resolver.DB.QueryRow(ctx, capitalQuery, shopID).Scan(&metrics.InventoryCapitalRatio)
	if err != nil {
		log.Printf("Error calculating capital realization parameters: %v", err)
		graphql.AddError(ctx, &gqlerror.Error{Message: "internal server error: resource analysis failure", Extensions: map[string]interface{}{"code": "INTERNAL_SERVER_ERROR"}})
		return nil, nil
	}

	// 6. WIDGET 6: PAST 7-DAY SALES HISTORY TREND ENGINE
	// Generates a recursive calendar series sequence to output historical values or zero states.
	trendQuery := `
		WITH RECURSIVE days AS (
			SELECT CURRENT_DATE - INTERVAL '6 days' AS calendar_day
			UNION ALL
			SELECT calendar_day + INTERVAL '1 day'
			FROM days
			WHERE calendar_day < CURRENT_DATE
		),
		daily_sales AS (
			SELECT 
				sold_at::date AS sales_day,
				COALESCE(SUM(gross_sale), 0.0) AS total_sales,
				COALESCE(SUM(gross_profit), 0.0) AS total_profit
			FROM checkout_batches
			WHERE shop_id = $1 AND sold_at::timestamp >= CURRENT_DATE - INTERVAL '6 days'
			GROUP BY sales_day
		)
		SELECT 
			TO_CHAR(d.calendar_day, 'Dy') AS day_name,
			TO_CHAR(d.calendar_day, 'MM/DD') AS formatted_date,
			COALESCE(s.total_sales, 0.0) AS gross_sale,
			COALESCE(s.total_profit, 0.0) AS gross_profit
		FROM days d
		LEFT JOIN daily_sales s ON d.calendar_day = s.sales_day
		ORDER BY d.calendar_day ASC;
	`
	rows, err := r.Resolver.DB.Query(ctx, trendQuery, shopID)
	if err != nil {
		log.Printf("Weekly chart matrix extraction failure: %v", err)
		graphql.AddError(ctx, &gqlerror.Error{Message: "internal server error: weekly trend compilation failure", Extensions: map[string]interface{}{"code": "INTERNAL_SERVER_ERROR"}})
		return nil, nil
	}
	defer rows.Close()

	var weeklySalesTrend []*model.DailySalesMetric
	for rows.Next() {
		var dayMetric model.DailySalesMetric
		err := rows.Scan(
			&dayMetric.DayName,
			&dayMetric.FormattedDate,
			&dayMetric.GrossSale,
			&dayMetric.GrossProfit,
		)
		if err != nil {
			log.Printf("Error decoding weekly trend data frames: %v", err)
			return nil, err
		}
		weeklySalesTrend = append(weeklySalesTrend, &dayMetric)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	metrics.WeeklySalesTrend = weeklySalesTrend

	return &metrics, nil
}
