package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"go-backend/internal/graph/model"
	"go-backend/internal/middleware"
	imageutil "go-backend/internal/utils"
	"log"
	"os"
	"time"

	"github.com/99designs/gqlgen/graphql"
	pgx "github.com/jackc/pgx/v5"
	"github.com/vektah/gqlparser/v2/gqlerror"
)

// CreateShop is the resolver for the createShop field.
func (r *mutationResolver) CreateShop(ctx context.Context, input model.CreateShopInput) (*model.OwnerShop, error) {
	// SECURITY GUARD: Enforce valid user identity state from Redis session
	currentUser := ctx.Value("currentUser").(middleware.CachedUser)

	// 1. INITIALIZE IMAGE UPLOADER WITH THE BASE PATH
	uploader, err := imageutil.NewImageUploader(
		os.Getenv("CLOUDINARY_CLOUD_NAME"),
		os.Getenv("CLOUDINARY_API_KEY"),
		os.Getenv("CLOUDINARY_API_SECRET"),
		os.Getenv("CLOUDINARY_FOLDER"),
	)
	if err != nil {
		log.Printf("🔴 FAILED TO INITIALIZE CLOUDINARY UPLOADER: %v", err)
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "internal server error: media processing failure",
			Extensions: map[string]any{"code": "INTERNAL_SERVER_ERROR"},
		})
		return nil, nil
	}
	if err != nil {
		log.Printf("🔴 FAILED TO INITIALIZE CLOUDINARY UPLOADER: %v", err)
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "internal server error: media processing failure",
			Extensions: map[string]any{"code": "INTERNAL_SERVER_ERROR"},
		})
		return nil, nil
	}

	// Dynamic target isolation mapping: /userId/shops
	uploadFolder := fmt.Sprintf("%s/%s/shops", os.Getenv("CLOUDINARY_FOLDER"), currentUser.ID)
	shopUploader := uploader.WithFolder(uploadFolder)

	// 2. UPLOAD PRIMARY LOGO/BANNER TO USER'S SHOPS CONTAINER
	finalPrimaryPhoto := ""
	if input.Photo != nil && input.Photo.File != nil {
		result, err := shopUploader.UploadImage(ctx, input.Photo.File, input.Photo.Filename)
		if err == nil {
			finalPrimaryPhoto = result.URL
		} else {
			log.Printf("⚠️ Primary photo upload failed: %v", err)
		}
	}

	// 3. STREAM MULTIPLE CAROUSEL GALLERY SLICES INDEPENDENTLY
	var finalPhotosSlice []string = []string{}
	for _, upload := range input.Photos {
		if upload != nil && upload.File != nil {
			result, err := shopUploader.UploadImage(ctx, upload.File, upload.Filename)
			if err != nil {
				log.Printf("⚠️ Additional photo slice failed to upload: %v", err)
				continue // Gracefully skip failed slice tracks
			}
			finalPhotosSlice = append(finalPhotosSlice, result.URL)
		}
	}

	// Marshal dynamic user configuration properties to structural JSON strings
	hoursJSON, _ := json.Marshal(input.BusinessHours)
	paymentsJSON, _ := json.Marshal(input.PaymentMethods)
	deliveryJSON, _ := json.Marshal(input.Delivery)
	socialJSON, _ := json.Marshal(input.SocialMedia)
	contactJSON, _ := json.Marshal(input.ContactDetails)
	coordinatesJSON, _ := json.Marshal(input.Coordinates)

	statusJSON, _ := json.Marshal(map[string]any{"isActive": true})
	verificationJSON, _ := json.Marshal(map[string]any{"isVerified": false, "verifiedDate": nil, "verificationId": ""})

	// 4. RETRIEVE ID VALUES STRAIGHT FROM POSTGRESQL DEFAULT SEQUENCES
	query := `
		INSERT INTO shops (
			shop_name, address, description, photo, photos, owner_id, created_at,
			business_hours, payment_methods, delivery, social_media, contact_details,
			coordinates, status, verification
		) 
		VALUES ($1, $2, $3, $4, $5, $6, NOW(), $7, $8, $9, $10, $11, $12, $13, $14) 
		RETURNING id, created_at
	`
	var insertedID string
	var createdAt time.Time

	// Execute storage bindings including newly obtained secure asset links
	err = r.Resolver.DB.QueryRow(ctx, query,
		input.ShopName,    // $1
		input.Address,     // $2
		input.Description, // $3
		finalPrimaryPhoto, // $4 <-- Saved secure string URL path reference
		finalPhotosSlice,  // $5 <-- Saved string array paths references
		currentUser.ID,    // $6
		hoursJSON,         // $7
		paymentsJSON,      // $8
		deliveryJSON,      // $9
		socialJSON,        // $10
		contactJSON,       // $11
		coordinatesJSON,   // $12
		statusJSON,        // $13
		verificationJSON,  // $14
	).Scan(&insertedID, &createdAt)

	if err != nil {
		log.Printf("🔴 DATABASE TRANSACTION FAILED IN CREATESHOP: %v", err)
		graphql.AddError(ctx, &gqlerror.Error{
			Message: "internal server error: failed to create shop entry",
			Extensions: map[string]any{
				"code": "INTERNAL_SERVER_ERROR",
			},
		})
		return nil, nil
	}

	// 5. MAP PERSISTED PARAMS TO SYSTEM REPRESENTATION INTERFACES
	return &model.OwnerShop{
		ID:          insertedID, // Uses native ID from SQL table schema
		OwnerID:     currentUser.ID,
		ShopName:    input.ShopName,
		Address:     input.Address,
		Description: input.Description,
		Photo:       &finalPrimaryPhoto,
		Photos:      finalPhotosSlice,
		CreatedAt:   createdAt.Format(time.RFC3339),
		Coordinates: &model.Coordinates{
			Lat: input.Coordinates.Lat,
			Lng: input.Coordinates.Lng,
		},
		BusinessHours: &model.BusinessHours{
			OpenTime:  input.BusinessHours.OpenTime,
			CloseTime: input.BusinessHours.CloseTime,
			Days:      input.BusinessHours.Days,
		},
		PaymentMethods: &model.PaymentMethods{
			Cash:    input.PaymentMethods.Cash,
			Gcash:   input.PaymentMethods.Gcash,
			Paymaya: input.PaymentMethods.Paymaya,
			Card:    input.PaymentMethods.Card,
		},
		Delivery: &model.DeliveryOptions{
			Available: input.Delivery.Available,
			Radius:    input.Delivery.Radius,
			Fee:       input.Delivery.Fee,
			MinOrder:  input.Delivery.MinOrder,
		},
		SocialMedia: &model.SocialMedia{
			Facebook:  input.SocialMedia.Facebook,
			Instagram: input.SocialMedia.Instagram,
		},
		ContactDetails: &model.ContactDetails{
			Phone:   input.ContactDetails.Phone,
			Email:   input.ContactDetails.Email,
			Address: input.ContactDetails.Address,
		},
		Status: &model.ShopStatus{
			IsActive: true,
		},
		Verification: &model.Verification{
			IsVerified: false,
		},
	}, nil
}

// UpdateShop is the resolver for the updateShop field.
func (r *mutationResolver) UpdateShop(ctx context.Context, input model.UpdateShopInput) (*model.OwnerShop, error) {
	// SECURITY GUARD 1: Is user logged in?
	currentUser := ctx.Value("currentUser").(middleware.CachedUser)

	// SECURITY GUARD 2: Fetch current database values to compare against
	var dbOwnerID string
	var verificationJSON []byte
	var statusJSON []byte
	var oldPrimaryPhoto *string
	var oldPhotosSlice []string

	checkQuery := "SELECT owner_id, status, verification, photo, photos FROM shops WHERE id = $1 LIMIT 1"
	err := r.Resolver.DB.QueryRow(ctx, checkQuery, input.ShopID).Scan(
		&dbOwnerID,
		&statusJSON,
		&verificationJSON,
		&oldPrimaryPhoto,
		&oldPhotosSlice,
	)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			graphql.AddError(ctx, &gqlerror.Error{
				Message:    "not found: target shop resource does not exist",
				Extensions: map[string]interface{}{"code": "NOT_FOUND"},
			})
			return nil, nil
		}
		return nil, err
	}

	if dbOwnerID != currentUser.ID {
		log.Printf("⚠️ SECURITY ALERT: User %s tried to mutate shop %s owned by %s", currentUser.ID, input.ShopID, dbOwnerID)
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "forbidden: you do not have permission to edit this shop",
			Extensions: map[string]interface{}{"code": "FORBIDDEN"},
		})
		return nil, nil
	}

	// INITIALIZE THE CLOUDINARY UPLOADER UTILITY
	uploader, err := imageutil.NewImageUploader(
		os.Getenv("CLOUDINARY_CLOUD_NAME"),
		os.Getenv("CLOUDINARY_API_KEY"),
		os.Getenv("CLOUDINARY_API_SECRET"),
		os.Getenv("CLOUDINARY_FOLDER"),
	)

	if err != nil {
		log.Printf("🔴 FAILED TO INITIALIZE CLOUDINARY UPLOADER IN UPDATESHOP: %v", err)
		return nil, fmt.Errorf("media processor error")
	}

	uploadFolder := fmt.Sprintf("%s/%s/shops", os.Getenv("CLOUDINARY_FOLDER"), currentUser.ID)
	shopUploader := uploader.WithFolder(uploadFolder)

	// =========================================================================
	// 1. BACKEND COMPARISON FOR PRIMARY PHOTO
	// =========================================================================
	finalPrimaryPhoto := ""
	if oldPrimaryPhoto != nil {
		finalPrimaryPhoto = *oldPrimaryPhoto
	}

	if input.Photo != nil && input.Photo.File != nil {
		// Rule: New file is different from the DB. Delete the old asset from Cloudinary.
		if oldPrimaryPhoto != nil && *oldPrimaryPhoto != "" {
			if cleanErr := shopUploader.DeleteImageByURL(ctx, *oldPrimaryPhoto); cleanErr != nil {
				log.Printf("⚠️ Failed to delete overwritten primary image: %v", cleanErr)
			}
		}

		// Upload the new replacement image
		result, uploadErr := shopUploader.UploadImage(ctx, input.Photo.File, input.Photo.Filename)
		if uploadErr == nil {
			finalPrimaryPhoto = result.URL
		} else {
			log.Printf("🔴 Primary photo upload failed: %v", uploadErr)
		}
	} else {
		// 🟢 THE CONDITION I MISSED: Frontend sent null (wants to delete it)
		// Access the current DB string we fetched and destroy it on Cloudinary
		if oldPrimaryPhoto != nil && *oldPrimaryPhoto != "" {
			if cleanErr := shopUploader.DeleteImageByURL(ctx, *oldPrimaryPhoto); cleanErr != nil {
				log.Printf("⚠️ Failed to delete removed primary image: %v", cleanErr)
			}
		}
		// Clear the string so it saves as empty/NULL in the database column
		finalPrimaryPhoto = ""
	}

	// =========================================================================
	// 2. BACKEND COMPARISON FOR GALLERY CAROUSEL (FIXED WITH ELSE CONDITION)
	// =========================================================================
	var finalPhotosSlice []string

	// Only trigger Cloudinary logic if a new set of files is explicitly sent
	if len(input.Photos) > 0 {
		// Rule: New files are sent. Delete all old gallery photos from Cloudinary.
		for _, oldURL := range oldPhotosSlice {
			if oldURL != "" {
				if cleanErr := shopUploader.DeleteImageByURL(ctx, oldURL); cleanErr != nil {
					log.Printf("⚠️ Failed to clean up overwritten gallery image %s: %v", oldURL, cleanErr)
				}
			}
		}

		// Reset the slice to prepare for the new uploads
		finalPhotosSlice = []string{}
		for _, upload := range input.Photos {
			if upload != nil && upload.File != nil {
				result, uploadErr := shopUploader.UploadImage(ctx, upload.File, upload.Filename)
				if uploadErr != nil {
					log.Printf("⚠️ Additional photo upload failed: %v", uploadErr)
					continue
				}
				finalPhotosSlice = append(finalPhotosSlice, result.URL)
			}
		}
	} else {
		// 🟢 THE CONDITION I MISSED: Frontend sent an empty or null array (wants to clear gallery)
		// Loop through the exact URLs currently in the DB and destroy them all on Cloudinary
		for _, oldURL := range oldPhotosSlice {
			if oldURL != "" {
				if cleanErr := shopUploader.DeleteImageByURL(ctx, oldURL); cleanErr != nil {
					log.Printf("⚠️ Failed to clean up deleted gallery image %s: %v", oldURL, cleanErr)
				}
			}
		}
		// Set it to an empty slice so it completely clears out your PostgreSQL column array
		finalPhotosSlice = []string{}
	}

	// =========================================================================
	// 3. SERIALIZE & UPDATE DATABASE
	// =========================================================================
	hoursJSON, _ := json.Marshal(input.BusinessHours)
	paymentsJSON, _ := json.Marshal(input.PaymentMethods)
	deliveryJSON, _ := json.Marshal(input.Delivery)
	socialJSON, _ := json.Marshal(input.SocialMedia)
	contactJSON, _ := json.Marshal(input.ContactDetails)
	coordinatesJSON, _ := json.Marshal(input.Coordinates)

	var currentStatus model.ShopStatus
	var currentVerification model.Verification
	_ = json.Unmarshal(statusJSON, &currentStatus)
	_ = json.Unmarshal(verificationJSON, &currentVerification)

	if finalPhotosSlice == nil {
		finalPhotosSlice = []string{}
	}

	updateQuery := `
		UPDATE shops 
		SET shop_name = $1, 
			address = $2, 
			description = $3, 
			photo = $4, 
			photos = $5,
			business_hours = $6, 
			payment_methods = $7, 
			delivery = $8, 
			social_media = $9, 
			contact_details = $10,
			coordinates = $11
		WHERE id = $12
		RETURNING id, created_at
	`
	var id string
	var createdAt time.Time

	err = r.Resolver.DB.QueryRow(ctx, updateQuery,
		input.ShopName,
		input.Address,
		input.Description,
		finalPrimaryPhoto, // Keeps old URL if no file sent, updates to new URL if file sent
		finalPhotosSlice,  // Keeps old URLs if no files sent, updates to new URLs if files sent
		hoursJSON,
		paymentsJSON,
		deliveryJSON,
		socialJSON,
		contactJSON,
		coordinatesJSON,
		input.ShopID,
	).Scan(&id, &createdAt)

	if err != nil {
		log.Printf("🔴 DATABASE UPDATE FAILED IN UPDATESHOP: %v", err)
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "internal server error: failed saving shop updates",
			Extensions: map[string]interface{}{"code": "INTERNAL_SERVER_ERROR"},
		})
		return nil, nil
	}

	return &model.OwnerShop{
		ID:          id,
		OwnerID:     currentUser.ID,
		ShopName:    input.ShopName,
		Address:     input.Address,
		Description: input.Description,
		Photo:       &finalPrimaryPhoto,
		Photos:      finalPhotosSlice,
		CreatedAt:   createdAt.Format(time.RFC3339),
		Coordinates: &model.Coordinates{
			Lat: input.Coordinates.Lat,
			Lng: input.Coordinates.Lng,
		},
		BusinessHours: &model.BusinessHours{
			OpenTime:  input.BusinessHours.OpenTime,
			CloseTime: input.BusinessHours.CloseTime,
			Days:      input.BusinessHours.Days,
		},
		PaymentMethods: &model.PaymentMethods{
			Cash:    input.PaymentMethods.Cash,
			Gcash:   input.PaymentMethods.Gcash,
			Paymaya: input.PaymentMethods.Paymaya,
			Card:    input.PaymentMethods.Card,
		},
		Delivery: &model.DeliveryOptions{
			Available: input.Delivery.Available,
			Radius:    input.Delivery.Radius,
			Fee:       input.Delivery.Fee,
			MinOrder:  input.Delivery.MinOrder,
		},
		SocialMedia: &model.SocialMedia{
			Facebook:  input.SocialMedia.Facebook,
			Instagram: input.SocialMedia.Instagram,
		},
		ContactDetails: &model.ContactDetails{
			Phone:   input.ContactDetails.Phone,
			Email:   input.ContactDetails.Email,
			Address: input.ContactDetails.Address,
		},
		Status:       &currentStatus,
		Verification: &currentVerification,
	}, nil
}

// DeleteShop is the resolver for the deleteShop field.
func (r *mutationResolver) DeleteShop(ctx context.Context, shopID string) (bool, error) {
	// SECURITY GUARD 1: Is user logged in?
	currentUser := ctx.Value("currentUser").(middleware.CachedUser)

	// SECURITY GUARD 2 & ASSET ACQUISITION: Fetch owner id and all associated photos before deleting the row
	var dbOwnerID string
	var oldPrimaryPhoto *string
	var oldPhotosSlice []string

	checkQuery := "SELECT owner_id, photo, photos FROM shops WHERE id = $1 LIMIT 1"
	err := r.Resolver.DB.QueryRow(ctx, checkQuery, shopID).Scan(&dbOwnerID, &oldPrimaryPhoto, &oldPhotosSlice)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			graphql.AddError(ctx, &gqlerror.Error{
				Message:    "not found: target resource does not exist",
				Extensions: map[string]interface{}{"code": "NOT_FOUND"},
			})
			return false, nil
		}
		return false, err
	}

	if dbOwnerID != currentUser.ID {
		log.Printf("⚠️ SECURITY ALERT: Deletion bypass attempt blocked on User ID %s for shop %s", currentUser.ID, shopID)
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "forbidden: you can only delete shops that you created",
			Extensions: map[string]interface{}{"code": "FORBIDDEN"},
		})
		return false, nil
	}

	// 1. INITIALIZE THE CLOUDINARY UPLOADER UTILITY DIRECTLY VIA OS ENVS
	uploader, err := imageutil.NewImageUploader(
		os.Getenv("CLOUDINARY_CLOUD_NAME"),
		os.Getenv("CLOUDINARY_API_KEY"),
		os.Getenv("CLOUDINARY_API_SECRET"),
		os.Getenv("CLOUDINARY_FOLDER"),
	)
	if err != nil {
		log.Printf("🔴 FAILED TO INITIALIZE CLOUDINARY UPLOADER IN DELETESHOP: %v", err)
		return false, fmt.Errorf("media processor error")
	}

	uploadFolder := fmt.Sprintf("%s/%s/shops", os.Getenv("CLOUDINARY_FOLDER"), currentUser.ID)
	shopUploader := uploader.WithFolder(uploadFolder)

	// 2. TRIGGER CLOUDINARY CLEANUP CODES FOR PRIMARY PHOTO
	if oldPrimaryPhoto != nil && *oldPrimaryPhoto != "" {
		if cleanErr := shopUploader.DeleteImageByURL(ctx, *oldPrimaryPhoto); cleanErr != nil {
			log.Printf("⚠️ Failed to remove primary shop image %s on deletion: %v", *oldPrimaryPhoto, cleanErr)
		}
	}

	// 3. TRIGGER CLOUDINARY CLEANUP CODES FOR ALL GALLERY CAROUSEL PHOTOS
	for _, oldURL := range oldPhotosSlice {
		if oldURL != "" {
			if cleanErr := shopUploader.DeleteImageByURL(ctx, oldURL); cleanErr != nil {
				log.Printf("⚠️ Failed to remove gallery shop image %s on deletion: %v", oldURL, cleanErr)
			}
		}
	}

	// 4. DATABASE ROW ELIMINATION
	deleteQuery := "DELETE FROM shops WHERE id = $1"
	_, err = r.Resolver.DB.Exec(ctx, deleteQuery, shopID)
	if err != nil {
		log.Printf("🔴 DATABASE DELETION FAILED IN DELETESHOP: %v", err)
		return false, err
	}

	return true, nil
}

// AddInventoryItem is the resolver for the addInventoryItem field.
func (r *mutationResolver) AddInventoryItem(ctx context.Context, input model.AddInventoryItemInput) (*model.OwnerInventoryItem, error) {
	// SECURITY GUARD 1: Is user logged in?
	currentUser := ctx.Value("currentUser").(middleware.CachedUser)

	// SECURITY GUARD 2: Verify the caller is the actual owner of the target shop
	var shopOwnerID string
	checkQuery := "SELECT owner_id FROM shops WHERE id = $1 LIMIT 1"
	err := r.Resolver.DB.QueryRow(ctx, checkQuery, input.ShopID).Scan(&shopOwnerID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			graphql.AddError(ctx, &gqlerror.Error{
				Message: "not found: target shop resource does not exist",
				Extensions: map[string]interface{}{
					"code": "NOT_FOUND",
				},
			})
			return nil, nil
		}
		graphql.AddError(ctx, &gqlerror.Error{
			Message: "internal server error: shop lookup failure",
			Extensions: map[string]interface{}{
				"code": "INTERNAL_SERVER_ERROR",
			},
		})
		return nil, nil
	}

	if shopOwnerID != currentUser.ID {
		log.Printf("⚠️ SECURITY ALERT: User %s tried to add items to shop %s owned by user %s", currentUser.ID, input.ShopID, shopOwnerID)
		graphql.AddError(ctx, &gqlerror.Error{
			Message: "forbidden: you do not have permission to modify this shop",
			Extensions: map[string]interface{}{
				"code": "FORBIDDEN",
			},
		})
		return nil, nil
	}

	query := `
		INSERT INTO inventory_items (
			shop_id, item_name, description, barcode, category, 
			unit_of_measure, photo, cost_price, selling_price, 
			stock_quantity, reorder_level, updated_at
		)
		VALUES ($1, $2, $3, $4, $5, $6, $7, COALESCE($8, 0.00), COALESCE($9, 0.00), COALESCE($10, 0), COALESCE($11, 5), NOW())
		RETURNING id, cost_price, selling_price, stock_quantity, reorder_level, updated_at
	`

	var insertedID string
	var costPrice, sellingPrice float64
	var stockQuantity, reorderLevel int
	var updatedAt time.Time

	err = r.Resolver.DB.QueryRow(ctx, query,
		input.ShopID, input.ItemName, input.Description, input.Barcode, input.Category,
		input.UnitOfMeasure, input.Photo, input.CostPrice, input.SellingPrice, input.StockQuantity, input.ReorderLevel,
	).Scan(&insertedID, &costPrice, &sellingPrice, &stockQuantity, &reorderLevel, &updatedAt)

	if err != nil {
		graphql.AddError(ctx, &gqlerror.Error{
			Message: "internal server error: failed to create inventory item entry",
			Extensions: map[string]interface{}{
				"code": "INTERNAL_SERVER_ERROR",
			},
		})
		return nil, nil
	}

	return &model.OwnerInventoryItem{
		ID:            insertedID,
		ShopID:        input.ShopID,
		ItemName:      input.ItemName,
		Description:   input.Description,
		Barcode:       input.Barcode,
		Category:      input.Category,
		UnitOfMeasure: input.UnitOfMeasure,
		Photo:         input.Photo,
		CostPrice:     &costPrice,
		SellingPrice:  &sellingPrice,
		StockQuantity: &stockQuantity,
		ReorderLevel:  &reorderLevel,
		UpdatedAt:     updatedAt.Format(time.RFC3339),
	}, nil
}

// UpdateInventoryItem is the resolver for the updateInventoryItem field.
func (r *mutationResolver) UpdateInventoryItem(ctx context.Context, input model.UpdateInventoryItemInput) (*model.OwnerInventoryItem, error) {
	currentUser := ctx.Value("currentUser").(middleware.CachedUser)

	// Verify owner through relation table JOIN
	var shopOwnerID string
	checkQuery := `
		SELECT s.owner_id FROM inventory_items i
		JOIN shops s ON i.shop_id = s.id
		WHERE i.id = $1 LIMIT 1
	`
	err := r.Resolver.DB.QueryRow(ctx, checkQuery, input.ItemID).Scan(&shopOwnerID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			graphql.AddError(ctx, &gqlerror.Error{
				Message:    "not found: target item does not exist",
				Extensions: map[string]interface{}{"code": "NOT_FOUND"},
			})
			return nil, nil
		}
		return nil, err
	}

	if shopOwnerID != currentUser.ID {
		log.Printf("⚠️ SECURITY ALERT: User %s tried to edit item %s owned by %s", currentUser.ID, input.ItemID, shopOwnerID)
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "forbidden: access denied to modify this item",
			Extensions: map[string]interface{}{"code": "FORBIDDEN"},
		})
		return nil, nil
	}

	updateQuery := `
		UPDATE inventory_items 
		SET item_name = $1, description = $2, barcode = $3, category = $4, unit_of_measure = $5, photo = $6,
		    cost_price = COALESCE($7, 0.00), selling_price = COALESCE($8, 0.00), stock_quantity = COALESCE($9, 0), reorder_level = COALESCE($10, 5), updated_at = NOW() 
		WHERE id = $11
		RETURNING id, shop_id, item_name, description, barcode, category, unit_of_measure, photo, cost_price, selling_price, stock_quantity, reorder_level, updated_at
	`
	var item model.OwnerInventoryItem
	var updatedAt time.Time

	err = r.Resolver.DB.QueryRow(ctx, updateQuery,
		input.ItemName, input.Description, input.Barcode, input.Category, input.UnitOfMeasure, input.Photo,
		input.CostPrice, input.SellingPrice, input.StockQuantity, input.ReorderLevel, input.ItemID,
	).Scan(
		&item.ID, &item.ShopID, &item.ItemName, &item.Description, &item.Barcode, &item.Category,
		&item.UnitOfMeasure, &item.Photo, &item.CostPrice, &item.SellingPrice, &item.StockQuantity, &item.ReorderLevel, &updatedAt,
	)
	if err != nil {
		return nil, err
	}

	item.UpdatedAt = updatedAt.Format(time.RFC3339)
	return &item, nil
}

// DeleteInventoryItem is the resolver for the deleteInventoryItem field.
func (r *mutationResolver) DeleteInventoryItem(ctx context.Context, itemID string) (bool, error) {
	currentUser := ctx.Value("currentUser").(middleware.CachedUser)

	var shopOwnerID string
	checkQuery := `
		SELECT s.owner_id FROM inventory_items i
		JOIN shops s ON i.shop_id = s.id
		WHERE i.id = $1 LIMIT 1
	`
	err := r.Resolver.DB.QueryRow(ctx, checkQuery, itemID).Scan(&shopOwnerID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			graphql.AddError(ctx, &gqlerror.Error{
				Message:    "not found: item does not exist",
				Extensions: map[string]interface{}{"code": "NOT_FOUND"},
			})
			return false, nil
		}
		return false, err
	}

	if shopOwnerID != currentUser.ID {
		log.Printf("⚠️ SECURITY ALERT: User %s tried to delete item %s owned by %s", currentUser.ID, itemID, shopOwnerID)
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "forbidden: access denied to delete this item",
			Extensions: map[string]interface{}{"code": "FORBIDDEN"},
		})
		return false, nil
	}

	deleteQuery := "DELETE FROM inventory_items WHERE id = $1"
	_, err = r.Resolver.DB.Exec(ctx, deleteQuery, itemID)
	if err != nil {
		return false, err
	}

	return true, nil
}

// IncrementStock is the resolver for the incrementStock field.
func (r *mutationResolver) IncrementStock(ctx context.Context, input model.IncrementStockInput) (*model.OwnerInventoryItem, error) {
	// SECURITY GUARD 1: Is user logged in?
	currentUser := ctx.Value("currentUser").(middleware.CachedUser)

	// SECURITY GUARD 2: Fetch the owner_id of the shop holding this item via a JOIN
	var shopOwnerID string
	checkQuery := `
		SELECT s.owner_id FROM inventory_items i
		JOIN shops s ON i.shop_id = s.id
		WHERE i.id = $1 LIMIT 1
	`
	err := r.Resolver.DB.QueryRow(ctx, checkQuery, input.ItemID).Scan(&shopOwnerID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			graphql.AddError(ctx, &gqlerror.Error{
				Message: "not found: target item does not exist",
				Extensions: map[string]interface{}{
					"code": "NOT_FOUND",
				},
			})
			return nil, nil
		}
		graphql.AddError(ctx, &gqlerror.Error{
			Message: "internal server error: item verification failure",
			Extensions: map[string]interface{}{
				"code": "INTERNAL_SERVER_ERROR",
			},
		})
		return nil, nil
	}

	if shopOwnerID != currentUser.ID {
		log.Printf("⚠️ SECURITY ALERT: User %s tried to increment stock for item %s owned by user %s", currentUser.ID, input.ItemID, shopOwnerID)
		graphql.AddError(ctx, &gqlerror.Error{
			Message: "forbidden: access denied to modify this item",
			Extensions: map[string]interface{}{
				"code": "FORBIDDEN",
			},
		})
		return nil, nil
	}

	// Perform atomic addition update directly in PostgreSQL
	updateQuery := `
		UPDATE inventory_items 
		SET stock_quantity = stock_quantity + $1, updated_at = NOW() 
		WHERE id = $2
		RETURNING id, shop_id, item_name, description, barcode, category, unit_of_measure, photo, cost_price, selling_price, stock_quantity, reorder_level, updated_at
	`

	var item model.OwnerInventoryItem
	var updatedAt time.Time

	err = r.Resolver.DB.QueryRow(ctx, updateQuery, input.QuantityToAdd, input.ItemID).Scan(
		&item.ID, &item.ShopID, &item.ItemName, &item.Description, &item.Barcode, &item.Category,
		&item.UnitOfMeasure, &item.Photo, &item.CostPrice, &item.SellingPrice, &item.StockQuantity, &item.ReorderLevel, &updatedAt,
	)

	if err != nil {
		graphql.AddError(ctx, &gqlerror.Error{
			Message: "internal server error: stock adjustment execution failure",
			Extensions: map[string]interface{}{
				"code": "INTERNAL_SERVER_ERROR",
			},
		})
		return nil, nil
	}

	item.UpdatedAt = updatedAt.Format(time.RFC3339)
	return &item, nil
}

// DecrementStock is the resolver for the decrementStock field.
func (r *mutationResolver) DecrementStock(ctx context.Context, input model.DecrementStockInput) (*model.OwnerInventoryItem, error) {
	// SECURITY GUARD 1: Is user logged in?
	currentUser := ctx.Value("currentUser").(middleware.CachedUser)

	// SECURITY GUARD 2: Fetch the owner_id of the shop holding this item via a JOIN to verify resource ownership
	var shopOwnerID string
	checkQuery := `
		SELECT s.owner_id FROM inventory_items i
		JOIN shops s ON i.shop_id = s.id
		WHERE i.id = $1 LIMIT 1
	`
	err := r.Resolver.DB.QueryRow(ctx, checkQuery, input.ItemID).Scan(&shopOwnerID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			graphql.AddError(ctx, &gqlerror.Error{
				Message: "not found: target item does not exist",
				Extensions: map[string]interface{}{
					"code": "NOT_FOUND",
				},
			})
			return nil, nil
		}
		graphql.AddError(ctx, &gqlerror.Error{
			Message: "internal server error: item verification failure",
			Extensions: map[string]interface{}{
				"code": "INTERNAL_SERVER_ERROR",
			},
		})
		return nil, nil
	}

	// Block operation if the logged-in user does not own the shop containing this item
	if shopOwnerID != currentUser.ID {
		log.Printf("⚠️ SECURITY ALERT: User %s tried to decrement stock for item %s owned by user %s", currentUser.ID, input.ItemID, shopOwnerID)
		graphql.AddError(ctx, &gqlerror.Error{
			Message: "forbidden: access denied to modify this item",
			Extensions: map[string]interface{}{
				"code": "FORBIDDEN",
			},
		})
		return nil, nil
	}

	// Perform atomic deduction update directly in PostgreSQL
	// GREATEST(0, stock_quantity - $1) ensures stock level never dips below zero
	updateQuery := `
		UPDATE inventory_items 
		SET stock_quantity = GREATEST(0, stock_quantity - $1), updated_at = NOW() 
		WHERE id = $2
		RETURNING id, shop_id, item_name, description, barcode, category, unit_of_measure, photo, cost_price, selling_price, stock_quantity, reorder_level, updated_at
	`
	var item model.OwnerInventoryItem
	var updatedAt time.Time

	err = r.Resolver.DB.QueryRow(ctx, updateQuery, input.QuantityToRemove, input.ItemID).Scan(
		&item.ID, &item.ShopID, &item.ItemName, &item.Description, &item.Barcode, &item.Category,
		&item.UnitOfMeasure, &item.Photo, &item.CostPrice, &item.SellingPrice, &item.StockQuantity, &item.ReorderLevel, &updatedAt,
	)
	if err != nil {
		graphql.AddError(ctx, &gqlerror.Error{
			Message: "internal server error: stock adjustment failed",
			Extensions: map[string]interface{}{
				"code": "INTERNAL_SERVER_ERROR",
			},
		})
		return nil, nil
	}

	item.UpdatedAt = updatedAt.Format(time.RFC3339)
	return &item, nil
}

// GetMyShops is the resolver for the getMyShops field.
func (r *queryResolver) GetMyShops(ctx context.Context, limit int, offset int) (*model.PaginatedOwnerShops, error) {
	// SECURITY GUARD: Enforce valid user identity state from Redis session
	currentUser := ctx.Value("currentUser").(middleware.CachedUser)

	// 1. Get total record count for metadata pagination calculation based on current owner
	var totalCount int64
	countQuery := "SELECT COUNT(*) FROM shops WHERE owner_id = $1"
	err := r.Resolver.DB.QueryRow(ctx, countQuery, currentUser.ID).Scan(&totalCount)
	if err != nil {
		graphql.AddError(ctx, &gqlerror.Error{
			Message: "internal server error: analytical tracking aggregation failure",
			Extensions: map[string]interface{}{
				"code": "INTERNAL_SERVER_ERROR",
			},
		})
		return nil, nil
	}

	// 2. Fetch the paginated subset from PostgreSQL (Matching your exact table schema columns)
	selectQuery := `
		SELECT id, shop_name, address, description, photo, photos, owner_id, created_at, 
		       verification, contact_details, status, coordinates, business_hours, payment_methods, delivery, social_media
		FROM shops 
		WHERE owner_id = $1
		ORDER BY created_at DESC 
		LIMIT $2 OFFSET $3
	`
	rows, err := r.Resolver.DB.Query(ctx, selectQuery, currentUser.ID, limit, offset)
	if err != nil {
		log.Printf("🔴 Error getting shops: %v", err)
		graphql.AddError(ctx, &gqlerror.Error{
			Message: "internal server error: collection retrieval failure",
			Extensions: map[string]interface{}{
				"code": "INTERNAL_SERVER_ERROR",
			},
		})
		return nil, nil
	}
	defer rows.Close()

	var shops []*model.OwnerShop
	for rows.Next() {
		var shop model.OwnerShop
		var createdAt time.Time

		// Allocate temporary raw byte buffers to hold JSONB structures from PostgreSQL columns
		var verificationBytes []byte
		var contactBytes []byte
		var statusBytes []byte
		var coordinatesBytes []byte
		var hoursBytes []byte
		var paymentsBytes []byte
		var deliveryBytes []byte
		var socialBytes []byte

		// FIXED: Scan all 16 incoming column positions perfectly 1-to-1
		err := rows.Scan(
			&shop.ID, &shop.ShopName, &shop.Address, &shop.Description,
			&shop.Photo, &shop.Photos, &shop.OwnerID, &createdAt,
			&verificationBytes, &contactBytes, &statusBytes, &coordinatesBytes,
			&hoursBytes, &paymentsBytes, &deliveryBytes, &socialBytes,
		)
		if err != nil {
			log.Printf("🔴 Rows scan decoding anomaly details: %v", err)
			graphql.AddError(ctx, &gqlerror.Error{
				Message: "internal server error: data decoding anomaly",
				Extensions: map[string]interface{}{
					"code": "INTERNAL_SERVER_ERROR",
				},
			})
			return nil, nil
		}

		// Initialize structural payload containers to prevent nil pointer encoding memory exceptions
		shop.Verification = &model.Verification{}
		shop.ContactDetails = &model.ContactDetails{}
		shop.Status = &model.ShopStatus{}
		shop.Coordinates = &model.Coordinates{}
		shop.BusinessHours = &model.BusinessHours{}
		shop.PaymentMethods = &model.PaymentMethods{}
		shop.Delivery = &model.DeliveryOptions{}
		shop.SocialMedia = &model.SocialMedia{}

		// Safely decode JSON buffers straight back into your model layouts
		_ = json.Unmarshal(verificationBytes, shop.Verification)
		_ = json.Unmarshal(contactBytes, shop.ContactDetails)
		_ = json.Unmarshal(statusBytes, shop.Status)
		_ = json.Unmarshal(coordinatesBytes, shop.Coordinates)
		_ = json.Unmarshal(hoursBytes, shop.BusinessHours)
		_ = json.Unmarshal(paymentsBytes, shop.PaymentMethods)
		_ = json.Unmarshal(deliveryBytes, shop.Delivery)
		_ = json.Unmarshal(socialBytes, shop.SocialMedia)

		shop.CreatedAt = createdAt.Format(time.RFC3339)
		shops = append(shops, &shop)
	}

	if err := rows.Err(); err != nil {
		graphql.AddError(ctx, &gqlerror.Error{
			Message: "internal server error: active data stream break",
			Extensions: map[string]interface{}{
				"code": "INTERNAL_SERVER_ERROR",
			},
		})
		return nil, nil
	}

	// 3. Compute structural limits for layout boundary checks
	hasNextPage := int64(offset+limit) < totalCount

	return &model.PaginatedOwnerShops{
		Shops:       shops,
		TotalCount:  int(totalCount),
		HasNextPage: hasNextPage,
	}, nil
}

// GetShopInventory is the resolver for the getShopInventory field.
func (r *queryResolver) GetShopInventory(ctx context.Context, shopID string, limit int, offset int) (*model.PaginatedOwnerInventory, error) {
	// SECURITY GUARD 1: Is user logged in?
	currentUser := ctx.Value("currentUser").(middleware.CachedUser)

	// SECURITY GUARD 2: Verify the caller is the actual owner of the shop before pulling internal records
	var shopOwnerID string
	checkQuery := "SELECT owner_id FROM shops WHERE id = $1 LIMIT 1"
	err := r.Resolver.DB.QueryRow(ctx, checkQuery, shopID).Scan(&shopOwnerID)
	if err != nil {
		if errors.Is(err, pgx.ErrNoRows) {
			graphql.AddError(ctx, &gqlerror.Error{
				Message:    "not found: target shop resource does not exist",
				Extensions: map[string]interface{}{"code": "NOT_FOUND"},
			})
			return nil, nil
		}
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "internal server error: ownership confirmation failure",
			Extensions: map[string]interface{}{"code": "INTERNAL_SERVER_ERROR"},
		})
		return nil, nil
	}

	// Block operation if the logged-in user doesn't own this shop
	if shopOwnerID != currentUser.ID {
		log.Printf("⚠️ SECURITY ALERT: User %s tried to view internal inventory records for shop %s owned by user %s", currentUser.ID, shopID, shopOwnerID)
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "forbidden: access denied to view inventory metrics",
			Extensions: map[string]interface{}{"code": "FORBIDDEN"},
		})
		return nil, nil
	}

	// 1. Fetch total item count for the owner's pagination metrics
	var totalCount int64
	countQuery := "SELECT COUNT(*) FROM inventory_items WHERE shop_id = $1"
	err = r.Resolver.DB.QueryRow(ctx, countQuery, shopID).Scan(&totalCount)
	if err != nil {
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "internal server error: analytical tracking aggregation failure",
			Extensions: map[string]interface{}{"code": "INTERNAL_SERVER_ERROR"},
		})
		return nil, nil
	}

	// 2. Fetch complete list including sensitive details (cost_price, reorder_level)
	selectQuery := `
		SELECT id, shop_id, item_name, description, barcode, category, unit_of_measure, photo, cost_price, selling_price, stock_quantity, reorder_level, updated_at 
		FROM inventory_items 
		WHERE shop_id = $1
		ORDER BY item_name ASC 
		LIMIT $2 OFFSET $3
	`
	rows, err := r.Resolver.DB.Query(ctx, selectQuery, shopID, limit, offset)
	if err != nil {
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "internal server error: collection retrieval failure",
			Extensions: map[string]interface{}{"code": "INTERNAL_SERVER_ERROR"},
		})
		return nil, nil
	}
	defer rows.Close()

	var items []*model.OwnerInventoryItem
	for rows.Next() {
		var item model.OwnerInventoryItem
		var updatedAt time.Time

		err := rows.Scan(
			&item.ID, &item.ShopID, &item.ItemName, &item.Description, &item.Barcode, &item.Category,
			&item.UnitOfMeasure, &item.Photo, &item.CostPrice, &item.SellingPrice, &item.StockQuantity, &item.ReorderLevel, &updatedAt,
		)
		if err != nil {
			graphql.AddError(ctx, &gqlerror.Error{
				Message:    "internal server error: data decoding anomaly",
				Extensions: map[string]interface{}{"code": "INTERNAL_SERVER_ERROR"},
			})
			return nil, nil
		}
		item.UpdatedAt = updatedAt.Format(time.RFC3339)
		items = append(items, &item)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	hasNextPage := int64(offset+limit) < totalCount

	return &model.PaginatedOwnerInventory{
		Items:       items,
		TotalCount:  int(totalCount),
		HasNextPage: hasNextPage,
	}, nil
}

// SearchShop is the resolver for the searchShop field.
func (r *queryResolver) SearchShop(ctx context.Context, query string, limit int, offset int) (*model.PaginatedShops, error) {
	// 1. Get total record count matching search parameter
	var totalCount int64
	countQuery := "SELECT COUNT(*) FROM shops WHERE shop_name ILIKE $1 OR address ILIKE $1"
	searchPattern := "%" + query + "%"

	err := r.Resolver.DB.QueryRow(ctx, countQuery, searchPattern).Scan(&totalCount)
	if err != nil {
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "internal server error: store search aggregation failure",
			Extensions: map[string]interface{}{"code": "INTERNAL_SERVER_ERROR"},
		})
		return nil, nil
	}

	// 2. Fetch the paginated public subset (No ownerId column requested)
	selectQuery := `
		SELECT id, shop_name, address, description, photo, photos, created_at, 
		       verification, contact_details, status, coordinates, business_hours, payment_methods, delivery, social_media
		FROM shops 
		WHERE shop_name ILIKE $1 OR address ILIKE $1
		ORDER BY shop_name ASC 
		LIMIT $2 OFFSET $3
	`
	rows, err := r.Resolver.DB.Query(ctx, selectQuery, searchPattern, limit, offset)
	if err != nil {
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "internal server error: store collection search failure",
			Extensions: map[string]interface{}{"code": "INTERNAL_SERVER_ERROR"},
		})
		return nil, nil
	}
	defer rows.Close()

	var shops []*model.Shop
	for rows.Next() {
		var shop model.Shop
		var createdAt time.Time

		// Allocate temporary raw byte buffers to hold JSONB structures from PostgreSQL columns
		var verificationBytes []byte
		var contactBytes []byte
		var statusBytes []byte
		var coordinatesBytes []byte
		var hoursBytes []byte
		var paymentsBytes []byte
		var deliveryBytes []byte
		var socialBytes []byte

		// FIXED: Scan all 15 columns perfectly 1-to-1 matching position order
		err := rows.Scan(
			&shop.ID, &shop.ShopName, &shop.Address, &shop.Description, &shop.Photo, &shop.Photos, &createdAt,
			&verificationBytes, &contactBytes, &statusBytes, &coordinatesBytes,
			&hoursBytes, &paymentsBytes, &deliveryBytes, &socialBytes,
		)
		if err != nil {
			log.Printf("🔴 Public search rows scan decoding anomaly details: %v", err)
			graphql.AddError(ctx, &gqlerror.Error{
				Message:    "internal server error: data rendering exception",
				Extensions: map[string]interface{}{"code": "INTERNAL_SERVER_ERROR"},
			})
			return nil, nil
		}

		// Initialize structural payload containers to prevent nil pointer encoding memory exceptions
		shop.Verification = &model.Verification{}
		shop.ContactDetails = &model.ContactDetails{}
		shop.Status = &model.ShopStatus{}
		shop.Coordinates = &model.Coordinates{}
		shop.BusinessHours = &model.BusinessHours{}
		shop.PaymentMethods = &model.PaymentMethods{}
		shop.Delivery = &model.DeliveryOptions{}
		shop.SocialMedia = &model.SocialMedia{}

		// Safely decode JSON buffers straight back into your model layouts
		_ = json.Unmarshal(verificationBytes, shop.Verification)
		_ = json.Unmarshal(contactBytes, shop.ContactDetails)
		_ = json.Unmarshal(statusBytes, shop.Status)
		_ = json.Unmarshal(coordinatesBytes, shop.Coordinates)
		_ = json.Unmarshal(hoursBytes, shop.BusinessHours)
		_ = json.Unmarshal(paymentsBytes, shop.PaymentMethods)
		_ = json.Unmarshal(deliveryBytes, shop.Delivery)
		_ = json.Unmarshal(socialBytes, shop.SocialMedia)

		// Initialize reviews as empty slice to avoid frontend nil panics
		shop.Reviews = []*model.ShopReview{}
		shop.CreatedAt = createdAt.Format(time.RFC3339)
		shops = append(shops, &shop)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	hasNextPage := int64(offset+limit) < totalCount

	return &model.PaginatedShops{
		Shops:       shops,
		TotalCount:  int(totalCount),
		HasNextPage: hasNextPage,
	}, nil
}

// SearchProduct is the resolver for the searchProduct field.
func (r *queryResolver) SearchProduct(ctx context.Context, query string, limit int, offset int) (*model.PaginatedPublicProducts, error) {
	// 1. Get total items matching item name or category string
	var totalCount int64
	countQuery := "SELECT COUNT(*) FROM inventory_items WHERE item_name ILIKE $1 OR category ILIKE $1"
	searchPattern := "%" + query + "%"

	err := r.Resolver.DB.QueryRow(ctx, countQuery, searchPattern).Scan(&totalCount)
	if err != nil {
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "internal server error: product search count failure",
			Extensions: map[string]interface{}{"code": "INTERNAL_SERVER_ERROR"},
		})
		return nil, nil
	}

	// 2. Fetch public fields only. cost_price and reorder_level are completely skipped.
	selectQuery := `
		SELECT id, shop_id, item_name, description, category, unit_of_measure, photo, selling_price, stock_quantity
		FROM inventory_items 
		WHERE item_name ILIKE $1 OR category ILIKE $1
		ORDER BY item_name ASC 
		LIMIT $2 OFFSET $3
	`
	rows, err := r.Resolver.DB.Query(ctx, selectQuery, searchPattern, limit, offset)
	if err != nil {
		graphql.AddError(ctx, &gqlerror.Error{
			Message:    "internal server error: product collection search failure",
			Extensions: map[string]interface{}{"code": "INTERNAL_SERVER_ERROR"},
		})
		return nil, nil
	}
	defer rows.Close()

	var products []*model.PublicProduct
	for rows.Next() {
		var prod model.PublicProduct

		err := rows.Scan(
			&prod.ID, &prod.ShopID, &prod.ItemName, &prod.Description,
			&prod.Category, &prod.UnitOfMeasure, &prod.Photo, &prod.SellingPrice, &prod.StockQuantity,
		)
		if err != nil {
			graphql.AddError(ctx, &gqlerror.Error{
				Message:    "internal server error: item decoding failure",
				Extensions: map[string]interface{}{"code": "INTERNAL_SERVER_ERROR"},
			})
			return nil, nil
		}
		products = append(products, &prod)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	hasNextPage := int64(offset+limit) < totalCount

	return &model.PaginatedPublicProducts{
		Products:    products,
		TotalCount:  int(totalCount),
		HasNextPage: hasNextPage,
	}, nil
}
